// GENERATED by pops.codegen.program_codegen.emit_cpp_program (epic ADC-399 / ADC-401). Do not edit.
// A compiled time Program installed across the stable .so ABI: it drives sim.step(dt) entirely in
// C++ via the shared Program execution service and its topology provider (no runtime reimplementation).
#if !defined(POPS_RUNTIME_SHARED_EXCEPTION_ABI)
#error "generated Program loaders require the shared runtime exception ABI consumer contract"
#endif
#include <pops/core/foundation/native_dimension.hpp>
#include <pops/runtime/program/program_context.hpp>
#include <pops/numerics/diffusion/prepared_diffusion.hpp>
#include <pops/runtime/program/step_transaction.hpp>
#include <pops/numerics/linalg/finite_linear.hpp>
#include <pops/runtime/dynamic/abi_key.hpp>
#include <pops/mesh/storage/multifab.hpp>
#include <pops/mesh/storage/field_view.hpp>     // exact-ranked per-cell handles
#include <pops/mesh/execution/for_each.hpp>     // for_each_cell (Phase-4b per-cell kernels)
#include <pops/numerics/linalg/dense_eig.hpp>   // pops::detail::mat_inverse (local dense solve)
#include <pops/numerics/nonlinear/local_nonlinear_collective.hpp>  // exact failure location
#include <pops/numerics/nonlinear/prepared_local_nonlinear.hpp>  // one prepared local solver
#include <pops/numerics/elliptic/linear/generic_krylov.hpp>  // prepared affine Krylov route
#include <pops/core/foundation/types.hpp>
#include <array>                               // exact-ranked axis packs
#include <chrono>                              // std::chrono::steady_clock (per-node profiling pair, ADC-459)
#include <cmath>                               // std::sqrt / std::fabs / std::pow in lowered formulas
#include <limits>                              // std::numeric_limits (dt_bound +inf sentinel)
#include <functional>                          // per-level AMR persistent Program closures
#include <memory>                              // std::make_shared (persistent matrix-free scratch)
#include <optional>                            // exact ProviderPack contract optional unit/kind
#include <stdexcept>                           // std::runtime_error (AMR install fail-loud, ADC-508)
#include <utility>                             // std::as_const (read-only field views)
#include <vector>                              // pointer list for the coupled multi-block field-solve (ADC-457)


extern "C" const char* pops_program_abi_key() { return POPS_ABI_KEY_LITERAL; }
extern "C" const char* pops_program_route_manifest() { return "v4:d47b60d2276e0255873cb7573417de84f0d4fcfb7d2adb5b77813420ae8e0d01"; }
extern "C" const char* pops_program_name() { return "finite_condensed"; }
extern "C" const char* pops_program_hash() { return "92cd521de5b7c6f5692a681a9c05eb03519e60a3c183c89b57c806beab5d191b"; }
// Selective-history replay authorities (fail-closed native allow-list).
extern "C" int pops_program_history_replay_authority_count() { return 0; }
extern "C" const char* pops_program_history_replay_authority_name(int i) {
  switch (i) {
    default: return "";
  }
}
extern "C" int pops_program_history_replay_authority_depth(int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" int pops_program_operator_authority_count() { return 0; }
extern "C" std::uint64_t pops_program_operator_authority_word(int operator_index, int word_index) {
  if (operator_index < 0 || operator_index >= 0 || word_index < 0 || word_index >= 4)
    return UINT64_C(0);
  
  return UINT64_C(0);
}


// NAME-based block binding (Spec 3 criterion 23, ADC-457): the Program's block names in
// T.state declaration order. install_program matches each to a System block BY NAME (not
// add-order) and builds the program-index -> system-index map the provider resolves.
extern "C" int pops_program_block_count() { return 2; }
extern "C" const char* pops_program_block_name(int i) {
  switch (i) {
    case 0: return "velocity";
    case 1: return "potential";
    default: return "";
  }
}

// GeneratedModule metadata (Spec 2 / ADC-442): the typed operator registry exposed by
// the .so for introspection + install-time validation. OperatorId = the array index.
// NOT called from any hot kernel -- operators are inlined at codegen.
extern "C" int pops_module_operator_count() { return 0; }
extern "C" int pops_module_state_space_count() { return 2; }
extern "C" int pops_module_field_space_count() { return 2; }
extern "C" const char* pops_module_operator_name(int i) {
  switch (i) {
    default: return "";
  }
}
extern "C" const char* pops_module_operator_kind(int i) {
  switch (i) {
    default: return "";
  }
}
extern "C" const char* pops_module_operator_signature(int i) {
  switch (i) {
    default: return "";
  }
}
extern "C" const char* pops_module_operator_requirements(int i) {
  switch (i) {
    default: return "";
  }
}
extern "C" const char* pops_module_operator_owner(int i) {
  switch (i) {
    default: return "";
  }
}
extern "C" const char* pops_module_state_space_name(int i) {
  switch (i) {
    case 0: return "phi";
    case 1: return "v";
    default: return "";
  }
}
extern "C" const char* pops_module_state_space_owner(int i) {
  switch (i) {
    case 0: return "model_definition:potential_dofs@pops.module%3Asha256%3Aeba7b10f4659ba30e2315381856e2f6a5c189cfb970e820c8a4d6cdb9064970a";
    case 1: return "model_definition:velocity_dofs@pops.module%3Asha256%3Aaf548c75173a6594dd5fcf10984338155a754cb22ce838a63dc77ec1e47a3a03";
    default: return "";
  }
}
extern "C" const char* pops_module_field_space_name(int i) {
  switch (i) {
    case 0: return "fields";
    case 1: return "fields";
    default: return "";
  }
}
extern "C" const char* pops_module_field_space_owner(int i) {
  switch (i) {
    case 0: return "model_definition:potential_dofs@pops.module%3Asha256%3Aeba7b10f4659ba30e2315381856e2f6a5c189cfb970e820c8a4d6cdb9064970a";
    case 1: return "model_definition:velocity_dofs@pops.module%3Asha256%3Aaf548c75173a6594dd5fcf10984338155a754cb22ce838a63dc77ec1e47a3a03";
    default: return "";
  }
}

// RUNTIME-parameter metadata (ADC-510, Spec 5 C5): per flat parameter, its PROGRAM block
// index, its stable within-block index (sorted-name order, the index the lowered runtime read
// uses) and its name. Carrier values are neutral here; BindSchema installs defaults/values.
// NOT called from any hot kernel.
extern "C" int pops_program_param_count() { return 0; }
extern "C" int pops_program_param_block(int i) {
  static const int v[] = {0};
  return (i >= 0 && i < 0) ? v[i] : -1;
}
extern "C" int pops_program_param_index(int i) {
  static const int v[] = {0};
  return (i >= 0 && i < 0) ? v[i] : -1;
}
extern "C" const char* pops_program_param_name(int i) {
  switch (i) {
    default: return "";
  }
}
extern "C" double pops_program_param_default(int i) {
  static const double v[] = {0.0};
  return (i >= 0 && i < 0) ? v[i] : 0.0;
}


extern "C" void pops_install_program(pops::System<pops::kNativeDimension>* sys) {
  auto ctx_owner = pops::runtime::program::make_program_execution_provider(sys);
  auto& ctx = *ctx_owner;
  ctx.configure_primary_clock("pops.clock.v1::sha256:3d4af201d12c5fd55c27937c4031da304c96352325694331dffabf551d209885");
  ctx.install([=](double dt) {
    auto& ctx = *ctx_owner;
    (void)dt;
    ctx.begin_step(dt);
    pops::MultiFab<pops::kNativeDimension>& u0 = ctx.state(0);
    const auto _pt1 = std::chrono::steady_clock::now();  // ProfileScope "node:v_seed"
    pops::MultiFab<pops::kNativeDimension>& u1 = ctx.scratch_state(1, 0, u0);
    ctx.axpy(u1, static_cast<pops::Real>(0), u0, dt, {});
    ctx.profile_record("node:v_seed", _pt1);
    pops::MultiFab<pops::kNativeDimension>& u2 = ctx.state(1);
    const auto _pt3 = std::chrono::steady_clock::now();  // ProfileScope "node:p_seed"
    pops::MultiFab<pops::kNativeDimension>& u3 = ctx.scratch_state(3, 0, u2);
    ctx.axpy(u3, static_cast<pops::Real>(0), u2, dt, {});
    ctx.profile_record("node:p_seed", _pt3);
    const auto _pt7 = std::chrono::steady_clock::now();  // ProfileScope "node:local_product"
    ctx.require_cartesian_generated_operator(1, "solve_coupled_implicit");
    pops::MultiFab<pops::kNativeDimension>& ci7_potential = ctx.scratch_state(7, 0, u3);
    pops::MultiFab<pops::kNativeDimension>& ci_status_7 = ctx.scalar_scratch(7, 0, u3, 11, 0);
    {
    long product_layout_error_ = 0;
    product_layout_error_ |= (u3.layout() != ci7_potential.layout() || u3.distribution() != ci7_potential.distribution() || u3.local_rank() != ci7_potential.local_rank());
    product_layout_error_ |= (u2.layout() != ci7_potential.layout() || u2.distribution() != ci7_potential.distribution() || u2.local_rank() != ci7_potential.local_rank());
    product_layout_error_ |= (u0.layout() != ci7_potential.layout() || u0.distribution() != ci7_potential.distribution() || u0.local_rank() != ci7_potential.local_rank());
    if (pops::all_reduce_max(product_layout_error_, ctx.prepared_execution_lane()))
      throw std::runtime_error("local product requires co-located layouts, distributions and ranks");
    for (int li = 0; li < ci7_potential.local_size(); ++li) {
      const pops::FieldView<pops::Real, pops::kNativeDimension> ci7_potentialA = ci7_potential.fab(li).view();
      const pops::FieldView<pops::Real, pops::kNativeDimension> ci_status_7A = ci_status_7.fab(li).view();
      const pops::FieldView<const pops::Real, pops::kNativeDimension> u3A = std::as_const(u3).fab(li).view();
      const pops::FieldView<const pops::Real, pops::kNativeDimension> u2A = std::as_const(u2).fab(li).view();
      const pops::FieldView<const pops::Real, pops::kNativeDimension> u0A = std::as_const(u0).fab(li).view();
      pops::for_each_cell(ci7_potential.box(li), [=] POPS_HD(const pops::CellIndex<pops::kNativeDimension>& index) {
        pops::Real G_[4];
        G_[0] = u3A(index, 0);
        G_[1] = u3A(index, 1);
        G_[2] = u3A(index, 2);
        G_[3] = u3A(index, 3);
        auto residual_eval = [&](const pops::Real (&Ueval)[4], pops::Real (&rout)[4]) {
          const pops::Real cse0_ = u0A(index, 0);
          const pops::Real cse1_ = Ueval[0];
          const pops::Real cse2_ = Ueval[1];
          const pops::Real cse3_ = Ueval[2];
          const pops::Real cse4_ = Ueval[3];
          const pops::Real cse5_ = u0A(index, 1);
          const pops::Real cse6_ = u0A(index, 2);
          const pops::Real cse7_ = u0A(index, 3);
          const pops::Real cse8_ = u0A(index, 4);
          const pops::Real cse9_ = u0A(index, 5);
          const pops::Real cse10_ = u0A(index, 6);
          const pops::Real cse11_ = u0A(index, 7);
          const pops::Real cse12_ = u2A(index, 0);
          const pops::Real cse13_ = u2A(index, 1);
          const pops::Real cse14_ = u2A(index, 2);
          const pops::Real cse15_ = u2A(index, 3);
          const auto cse16_ = pops::detail::finite_linear_apply<8, 4>(Kokkos::Array<pops::Real, 32>{pops::Real(-0.013589167320797008), pops::Real(-0.02193018605372624), pops::Real(0.04142813657619906), pops::Real(-0.024503221356819312), pops::Real(-0.018952739845989667), pops::Real(0.03500480498338109), pops::Real(-0.01872373501631816), pops::Real(-0.038775202176527954), pops::Real(0.015390439246600059), pops::Real(-0.00047294549644802235), pops::Real(-0.0012598770839013908), pops::Real(-0.0117124489626006), pops::Real(-0.0294645981595671), pops::Real(-0.058009349426267134), pops::Real(0.03399833914900236), pops::Real(-0.016725503464515436), pops::Real(0.0031210578204783875), pops::Real(0.012359973645102832), pops::Real(-0.015103636923168908), pops::Real(-0.04800107111095276), pops::Real(-0.06605385022461835), pops::Real(0.0502117069605897), pops::Real(-0.008188673080440991), pops::Real(-0.036152827017070614), pops::Real(0.002321237863549344), pops::Real(-0.028717544833747846), pops::Real(-0.011932632024937653), pops::Real(-0.00525683887627116), pops::Real(-0.011145372748310683), pops::Real(-0.010564530460494033), pops::Real(0.01557827210419707), pops::Real(0.016884203346276324)}, Kokkos::Array<pops::Real, 4>{cse1_, cse2_, cse3_, cse4_});
          const auto cse17_ = pops::detail::finite_linear_apply<4, 4>(Kokkos::Array<pops::Real, 16>{pops::Real(6.834843990426089), pops::Real(-2.1005507381677084), pops::Real(-1.0409059215957308), pops::Real(3.798068208843949), pops::Real(-2.1005507381677084), pops::Real(9.646520977899726), pops::Real(-4.394802400698765), pops::Real(-2.5335339628924682), pops::Real(-1.0409059215957308), pops::Real(-4.394802400698765), pops::Real(4.338430658016501), pops::Real(0.5597775399173847), pops::Real(3.798068208843949), pops::Real(-2.5335339628924682), pops::Real(0.5597775399173847), pops::Real(7.1607649936326725)}, Kokkos::Array<pops::Real, 4>{cse1_, cse2_, cse3_, cse4_});
          const auto cse18_ = pops::detail::finite_linear_apply<4, 4>(Kokkos::Array<pops::Real, 16>{pops::Real(6.834843990426089), pops::Real(-2.1005507381677084), pops::Real(-1.0409059215957308), pops::Real(3.798068208843949), pops::Real(-2.1005507381677084), pops::Real(9.646520977899726), pops::Real(-4.394802400698765), pops::Real(-2.5335339628924682), pops::Real(-1.0409059215957308), pops::Real(-4.394802400698765), pops::Real(4.338430658016501), pops::Real(0.5597775399173847), pops::Real(3.798068208843949), pops::Real(-2.5335339628924682), pops::Real(0.5597775399173847), pops::Real(7.1607649936326725)}, Kokkos::Array<pops::Real, 4>{cse12_, cse13_, cse14_, cse15_});
          const pops::Real cse19_ = cse16_[0];
          const pops::Real cse20_ = cse16_[1];
          const pops::Real cse21_ = cse16_[2];
          const pops::Real cse22_ = cse16_[3];
          const pops::Real cse23_ = cse16_[4];
          const pops::Real cse24_ = cse16_[5];
          const pops::Real cse25_ = cse16_[6];
          const pops::Real cse26_ = cse16_[7];
          const pops::Real cse27_ = cse17_[0];
          const pops::Real cse28_ = cse18_[0];
          const pops::Real cse29_ = cse17_[1];
          const pops::Real cse30_ = cse18_[1];
          const pops::Real cse31_ = cse17_[2];
          const pops::Real cse32_ = cse18_[2];
          const pops::Real cse33_ = cse17_[3];
          const pops::Real cse34_ = cse18_[3];
          const pops::Real cse35_ = (cse0_ - cse19_);
          const pops::Real cse36_ = (cse5_ - cse20_);
          const pops::Real cse37_ = (cse6_ - cse21_);
          const pops::Real cse38_ = (cse7_ - cse22_);
          const pops::Real cse39_ = (cse8_ - cse23_);
          const pops::Real cse40_ = (cse9_ - cse24_);
          const pops::Real cse41_ = (cse10_ - cse25_);
          const pops::Real cse42_ = (cse11_ - cse26_);
          const auto cse43_ = pops::detail::finite_linear_solve<8, 8>(Kokkos::Array<pops::Real, 64>{pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0)}, Kokkos::Array<pops::Real, 8>{cse35_, cse36_, cse37_, cse38_, cse39_, cse40_, cse41_, cse42_});
          const pops::Real cse44_ = cse43_[0];
          const pops::Real cse45_ = cse43_[1];
          const pops::Real cse46_ = cse43_[2];
          const pops::Real cse47_ = cse43_[3];
          const pops::Real cse48_ = cse43_[4];
          const pops::Real cse49_ = cse43_[5];
          const pops::Real cse50_ = cse43_[6];
          const pops::Real cse51_ = cse43_[7];
          const auto cse52_ = pops::detail::finite_linear_apply<4, 8>(Kokkos::Array<pops::Real, 32>{pops::Real(0.006794583660398504), pops::Real(0.010424006915294317), pops::Real(-0.006925697660970027), pops::Real(0.01767875889574026), pops::Real(-0.0015605289102391937), pops::Real(0.036329617623540096), pops::Real(-0.0010445570385972049), pops::Real(0.00668722364898641), pops::Real(0.01096509302686312), pops::Real(-0.019252642740859603), pops::Real(0.00021282547340161005), pops::Real(0.03480560965576028), pops::Real(-0.006179986822551416), pops::Real(-0.027616438828324336), pops::Real(0.01292289517518653), pops::Real(0.006338718276296419), pops::Real(-0.02071406828809953), pops::Real(0.010298054258974988), pops::Real(0.0005669446877556259), pops::Real(-0.020399003489401418), pops::Real(0.007551818461584454), pops::Real(0.0045037701942425455), pops::Real(0.005369684411221944), pops::Real(-0.009346963262518241), pops::Real(0.012251610678409656), pops::Real(0.021326361197090377), pops::Real(0.0052706020331702704), pops::Real(0.01003530207870926), pops::Real(0.02400053555547638), pops::Real(0.01988405485938884), pops::Real(0.002365577494322022), pops::Real(-0.010130522007765794)}, Kokkos::Array<pops::Real, 8>{cse44_, cse45_, cse46_, cse47_, cse48_, cse49_, cse50_, cse51_});
          const pops::Real cse53_ = cse52_[0];
          const pops::Real cse54_ = cse52_[1];
          const pops::Real cse55_ = cse52_[2];
          const pops::Real cse56_ = cse52_[3];
          const pops::Real cse57_ = (cse53_ + cse27_);
          const pops::Real cse58_ = (cse54_ + cse29_);
          const pops::Real cse59_ = (cse55_ + cse31_);
          const pops::Real cse60_ = (cse56_ + cse33_);
          const pops::Real cse61_ = (cse57_ - cse28_);
          const pops::Real cse62_ = (cse58_ - cse30_);
          const pops::Real cse63_ = (cse59_ - cse32_);
          const pops::Real cse64_ = (cse60_ - cse34_);
          if (!Kokkos::isfinite(cse0_) || !Kokkos::isfinite(cse1_) || !Kokkos::isfinite(cse2_) || !Kokkos::isfinite(cse3_) || !Kokkos::isfinite(cse4_) || !Kokkos::isfinite(cse5_) || !Kokkos::isfinite(cse6_) || !Kokkos::isfinite(cse7_) || !Kokkos::isfinite(cse8_) || !Kokkos::isfinite(cse9_) || !Kokkos::isfinite(cse10_) || !Kokkos::isfinite(cse11_) || !Kokkos::isfinite(cse12_) || !Kokkos::isfinite(cse13_) || !Kokkos::isfinite(cse14_) || !Kokkos::isfinite(cse15_) || !Kokkos::isfinite(cse19_) || !Kokkos::isfinite(cse20_) || !Kokkos::isfinite(cse21_) || !Kokkos::isfinite(cse22_) || !Kokkos::isfinite(cse23_) || !Kokkos::isfinite(cse24_) || !Kokkos::isfinite(cse25_) || !Kokkos::isfinite(cse26_) || !Kokkos::isfinite(cse27_) || !Kokkos::isfinite(cse28_) || !Kokkos::isfinite(cse29_) || !Kokkos::isfinite(cse30_) || !Kokkos::isfinite(cse31_) || !Kokkos::isfinite(cse32_) || !Kokkos::isfinite(cse33_) || !Kokkos::isfinite(cse34_) || !Kokkos::isfinite(cse35_) || !Kokkos::isfinite(cse36_) || !Kokkos::isfinite(cse37_) || !Kokkos::isfinite(cse38_) || !Kokkos::isfinite(cse39_) || !Kokkos::isfinite(cse40_) || !Kokkos::isfinite(cse41_) || !Kokkos::isfinite(cse42_) || !Kokkos::isfinite(cse44_) || !Kokkos::isfinite(cse45_) || !Kokkos::isfinite(cse46_) || !Kokkos::isfinite(cse47_) || !Kokkos::isfinite(cse48_) || !Kokkos::isfinite(cse49_) || !Kokkos::isfinite(cse50_) || !Kokkos::isfinite(cse51_) || !Kokkos::isfinite(cse53_) || !Kokkos::isfinite(cse54_) || !Kokkos::isfinite(cse55_) || !Kokkos::isfinite(cse56_) || !Kokkos::isfinite(cse57_) || !Kokkos::isfinite(cse58_) || !Kokkos::isfinite(cse59_) || !Kokkos::isfinite(cse60_) || !Kokkos::isfinite(cse61_) || !Kokkos::isfinite(cse62_) || !Kokkos::isfinite(cse63_) || !Kokkos::isfinite(cse64_)) {
            rout[0] = std::numeric_limits<pops::Real>::quiet_NaN();
            rout[1] = std::numeric_limits<pops::Real>::quiet_NaN();
            rout[2] = std::numeric_limits<pops::Real>::quiet_NaN();
            rout[3] = std::numeric_limits<pops::Real>::quiet_NaN();
            return;
          }
          rout[0] = cse61_;
          rout[1] = cse62_;
          rout[2] = cse63_;
          rout[3] = cse64_;
        };
        pops::PreparedLocalNonlinearControls controls_;
        controls_.absolute_tolerance = static_cast<pops::Real>(1e-13);
        controls_.relative_tolerance = static_cast<pops::Real>(0.0);
        controls_.step_tolerance = static_cast<pops::Real>(0.0);
        controls_.max_iterations = 20;
        controls_.max_evaluations = 0;
        controls_.finite_difference_step = static_cast<pops::Real>(1e-07);
        controls_.safeguard = pops::LocalSafeguardKind::kExactNewton;
        controls_.initial_step = static_cast<pops::Real>(1.0);
        controls_.max_backtracks = 12;
        controls_.minimum_step = static_cast<pops::Real>(0.000244140625);
        controls_.armijo = static_cast<pops::Real>(0.0001);
        const auto prepared_ = pops::prepare_local_nonlinear_problem<4>(residual_eval, pops::FiniteDifferenceLocalJacobian<4>{}, pops::AcceptAllLocalCandidates<4>{}, controls_);
        const pops::LocalNonlinearCellResult<4> solved_ = pops::solve_prepared_local_nonlinear(prepared_, G_);
        ci7_potentialA(index, 0) = solved_.value[0];
        ci7_potentialA(index, 1) = solved_.value[1];
        ci7_potentialA(index, 2) = solved_.value[2];
        ci7_potentialA(index, 3) = solved_.value[3];
        ci_status_7A(index, 0) = static_cast<pops::Real>(pops::local_nonlinear_status_code(solved_.status));
        ci_status_7A(index, 1) = static_cast<pops::Real>(solved_.iterations);
        ci_status_7A(index, 2) = static_cast<pops::Real>(solved_.evaluations);
        ci_status_7A(index, 3) = solved_.reference_residual_norm;
        ci_status_7A(index, 4) = solved_.residual_norm;
        ci_status_7A(index, 5) = solved_.step_norm;
        ci_status_7A(index, 6) = solved_.condition_evidence;
        ci_status_7A(index, 7) = static_cast<pops::Real>(solved_.safeguard_steps);
        ci_status_7A(index, 10) = static_cast<pops::Real>(pops::local_nonlinear_status_priority(solved_.status));
        if (!solved_.solved()) {
          ci_status_7A(index, 8) = static_cast<pops::Real>(solved_.failing_component);
          ci_status_7A(index, 9) = pops::Real(1);
        } else {
          ci_status_7A(index, 8) = pops::Real(0);
          ci_status_7A(index, 9) = pops::Real(0);
        }
      });
    }
    }
    const pops::ExecutionLane& ci_report_7_lane = ctx.prepared_execution_lane();
    const int ci_report_7_priority = static_cast<int>(pops::all_reduce_max(pops::reduce_max_local(ci_status_7, 10), ci_report_7_lane));
    const int ci_report_7_status = pops::local_nonlinear_status_code(pops::local_nonlinear_status_from_priority(ci_report_7_priority));
    const int ci_report_7_iterations = static_cast<int>(pops::all_reduce_max(pops::reduce_max_local(ci_status_7, 1), ci_report_7_lane));
    const int ci_report_7_evaluations = static_cast<int>(pops::all_reduce_max(pops::reduce_max_local(ci_status_7, 2), ci_report_7_lane));
    const pops::Real ci_report_7_reference_residual = pops::all_reduce_max(pops::reduce_max_local(ci_status_7, 3), ci_report_7_lane);
    const pops::Real ci_report_7_residual = pops::all_reduce_max(pops::reduce_max_local(ci_status_7, 4), ci_report_7_lane);
    const pops::Real ci_report_7_step = pops::all_reduce_max(pops::reduce_max_local(ci_status_7, 5), ci_report_7_lane);
    const pops::Real ci_report_7_condition = pops::all_reduce_max(pops::reduce_max_local(ci_status_7, 6), ci_report_7_lane);
    const int ci_report_7_safeguard_steps = static_cast<int>(pops::all_reduce_max(pops::reduce_max_local(ci_status_7, 7), ci_report_7_lane));
    const pops::Real ci_report_7_failed_count = pops::all_reduce_sum(pops::reduce_sum_local(ci_status_7, 9), ci_report_7_lane);
    pops::LocalNonlinearFailureLocation<pops::kNativeDimension> ci_report_7_failure_location;
    if (ci_report_7_failed_count > pops::Real(0))
      ci_report_7_failure_location = pops::collective_first_local_nonlinear_failure(ci_status_7, ci_report_7_priority, 10, 8, ci_report_7_lane);
    if (ci_report_7_failed_count > pops::Real(0) && (!ci_report_7_failure_location.found || ci_report_7_failure_location.priority != ci_report_7_priority))
      throw std::runtime_error("local nonlinear collective status/location precedence mismatch");
    const pops::SolveFailureLocation ci_report_7_reported_failure = ci_report_7_failure_location.found ? pops::SolveFailureLocation::from<pops::kNativeDimension>(ci_report_7_failure_location.index, ci_report_7_failure_location.component) : pops::SolveFailureLocation{};
    pops::SolveReport ci_report_7 = pops::local_nonlinear_solve_report(ci_report_7_status, ci_report_7_iterations, ci_report_7_evaluations, ci_report_7_reference_residual, ci_report_7_residual, ci_report_7_step, ci_report_7_condition, ci_report_7_safeguard_steps, ci_report_7_reported_failure, pops::SolveAction::kFailRun);
    pops::SolveOutcome ci_outcome_7 = pops::SolveOutcome::collective_lane(std::move(ci_report_7), ci_report_7_lane);
    if (!ci_outcome_7.report().solved_value_available()) {
      const pops::SolveReport ci_outcome_7_report = ci_outcome_7.consume(pops::SolveConsumption::kFailRun);
      throw std::runtime_error(std::string("coupled_implicit failed: ") + ci_outcome_7_report.status_name() + " action=" + ci_outcome_7_report.action_name() + " reason=" + ci_outcome_7_report.reason);
    }
    (void)ci_outcome_7.consume(pops::SolveConsumption::kAccept);
    ctx.profile_record("node:local_product", _pt7);
    const auto _pt10 = std::chrono::steady_clock::now();  // ProfileScope "node:reconstructed_velocity"
    pops::MultiFab<pops::kNativeDimension>& u10 = ctx.scratch_state(10, 0, u0);
    pops::MultiFab<pops::kNativeDimension>& expression_status_10 = ctx.scalar_scratch(10, 1, u0, 1, 0);
    {
    long finite_layout_error_ = 0;
    finite_layout_error_ |= (u0.layout() != u10.layout() || u0.distribution() != u10.distribution() || u0.local_rank() != u10.local_rank());
    finite_layout_error_ |= (ci7_potential.layout() != u10.layout() || ci7_potential.distribution() != u10.distribution() || ci7_potential.local_rank() != u10.local_rank());
    if (pops::all_reduce_max(finite_layout_error_, ctx.prepared_execution_lane()))
      throw std::runtime_error("finite materialization requires co-located layouts, distributions and ranks");
    const auto* expression_active_10 = ctx.pointwise_active_mask(0, u10);
    for (int li = 0; li < u10.local_size(); ++li) {
      const pops::FieldView<pops::Real, pops::kNativeDimension> outA = u10.fab(li).view();
      const pops::FieldView<const pops::Real, pops::kNativeDimension> u0A = std::as_const(u0).fab(li).view();
      const auto ci7_potentialA = std::as_const(ci7_potential).fab(li).view();
      const auto expression_status_ = expression_status_10.fab(li).view();
      const bool expression_has_mask_ = expression_active_10 != nullptr;
      const auto expression_mask_ = expression_has_mask_ ? std::as_const(*expression_active_10).fab(li).view() : pops::FieldView<const pops::Real, pops::kNativeDimension>{};
      pops::for_each_cell(u10.box(li), [=] POPS_HD(const pops::CellIndex<pops::kNativeDimension>& index) {
        if (expression_has_mask_ && !(expression_mask_(index, 0) >= pops::Real(0.5))) {
          outA(index, 0) = u0A(index, 0);
          outA(index, 1) = u0A(index, 1);
          outA(index, 2) = u0A(index, 2);
          outA(index, 3) = u0A(index, 3);
          outA(index, 4) = u0A(index, 4);
          outA(index, 5) = u0A(index, 5);
          outA(index, 6) = u0A(index, 6);
          outA(index, 7) = u0A(index, 7);
          expression_status_(index, 0) = pops::Real(0);
          return;
        }
        const pops::Real cse0_ = u0A(index, 0);
        const pops::Real cse1_ = ci7_potentialA(index, 0);
        const pops::Real cse2_ = ci7_potentialA(index, 1);
        const pops::Real cse3_ = ci7_potentialA(index, 2);
        const pops::Real cse4_ = ci7_potentialA(index, 3);
        const pops::Real cse5_ = u0A(index, 1);
        const pops::Real cse6_ = u0A(index, 2);
        const pops::Real cse7_ = u0A(index, 3);
        const pops::Real cse8_ = u0A(index, 4);
        const pops::Real cse9_ = u0A(index, 5);
        const pops::Real cse10_ = u0A(index, 6);
        const pops::Real cse11_ = u0A(index, 7);
        const auto cse12_ = pops::detail::finite_linear_apply<8, 4>(Kokkos::Array<pops::Real, 32>{pops::Real(-0.013589167320797008), pops::Real(-0.02193018605372624), pops::Real(0.04142813657619906), pops::Real(-0.024503221356819312), pops::Real(-0.018952739845989667), pops::Real(0.03500480498338109), pops::Real(-0.01872373501631816), pops::Real(-0.038775202176527954), pops::Real(0.015390439246600059), pops::Real(-0.00047294549644802235), pops::Real(-0.0012598770839013908), pops::Real(-0.0117124489626006), pops::Real(-0.0294645981595671), pops::Real(-0.058009349426267134), pops::Real(0.03399833914900236), pops::Real(-0.016725503464515436), pops::Real(0.0031210578204783875), pops::Real(0.012359973645102832), pops::Real(-0.015103636923168908), pops::Real(-0.04800107111095276), pops::Real(-0.06605385022461835), pops::Real(0.0502117069605897), pops::Real(-0.008188673080440991), pops::Real(-0.036152827017070614), pops::Real(0.002321237863549344), pops::Real(-0.028717544833747846), pops::Real(-0.011932632024937653), pops::Real(-0.00525683887627116), pops::Real(-0.011145372748310683), pops::Real(-0.010564530460494033), pops::Real(0.01557827210419707), pops::Real(0.016884203346276324)}, Kokkos::Array<pops::Real, 4>{cse1_, cse2_, cse3_, cse4_});
        const pops::Real cse13_ = cse12_[0];
        const pops::Real cse14_ = cse12_[1];
        const pops::Real cse15_ = cse12_[2];
        const pops::Real cse16_ = cse12_[3];
        const pops::Real cse17_ = cse12_[4];
        const pops::Real cse18_ = cse12_[5];
        const pops::Real cse19_ = cse12_[6];
        const pops::Real cse20_ = cse12_[7];
        const pops::Real cse21_ = (cse0_ - cse13_);
        const pops::Real cse22_ = (cse5_ - cse14_);
        const pops::Real cse23_ = (cse6_ - cse15_);
        const pops::Real cse24_ = (cse7_ - cse16_);
        const pops::Real cse25_ = (cse8_ - cse17_);
        const pops::Real cse26_ = (cse9_ - cse18_);
        const pops::Real cse27_ = (cse10_ - cse19_);
        const pops::Real cse28_ = (cse11_ - cse20_);
        const auto cse29_ = pops::detail::finite_linear_solve<8, 8>(Kokkos::Array<pops::Real, 64>{pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0)}, Kokkos::Array<pops::Real, 8>{cse21_, cse22_, cse23_, cse24_, cse25_, cse26_, cse27_, cse28_});
        const pops::Real cse30_ = cse29_[0];
        const pops::Real cse31_ = cse29_[1];
        const pops::Real cse32_ = cse29_[2];
        const pops::Real cse33_ = cse29_[3];
        const pops::Real cse34_ = cse29_[4];
        const pops::Real cse35_ = cse29_[5];
        const pops::Real cse36_ = cse29_[6];
        const pops::Real cse37_ = cse29_[7];
        expression_status_(index, 0) = (!Kokkos::isfinite(cse0_) || !Kokkos::isfinite(cse1_) || !Kokkos::isfinite(cse2_) || !Kokkos::isfinite(cse3_) || !Kokkos::isfinite(cse4_) || !Kokkos::isfinite(cse5_) || !Kokkos::isfinite(cse6_) || !Kokkos::isfinite(cse7_) || !Kokkos::isfinite(cse8_) || !Kokkos::isfinite(cse9_) || !Kokkos::isfinite(cse10_) || !Kokkos::isfinite(cse11_) || !Kokkos::isfinite(cse13_) || !Kokkos::isfinite(cse14_) || !Kokkos::isfinite(cse15_) || !Kokkos::isfinite(cse16_) || !Kokkos::isfinite(cse17_) || !Kokkos::isfinite(cse18_) || !Kokkos::isfinite(cse19_) || !Kokkos::isfinite(cse20_) || !Kokkos::isfinite(cse21_) || !Kokkos::isfinite(cse22_) || !Kokkos::isfinite(cse23_) || !Kokkos::isfinite(cse24_) || !Kokkos::isfinite(cse25_) || !Kokkos::isfinite(cse26_) || !Kokkos::isfinite(cse27_) || !Kokkos::isfinite(cse28_) || !Kokkos::isfinite(cse30_) || !Kokkos::isfinite(cse31_) || !Kokkos::isfinite(cse32_) || !Kokkos::isfinite(cse33_) || !Kokkos::isfinite(cse34_) || !Kokkos::isfinite(cse35_) || !Kokkos::isfinite(cse36_) || !Kokkos::isfinite(cse37_)) ? pops::Real(1) : pops::Real(0);
        outA(index, 0) = cse30_;
        outA(index, 1) = cse31_;
        outA(index, 2) = cse32_;
        outA(index, 3) = cse33_;
        outA(index, 4) = cse34_;
        outA(index, 5) = cse35_;
        outA(index, 6) = cse36_;
        outA(index, 7) = cse37_;
      });
    }
    }
    if (ctx.pointwise_status_max(0, expression_status_10, expression_active_10, ctx.prepared_execution_lane()) != pops::Real(0)) {
      throw pops::runtime::program::StepAttemptRejected(pops::SolveStatus::kInvalidEvaluation, "pointwise_expression", "non-finite scientific expression input or intermediate");
    }
    ctx.profile_record("node:reconstructed_velocity", _pt10);
    const auto _pt11 = std::chrono::steady_clock::now();  // ProfileScope "node:original_velocity_residual"
    pops::MultiFab<pops::kNativeDimension>& u11 = ctx.scratch_state(11, 0, u10);
    pops::MultiFab<pops::kNativeDimension>& expression_status_11 = ctx.scalar_scratch(11, 1, u10, 1, 0);
    {
    long finite_layout_error_ = 0;
    finite_layout_error_ |= (u10.layout() != u11.layout() || u10.distribution() != u11.distribution() || u10.local_rank() != u11.local_rank());
    finite_layout_error_ |= (ci7_potential.layout() != u11.layout() || ci7_potential.distribution() != u11.distribution() || ci7_potential.local_rank() != u11.local_rank());
    finite_layout_error_ |= (u0.layout() != u11.layout() || u0.distribution() != u11.distribution() || u0.local_rank() != u11.local_rank());
    if (pops::all_reduce_max(finite_layout_error_, ctx.prepared_execution_lane()))
      throw std::runtime_error("finite materialization requires co-located layouts, distributions and ranks");
    const auto* expression_active_11 = ctx.pointwise_active_mask(0, u11);
    for (int li = 0; li < u11.local_size(); ++li) {
      const pops::FieldView<pops::Real, pops::kNativeDimension> outA = u11.fab(li).view();
      const pops::FieldView<const pops::Real, pops::kNativeDimension> u10A = std::as_const(u10).fab(li).view();
      const auto ci7_potentialA = std::as_const(ci7_potential).fab(li).view();
      const auto u0A = std::as_const(u0).fab(li).view();
      const auto expression_status_ = expression_status_11.fab(li).view();
      const bool expression_has_mask_ = expression_active_11 != nullptr;
      const auto expression_mask_ = expression_has_mask_ ? std::as_const(*expression_active_11).fab(li).view() : pops::FieldView<const pops::Real, pops::kNativeDimension>{};
      pops::for_each_cell(u11.box(li), [=] POPS_HD(const pops::CellIndex<pops::kNativeDimension>& index) {
        if (expression_has_mask_ && !(expression_mask_(index, 0) >= pops::Real(0.5))) {
          outA(index, 0) = u10A(index, 0);
          outA(index, 1) = u10A(index, 1);
          outA(index, 2) = u10A(index, 2);
          outA(index, 3) = u10A(index, 3);
          outA(index, 4) = u10A(index, 4);
          outA(index, 5) = u10A(index, 5);
          outA(index, 6) = u10A(index, 6);
          outA(index, 7) = u10A(index, 7);
          expression_status_(index, 0) = pops::Real(0);
          return;
        }
        const pops::Real cse0_ = u10A(index, 0);
        const pops::Real cse1_ = u10A(index, 1);
        const pops::Real cse2_ = u10A(index, 2);
        const pops::Real cse3_ = u10A(index, 3);
        const pops::Real cse4_ = u10A(index, 4);
        const pops::Real cse5_ = u10A(index, 5);
        const pops::Real cse6_ = u10A(index, 6);
        const pops::Real cse7_ = u10A(index, 7);
        const pops::Real cse8_ = ci7_potentialA(index, 0);
        const pops::Real cse9_ = ci7_potentialA(index, 1);
        const pops::Real cse10_ = ci7_potentialA(index, 2);
        const pops::Real cse11_ = ci7_potentialA(index, 3);
        const pops::Real cse12_ = u0A(index, 0);
        const pops::Real cse13_ = u0A(index, 1);
        const pops::Real cse14_ = u0A(index, 2);
        const pops::Real cse15_ = u0A(index, 3);
        const pops::Real cse16_ = u0A(index, 4);
        const pops::Real cse17_ = u0A(index, 5);
        const pops::Real cse18_ = u0A(index, 6);
        const pops::Real cse19_ = u0A(index, 7);
        const auto cse20_ = pops::detail::finite_linear_apply<8, 4>(Kokkos::Array<pops::Real, 32>{pops::Real(-0.013589167320797008), pops::Real(-0.02193018605372624), pops::Real(0.04142813657619906), pops::Real(-0.024503221356819312), pops::Real(-0.018952739845989667), pops::Real(0.03500480498338109), pops::Real(-0.01872373501631816), pops::Real(-0.038775202176527954), pops::Real(0.015390439246600059), pops::Real(-0.00047294549644802235), pops::Real(-0.0012598770839013908), pops::Real(-0.0117124489626006), pops::Real(-0.0294645981595671), pops::Real(-0.058009349426267134), pops::Real(0.03399833914900236), pops::Real(-0.016725503464515436), pops::Real(0.0031210578204783875), pops::Real(0.012359973645102832), pops::Real(-0.015103636923168908), pops::Real(-0.04800107111095276), pops::Real(-0.06605385022461835), pops::Real(0.0502117069605897), pops::Real(-0.008188673080440991), pops::Real(-0.036152827017070614), pops::Real(0.002321237863549344), pops::Real(-0.028717544833747846), pops::Real(-0.011932632024937653), pops::Real(-0.00525683887627116), pops::Real(-0.011145372748310683), pops::Real(-0.010564530460494033), pops::Real(0.01557827210419707), pops::Real(0.016884203346276324)}, Kokkos::Array<pops::Real, 4>{cse8_, cse9_, cse10_, cse11_});
        const pops::Real cse21_ = cse20_[0];
        const pops::Real cse22_ = cse20_[1];
        const pops::Real cse23_ = cse20_[2];
        const pops::Real cse24_ = cse20_[3];
        const pops::Real cse25_ = cse20_[4];
        const pops::Real cse26_ = cse20_[5];
        const pops::Real cse27_ = cse20_[6];
        const pops::Real cse28_ = cse20_[7];
        const auto cse29_ = pops::detail::finite_linear_apply<8, 8>(Kokkos::Array<pops::Real, 64>{pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(-0.03), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(0.03), pops::Real(0.0), pops::Real(0.0), pops::Real(0.0), pops::Real(1.0)}, Kokkos::Array<pops::Real, 8>{cse0_, cse1_, cse2_, cse3_, cse4_, cse5_, cse6_, cse7_});
        const pops::Real cse30_ = cse29_[0];
        const pops::Real cse31_ = cse29_[1];
        const pops::Real cse32_ = cse29_[2];
        const pops::Real cse33_ = cse29_[3];
        const pops::Real cse34_ = cse29_[4];
        const pops::Real cse35_ = cse29_[5];
        const pops::Real cse36_ = cse29_[6];
        const pops::Real cse37_ = cse29_[7];
        const pops::Real cse38_ = (cse30_ + cse21_);
        const pops::Real cse39_ = (cse31_ + cse22_);
        const pops::Real cse40_ = (cse32_ + cse23_);
        const pops::Real cse41_ = (cse33_ + cse24_);
        const pops::Real cse42_ = (cse34_ + cse25_);
        const pops::Real cse43_ = (cse35_ + cse26_);
        const pops::Real cse44_ = (cse36_ + cse27_);
        const pops::Real cse45_ = (cse37_ + cse28_);
        const pops::Real cse46_ = (cse38_ - cse12_);
        const pops::Real cse47_ = (cse39_ - cse13_);
        const pops::Real cse48_ = (cse40_ - cse14_);
        const pops::Real cse49_ = (cse41_ - cse15_);
        const pops::Real cse50_ = (cse42_ - cse16_);
        const pops::Real cse51_ = (cse43_ - cse17_);
        const pops::Real cse52_ = (cse44_ - cse18_);
        const pops::Real cse53_ = (cse45_ - cse19_);
        expression_status_(index, 0) = (!Kokkos::isfinite(cse0_) || !Kokkos::isfinite(cse1_) || !Kokkos::isfinite(cse2_) || !Kokkos::isfinite(cse3_) || !Kokkos::isfinite(cse4_) || !Kokkos::isfinite(cse5_) || !Kokkos::isfinite(cse6_) || !Kokkos::isfinite(cse7_) || !Kokkos::isfinite(cse8_) || !Kokkos::isfinite(cse9_) || !Kokkos::isfinite(cse10_) || !Kokkos::isfinite(cse11_) || !Kokkos::isfinite(cse12_) || !Kokkos::isfinite(cse13_) || !Kokkos::isfinite(cse14_) || !Kokkos::isfinite(cse15_) || !Kokkos::isfinite(cse16_) || !Kokkos::isfinite(cse17_) || !Kokkos::isfinite(cse18_) || !Kokkos::isfinite(cse19_) || !Kokkos::isfinite(cse21_) || !Kokkos::isfinite(cse22_) || !Kokkos::isfinite(cse23_) || !Kokkos::isfinite(cse24_) || !Kokkos::isfinite(cse25_) || !Kokkos::isfinite(cse26_) || !Kokkos::isfinite(cse27_) || !Kokkos::isfinite(cse28_) || !Kokkos::isfinite(cse30_) || !Kokkos::isfinite(cse31_) || !Kokkos::isfinite(cse32_) || !Kokkos::isfinite(cse33_) || !Kokkos::isfinite(cse34_) || !Kokkos::isfinite(cse35_) || !Kokkos::isfinite(cse36_) || !Kokkos::isfinite(cse37_) || !Kokkos::isfinite(cse38_) || !Kokkos::isfinite(cse39_) || !Kokkos::isfinite(cse40_) || !Kokkos::isfinite(cse41_) || !Kokkos::isfinite(cse42_) || !Kokkos::isfinite(cse43_) || !Kokkos::isfinite(cse44_) || !Kokkos::isfinite(cse45_) || !Kokkos::isfinite(cse46_) || !Kokkos::isfinite(cse47_) || !Kokkos::isfinite(cse48_) || !Kokkos::isfinite(cse49_) || !Kokkos::isfinite(cse50_) || !Kokkos::isfinite(cse51_) || !Kokkos::isfinite(cse52_) || !Kokkos::isfinite(cse53_)) ? pops::Real(1) : pops::Real(0);
        outA(index, 0) = cse46_;
        outA(index, 1) = cse47_;
        outA(index, 2) = cse48_;
        outA(index, 3) = cse49_;
        outA(index, 4) = cse50_;
        outA(index, 5) = cse51_;
        outA(index, 6) = cse52_;
        outA(index, 7) = cse53_;
      });
    }
    }
    if (ctx.pointwise_status_max(0, expression_status_11, expression_active_11, ctx.prepared_execution_lane()) != pops::Real(0)) {
      throw pops::runtime::program::StepAttemptRejected(pops::SolveStatus::kInvalidEvaluation, "pointwise_expression", "non-finite scientific expression input or intermediate");
    }
    ctx.profile_record("node:original_velocity_residual", _pt11);
    const auto _pt12 = std::chrono::steady_clock::now();  // ProfileScope "node:original_potential_residual"
    pops::MultiFab<pops::kNativeDimension>& u12 = ctx.scratch_state(12, 0, u10);
    pops::MultiFab<pops::kNativeDimension>& expression_status_12 = ctx.scalar_scratch(12, 1, u10, 1, 0);
    {
    long finite_layout_error_ = 0;
    finite_layout_error_ |= (u10.layout() != u12.layout() || u10.distribution() != u12.distribution() || u10.local_rank() != u12.local_rank());
    finite_layout_error_ |= (ci7_potential.layout() != u12.layout() || ci7_potential.distribution() != u12.distribution() || ci7_potential.local_rank() != u12.local_rank());
    finite_layout_error_ |= (u2.layout() != u12.layout() || u2.distribution() != u12.distribution() || u2.local_rank() != u12.local_rank());
    if (pops::all_reduce_max(finite_layout_error_, ctx.prepared_execution_lane()))
      throw std::runtime_error("finite materialization requires co-located layouts, distributions and ranks");
    const auto* expression_active_12 = ctx.pointwise_active_mask(1, u12);
    for (int li = 0; li < u12.local_size(); ++li) {
      const pops::FieldView<pops::Real, pops::kNativeDimension> outA = u12.fab(li).view();
      const pops::FieldView<const pops::Real, pops::kNativeDimension> ci7_potentialA = std::as_const(ci7_potential).fab(li).view();
      const auto u10A = std::as_const(u10).fab(li).view();
      const auto u2A = std::as_const(u2).fab(li).view();
      const auto expression_status_ = expression_status_12.fab(li).view();
      const bool expression_has_mask_ = expression_active_12 != nullptr;
      const auto expression_mask_ = expression_has_mask_ ? std::as_const(*expression_active_12).fab(li).view() : pops::FieldView<const pops::Real, pops::kNativeDimension>{};
      pops::for_each_cell(u12.box(li), [=] POPS_HD(const pops::CellIndex<pops::kNativeDimension>& index) {
        if (expression_has_mask_ && !(expression_mask_(index, 0) >= pops::Real(0.5))) {
          outA(index, 0) = ci7_potentialA(index, 0);
          outA(index, 1) = ci7_potentialA(index, 1);
          outA(index, 2) = ci7_potentialA(index, 2);
          outA(index, 3) = ci7_potentialA(index, 3);
          expression_status_(index, 0) = pops::Real(0);
          return;
        }
        const pops::Real cse0_ = u10A(index, 0);
        const pops::Real cse1_ = u10A(index, 1);
        const pops::Real cse2_ = u10A(index, 2);
        const pops::Real cse3_ = u10A(index, 3);
        const pops::Real cse4_ = u10A(index, 4);
        const pops::Real cse5_ = u10A(index, 5);
        const pops::Real cse6_ = u10A(index, 6);
        const pops::Real cse7_ = u10A(index, 7);
        const pops::Real cse8_ = ci7_potentialA(index, 0);
        const pops::Real cse9_ = ci7_potentialA(index, 1);
        const pops::Real cse10_ = ci7_potentialA(index, 2);
        const pops::Real cse11_ = ci7_potentialA(index, 3);
        const pops::Real cse12_ = u2A(index, 0);
        const pops::Real cse13_ = u2A(index, 1);
        const pops::Real cse14_ = u2A(index, 2);
        const pops::Real cse15_ = u2A(index, 3);
        const auto cse16_ = pops::detail::finite_linear_apply<4, 4>(Kokkos::Array<pops::Real, 16>{pops::Real(6.834843990426089), pops::Real(-2.1005507381677084), pops::Real(-1.0409059215957308), pops::Real(3.798068208843949), pops::Real(-2.1005507381677084), pops::Real(9.646520977899726), pops::Real(-4.394802400698765), pops::Real(-2.5335339628924682), pops::Real(-1.0409059215957308), pops::Real(-4.394802400698765), pops::Real(4.338430658016501), pops::Real(0.5597775399173847), pops::Real(3.798068208843949), pops::Real(-2.5335339628924682), pops::Real(0.5597775399173847), pops::Real(7.1607649936326725)}, Kokkos::Array<pops::Real, 4>{cse8_, cse9_, cse10_, cse11_});
        const auto cse17_ = pops::detail::finite_linear_apply<4, 4>(Kokkos::Array<pops::Real, 16>{pops::Real(6.834843990426089), pops::Real(-2.1005507381677084), pops::Real(-1.0409059215957308), pops::Real(3.798068208843949), pops::Real(-2.1005507381677084), pops::Real(9.646520977899726), pops::Real(-4.394802400698765), pops::Real(-2.5335339628924682), pops::Real(-1.0409059215957308), pops::Real(-4.394802400698765), pops::Real(4.338430658016501), pops::Real(0.5597775399173847), pops::Real(3.798068208843949), pops::Real(-2.5335339628924682), pops::Real(0.5597775399173847), pops::Real(7.1607649936326725)}, Kokkos::Array<pops::Real, 4>{cse12_, cse13_, cse14_, cse15_});
        const pops::Real cse18_ = cse16_[0];
        const pops::Real cse19_ = cse17_[0];
        const pops::Real cse20_ = cse16_[1];
        const pops::Real cse21_ = cse17_[1];
        const pops::Real cse22_ = cse16_[2];
        const pops::Real cse23_ = cse17_[2];
        const pops::Real cse24_ = cse16_[3];
        const pops::Real cse25_ = cse17_[3];
        const auto cse26_ = pops::detail::finite_linear_apply<4, 8>(Kokkos::Array<pops::Real, 32>{pops::Real(0.006794583660398504), pops::Real(0.010424006915294317), pops::Real(-0.006925697660970027), pops::Real(0.01767875889574026), pops::Real(-0.0015605289102391937), pops::Real(0.036329617623540096), pops::Real(-0.0010445570385972049), pops::Real(0.00668722364898641), pops::Real(0.01096509302686312), pops::Real(-0.019252642740859603), pops::Real(0.00021282547340161005), pops::Real(0.03480560965576028), pops::Real(-0.006179986822551416), pops::Real(-0.027616438828324336), pops::Real(0.01292289517518653), pops::Real(0.006338718276296419), pops::Real(-0.02071406828809953), pops::Real(0.010298054258974988), pops::Real(0.0005669446877556259), pops::Real(-0.020399003489401418), pops::Real(0.007551818461584454), pops::Real(0.0045037701942425455), pops::Real(0.005369684411221944), pops::Real(-0.009346963262518241), pops::Real(0.012251610678409656), pops::Real(0.021326361197090377), pops::Real(0.0052706020331702704), pops::Real(0.01003530207870926), pops::Real(0.02400053555547638), pops::Real(0.01988405485938884), pops::Real(0.002365577494322022), pops::Real(-0.010130522007765794)}, Kokkos::Array<pops::Real, 8>{cse0_, cse1_, cse2_, cse3_, cse4_, cse5_, cse6_, cse7_});
        const pops::Real cse27_ = cse26_[0];
        const pops::Real cse28_ = cse26_[1];
        const pops::Real cse29_ = cse26_[2];
        const pops::Real cse30_ = cse26_[3];
        const pops::Real cse31_ = (cse27_ + cse18_);
        const pops::Real cse32_ = (cse28_ + cse20_);
        const pops::Real cse33_ = (cse29_ + cse22_);
        const pops::Real cse34_ = (cse30_ + cse24_);
        const pops::Real cse35_ = (cse31_ - cse19_);
        const pops::Real cse36_ = (cse32_ - cse21_);
        const pops::Real cse37_ = (cse33_ - cse23_);
        const pops::Real cse38_ = (cse34_ - cse25_);
        expression_status_(index, 0) = (!Kokkos::isfinite(cse0_) || !Kokkos::isfinite(cse1_) || !Kokkos::isfinite(cse2_) || !Kokkos::isfinite(cse3_) || !Kokkos::isfinite(cse4_) || !Kokkos::isfinite(cse5_) || !Kokkos::isfinite(cse6_) || !Kokkos::isfinite(cse7_) || !Kokkos::isfinite(cse8_) || !Kokkos::isfinite(cse9_) || !Kokkos::isfinite(cse10_) || !Kokkos::isfinite(cse11_) || !Kokkos::isfinite(cse12_) || !Kokkos::isfinite(cse13_) || !Kokkos::isfinite(cse14_) || !Kokkos::isfinite(cse15_) || !Kokkos::isfinite(cse18_) || !Kokkos::isfinite(cse19_) || !Kokkos::isfinite(cse20_) || !Kokkos::isfinite(cse21_) || !Kokkos::isfinite(cse22_) || !Kokkos::isfinite(cse23_) || !Kokkos::isfinite(cse24_) || !Kokkos::isfinite(cse25_) || !Kokkos::isfinite(cse27_) || !Kokkos::isfinite(cse28_) || !Kokkos::isfinite(cse29_) || !Kokkos::isfinite(cse30_) || !Kokkos::isfinite(cse31_) || !Kokkos::isfinite(cse32_) || !Kokkos::isfinite(cse33_) || !Kokkos::isfinite(cse34_) || !Kokkos::isfinite(cse35_) || !Kokkos::isfinite(cse36_) || !Kokkos::isfinite(cse37_) || !Kokkos::isfinite(cse38_)) ? pops::Real(1) : pops::Real(0);
        outA(index, 0) = cse35_;
        outA(index, 1) = cse36_;
        outA(index, 2) = cse37_;
        outA(index, 3) = cse38_;
      });
    }
    }
    if (ctx.pointwise_status_max(1, expression_status_12, expression_active_12, ctx.prepared_execution_lane()) != pops::Real(0)) {
      throw pops::runtime::program::StepAttemptRejected(pops::SolveStatus::kInvalidEvaluation, "pointwise_expression", "non-finite scientific expression input or intermediate");
    }
    ctx.profile_record("node:original_potential_residual", _pt12);
    const auto _pt13 = std::chrono::steady_clock::now();  // ProfileScope "node:reduce13"
    const pops::Real s13 = ctx.norm_inf(0, u11);
    ctx.profile_record("node:reduce13", _pt13);
    const auto _pt15 = std::chrono::steady_clock::now();  // ProfileScope "node:reduce15"
    const pops::Real s15 = ctx.norm_inf(1, u12);
    ctx.profile_record("node:reduce15", _pt15);
    const auto _pt17 = std::chrono::steady_clock::now();  // ProfileScope "node:reconstructed_velocity"
    if (!((s13 < 1e-11))) {
      throw std::runtime_error("acceptance guard 'velocity_original_velocity' failed");
    }
    ctx.profile_record("node:reconstructed_velocity", _pt17);
    const auto _pt18 = std::chrono::steady_clock::now();  // ProfileScope "node:reconstructed_velocity"
    if (!((s15 < 1e-11))) {
      throw std::runtime_error("acceptance guard 'velocity_original_potential' failed");
    }
    ctx.profile_record("node:reconstructed_velocity", _pt18);
    const auto _pt19 = std::chrono::steady_clock::now();  // ProfileScope "node:local_product_potential"
    if (!((s13 < 1e-11))) {
      throw std::runtime_error("acceptance guard 'potential_original_velocity' failed");
    }
    ctx.profile_record("node:local_product_potential", _pt19);
    const auto _pt20 = std::chrono::steady_clock::now();  // ProfileScope "node:local_product_potential"
    if (!((s15 < 1e-11))) {
      throw std::runtime_error("acceptance guard 'potential_original_potential' failed");
    }
    ctx.profile_record("node:local_product_potential", _pt20);
    ctx.commit_many({{&u0, &u10}, {&u2, &ci7_potential}});
  });
}



// OPTIONAL dt bound (spec s18 / ADC-417). pops_program_has_dt_bound() is true iff the Program set one.
// The target-qualified entry receives the runtime facade, obtains the shared execution provider, and
// returns the lowered scalar bound (min'd into native CFL). With no bound it returns +inf (unreached).
extern "C" bool pops_program_has_dt_bound() { return false; }
extern "C" pops::Real pops_program_dt_bound(pops::System<pops::kNativeDimension>* sys, pops::Real cfl) {
  auto ctx = pops::runtime::program::make_program_execution_view(sys);
  (void)ctx; (void)cfl;
    return std::numeric_limits<pops::Real>::infinity();
}

