"""TM-04 Larmor / magnetized oscillator: d/dt (ux, uy) = A (ux, uy).

A = ((0, ωc), (-ωc, 0)). Closed form: rotation matrix by θ = ωc t.

    R(θ) = ((cos θ, sin θ), (-sin θ, cos θ))

Canonical ωc = 1, u0 = (1, 0). Does not import pops or read PoPS output.
"""
from __future__ import annotations

import numpy as np

OMEGA_C = 1.0
U0 = (1.0, 0.0)
DT = 0.25


def cyclotron_matrix(*, omega_c: float = OMEGA_C) -> np.ndarray:
    """Return the 2×2 generator ((0, ωc), (-ωc, 0))."""
    rate = float(omega_c)
    return np.array(((0.0, rate), (-rate, 0.0)), dtype=np.float64)


def rotation_matrix(theta) -> np.ndarray:
    """Return the clockwise rotation R(θ) generated by the cyclotron matrix."""
    angle = float(theta)
    cosine = np.cos(angle)
    sine = np.sin(angle)
    return np.array(((cosine, sine), (-sine, cosine)), dtype=np.float64)


def speed(u) -> float:
    """Return the Euclidean speed |u|."""
    return float(np.linalg.norm(np.asarray(u, dtype=np.float64)))


def exact_advance(u, t, *, omega_c: float = OMEGA_C) -> np.ndarray:
    """Apply the rotation matrix by θ = ωc t."""
    return rotation_matrix(float(omega_c) * float(t)) @ np.asarray(u, dtype=np.float64)
