"""Type-only contract for the AMR runtime coupler mixins (ADC-628, static analysis only).

Companion to :mod:`pops.runtime._system_contract`. The concrete
:class:`pops.runtime._amr_system.AmrSystem` composes the ``_amr_system_*`` mixins; each reads the
native facade ``self._s``, a few instance attributes (``self._L`` / ``self._Ly`` /
``self._xlo`` / ``self._ylo`` /
``self._regrid_every`` /
``self._aux_field_index`` / typed step-transaction state) and sibling methods defined across the
other AMR mixins and the concrete ``AmrSystem`` body. Declared once here as a ``TYPE_CHECKING``-only
base; at runtime it collapses to ``object`` (never imported, instantiated or introspected outside a
type checker), so the class layout, the MRO and every runtime behaviour are unchanged. The bodies
are ``...`` stubs: they describe shapes, never behaviour.
"""
from __future__ import annotations

from typing import Any


class _AmrSystem:
    """The :class:`AmrSystem` instance surface the ``_amr_system_*`` mixins share."""

    _s: Any
    _L: float
    _Ly: float
    _xlo: float
    _ylo: float
    _regrid_every: int
    _aux_field_index: dict
    _step_strategy: Any
    _step_transaction_plan: Any
    _history_persistence: dict  # ADC-631: name -> HistoryPersistence policy (forwarded at install)
    _last_restart_report: Any   # ADC-631: HistoryReplayReport of the last restart with rings
    _last_run_manifest: Any
    _last_run_identity: Any
    _last_restart_identity: Any
    _temporal_restart_state: Any
    _execution_context: Any

    def set_history_persistence(self, *args: Any, **kwargs: Any) -> Any: ...

    def add_equation(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_block(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_poisson(self, *args: Any, **kwargs: Any) -> Any: ...
    def _set_poisson_native(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_density(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_conservative_state(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_magnetic_field(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_aux_field(self, *args: Any, **kwargs: Any) -> Any: ...
    def install_program(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_program_params(self, *args: Any, **kwargs: Any) -> Any: ...
    def density(self, *args: Any, **kwargs: Any) -> Any: ...
    def potential(self, *args: Any, **kwargs: Any) -> Any: ...
    def patch_rectangles(self) -> Any: ...
    @property
    def bound_snapshot(self) -> Any: ...
    @property
    def last_run_identity(self) -> Any: ...
    def _finish_program_install(self, *args: Any, **kwargs: Any) -> Any: ...
    def _install_program_params(self, *args: Any, **kwargs: Any) -> Any: ...
    def _finalize_bind(self, *args: Any, **kwargs: Any) -> Any: ...
