"""pops.numerics.riemann.waves -- the typed wave-speed provider layer (ADC-552).

A model can obtain its SIGNED wave speeds (the interface bound HLL needs) from several
sources: an explicit signed pair (``m.wave_speeds(x=, y=)``), the eigenvalues of the flux
jacobian (``m.wave_speeds_from_jacobian(...)``), the historical primitive-'p' path, or one of
the hook-selector estimates (Einfeldt / Davis). Each source is now a TYPED
:class:`WaveSpeedProvider` (Spec 5 sec.6: a route-choosing object that declares its
requirements / capabilities / options) instead of the fragile ``module.capability("wave_speeds")``
string lookup.

The provider participates in ``HLL(waves=...)``: the factory validates the contract (a signed
provider), folds the provider kind into the descriptor options / requirements, and the install
guard cross-checks it against the compiled model. :func:`provider_of` derives THE provider a
model declares. The moment-hierarchy strategy stays :class:`pops.moments.speeds.ExactSpeeds`
(a different axis: it chooses HOW the exact speeds are computed, not which source HLL binds).
"""
from __future__ import annotations

from typing import Any

from pops.descriptors import Descriptor
from pops.descriptors_report import CapabilitySet, RequirementSet


class WaveSpeedProvider(Descriptor):
    """A typed wave-speed provider (route-choosing descriptor, Spec 5 sec.6).

    ``kind`` names the SOURCE of the signed wave speeds. Five kinds provide a SIGNED pair
    (``smin``/``smax`` per direction), the bound HLL consumes; ``max_wave_speed`` provides only a
    MAJORANT (the Rusanov spectral radius, unsigned) and is REFUSED by HLL. It computes nothing:
    it records the choice and exposes it as ``requirements()`` / ``capabilities()`` / ``options()``.
    """

    category = "wave_speeds"

    #: The five SIGNED-pair kinds (usable by HLL) and the single majorant kind (Rusanov only).
    _SIGNED = ("explicit_pair", "jacobian", "pressure_derived", "einfeldt", "davis")
    _MAJORANT = ("max_wave_speed",)
    _KINDS = _SIGNED + _MAJORANT

    def __init__(self, kind: Any, *, options: Any = None) -> None:
        if kind not in WaveSpeedProvider._KINDS:
            raise ValueError("WaveSpeedProvider kind %r must be one of %s"
                             % (kind, ", ".join(WaveSpeedProvider._KINDS)))
        self.kind = kind
        self._options = dict(options or {})

    @property
    def signed_pair(self) -> bool:
        """True when the provider yields a SIGNED (smin, smax) pair (the HLL contract)."""
        return self.kind in WaveSpeedProvider._SIGNED

    def requirements(self) -> Any:
        """What the source NEEDS from the model (documentary; the hard gate stays at install)."""
        needs = {
            "explicit_pair": "m.wave_speeds(x=(smin, smax), y=(smin, smax))",
            "jacobian": "m.wave_speeds_from_jacobian(...) (flux jacobian eigenvalues)",
            "pressure_derived": "a primitive 'p' + declared eigenvalues (historical path)",
            "einfeldt": "the Einfeldt wave-speed estimate hook",
            "davis": "the Davis wave-speed estimate hook",
            "max_wave_speed": "max_wave_speed (the Rusanov spectral-radius majorant)",
        }
        return RequirementSet({"model": needs[self.kind]})

    def capabilities(self) -> Any:
        """What the source PROVIDES: a signed pair, or (max_wave_speed) only an unsigned majorant."""
        if self.kind == "max_wave_speed":
            return CapabilitySet({"signed_pair": False, "majorant": True})
        return CapabilitySet({"signed_pair": True})

    def options(self) -> dict:
        return dict(self._options, kind=self.kind)

    def describe(self) -> str:
        """A one-line, human-readable summary of this provider (no runtime data)."""
        tail = " (signed pair)" if self.signed_pair else " (unsigned majorant, Rusanov only)"
        return "wave-speed provider %r%s" % (self.kind, tail)

    def __repr__(self) -> str:
        return "WaveSpeedProvider(%r)" % (self.kind,)


# --- factories (typed handles for each source; the public authoring surface) ------------------
def ExplicitPair() -> WaveSpeedProvider:
    """The signed pair declared with ``m.wave_speeds(x=(smin, smax), y=(...))``."""
    return WaveSpeedProvider("explicit_pair")


def FromJacobian(eig: Any = "numeric", blocks: Any = None) -> WaveSpeedProvider:
    """The exact signed speeds from the flux jacobian eigenvalues (``m.wave_speeds_from_jacobian``).

    @p eig ``"numeric"`` | ``"fd"`` (mirror of the authoring option); @p blocks the optional
    block partition. These ride in the provider options for inspection only (the arithmetic is
    generated by the model, not here)."""
    if eig not in ("numeric", "fd"):
        raise ValueError("FromJacobian: eig 'numeric' | 'fd' (got %r)" % (eig,))
    opts = {"eig": eig}
    if blocks is not None:
        opts["blocks"] = blocks
    return WaveSpeedProvider("jacobian", options=opts)


def FromPressure() -> WaveSpeedProvider:
    """The historical source: primitive 'p' + eigenvalues -> signed wave speeds."""
    return WaveSpeedProvider("pressure_derived")


def Einfeldt() -> WaveSpeedProvider:
    """The Einfeldt signed-speed estimate. Typed superset of ``riemann.speeds.einfeldt()``."""
    return WaveSpeedProvider("einfeldt")


def Davis() -> WaveSpeedProvider:
    """The Davis signed-speed estimate. Typed superset of ``riemann.speeds.davis()``."""
    return WaveSpeedProvider("davis")


def MaxWaveSpeed() -> WaveSpeedProvider:
    """The Rusanov MAJORANT (spectral radius). ``signed_pair`` is False -- HLL refuses it."""
    return WaveSpeedProvider("max_wave_speed")


# --- deriving the provider a model declares ---------------------------------------------------
def _authoring_model(model: Any) -> Any:
    """Return the backing HyperbolicModel of @p model (facade / board / raw), or ``None``."""
    for attr in ("_m", "_dsl"):
        inner = getattr(model, attr, None)
        if inner is not None:
            # board.Model -> ._dsl is a facade.Model whose ._m is the HyperbolicModel.
            return getattr(inner, "_m", inner)
    if hasattr(model, "_wave_speeds") or hasattr(model, "_ws_jacobian"):
        return model  # already a HyperbolicModel
    return None


def provider_of(model_or_compiled: Any) -> Any:
    """Derive THE wave-speed provider a model declares, or ``None`` when it declares none.

    On an authoring model (facade / board / :class:`HyperbolicModel`) the source is read from the
    model internals: ``_wave_speeds`` -> :func:`ExplicitPair`, ``_ws_jacobian`` -> :func:`FromJacobian`,
    a primitive ``'p'`` -> :func:`FromPressure`. The mutual exclusion of the explicit pair and the
    jacobian is ALREADY enforced by the authoring layer (``set_wave_speeds`` /
    ``set_wave_speeds_from_jacobian`` raise on the second); we assert it and raise a clear error
    naming both if a foreign object ever set both.

    On a bare :class:`pops.codegen.loader.CompiledModel` the SOURCE kind is not recorded (the ``.so``
    metadata carries only ``has_wave_speeds``): when the handle also exposes ``model`` (the carried
    authoring model) that model is consulted; otherwise a generic signed-pair provider is returned
    when ``has_wave_speeds`` is True, else ``None`` (an honest, documented limitation)."""
    from pops.codegen.loader import CompiledModel  # lazy: codegen <-> numerics edge
    if isinstance(model_or_compiled, CompiledModel):
        carried = getattr(model_or_compiled, "model", None)
        if carried is not None:
            return provider_of(carried)
        return ExplicitPair() if getattr(model_or_compiled, "has_wave_speeds", False) else None

    inner = _authoring_model(model_or_compiled)
    if inner is None:
        return None
    has_pair = getattr(inner, "_wave_speeds", None) is not None
    has_jac = getattr(inner, "_ws_jacobian", None) is not None
    if has_pair and has_jac:
        raise ValueError(
            "provider_of: the model declares BOTH an explicit wave-speed pair (m.wave_speeds) "
            "and a jacobian-derived source (m.wave_speeds_from_jacobian); a model has a SINGLE "
            "wave-speed provider. The authoring layer normally forbids this -- drop one.")
    if has_pair:
        return ExplicitPair()
    if has_jac:
        eig = (inner._ws_jacobian or {}).get("eig", "numeric")
        return FromJacobian(eig=eig if eig in ("numeric", "fd") else "numeric")
    if "p" in getattr(inner, "prim_defs", {}):
        return FromPressure()
    return None


def check_hll_waves(requested_kind: Any, model: Any, ctx: Any) -> None:
    """Cross-check an ``HLL(waves=<provider>)`` selection against @p model's actual source (ADC-552).

    The single shared idiom the install guards call: derive the model's actual provider kind with
    :func:`provider_of`, then delegate to :func:`pops.runtime.routes.check_wave_speed_provider`
    (which raises a precise refusal on a mismatch or when the model emits no wave speeds). @p ctx is
    the message prefix (``"add_equation"`` / ``"AmrSystem.add_equation"`` / ``"install"``)."""
    from pops.runtime.routes import check_wave_speed_provider  # lazy: waves <-> routes edge
    actual = provider_of(model)
    check_wave_speed_provider(requested_kind, model, ctx,
                              actual_provider=actual.kind if actual is not None else None)


class _CapabilityHandles:
    """A tiny typed-handle object exposing a model's capabilities (Spec 5 sec.6, ADC-552).

    ``F.capabilities.wave_speeds`` / ``m.capabilities.wave_speeds`` returns the model's
    :class:`WaveSpeedProvider`. There is NO silent ``None``: a model that declares no wave speeds
    raises a precise, actionable error on access (name the three ways to declare them)."""

    def __init__(self, model: Any) -> None:
        self._model = model

    @property
    def wave_speeds(self) -> Any:
        provider = provider_of(self._model)
        if provider is None:
            raise ValueError(
                "this model declares no wave speeds; declare m.wave_speeds(x=(smin, smax), "
                "y=(smin, smax)), or m.wave_speeds_from_jacobian(...), or a primitive 'p' "
                "(m.primitive('p', ...)) before reading .capabilities.wave_speeds.")
        return provider

    def __repr__(self) -> str:
        return "_CapabilityHandles(%r)" % (getattr(self._model, "name", "model"),)


__all__ = ["WaveSpeedProvider", "ExplicitPair", "FromJacobian", "FromPressure",
           "Einfeldt", "Davis", "MaxWaveSpeed", "provider_of", "check_hll_waves"]
