// GENERATED custom-solver codegen (ADC-462, Spec 3 section 20 / criterion 23 / 24.9): the
// @pops.lib.solver IR-DSL lowers a CUSTOM Richardson solver to a self-contained C++ kernel
// (pops.lib.generate_solver_cpp), emitted by scripts/gen_solver_kernel.py into the header included
// below. This test COMPILES that generated kernel against the real pops::pops runtime and RUNS it on a
// known linear system, proving the lowering is not merely emitted but executes -- and matches the
// native pops::solve_prepared_affine Richardson route (the same backend the DSL maps onto).
//
// OPERATOR: the SPD periodic Helmholtz operator A = I - alpha*Lap (alpha = 0.1),
//   supplied as a value-typed functor. The generated kernel takes the operator as a TEMPLATE
//   parameter (no std::function indirection in the loop), so the SAME functor drives both the
//   generated solver and the prepared native Richardson problem.
//
// MANUFACTURED SOLUTION phi_exact (a periodic sine mode on every native axis); rhs = A(phi_exact)
//   (discretization-exact, so the test exercises the SOLVER not the scheme). We require:
//     - the generated solver converges and recovers phi_exact (max|x - exact| < 1e-5), AND
//     - it matches the native prepared Richardson solve cell-by-cell (same omega / tol / operator) to a tight
//       tolerance -- the generated loop IS the native Richardson iteration, lowered from the IR.
//
// SERIAL test: one exact-ranked box on one explicit rank space; the dot products are nonetheless
// COLLECTIVE (pops::dot -> all_reduce_sum, the identity in serial).
//
// NOTE (test harness): this TEST is left as a single stateful pipeline (generated solve -> native
// reference solve -> cell-by-cell parity) rather than split into independent TEST cases, per the
// campaign rule for a genuinely one-shot scenario -- the parity check below is only meaningful once
// both solves have run against the SAME operator instance, and splitting would force rebuilding (or
// sharing via a fixture) state that exists to be compared exactly once.

#include <gtest/gtest.h>

#include "pops_generated_solver.hpp"  // GENERATED by scripts/gen_solver_kernel.py: richardson_gen_solve

#include <pops/core/foundation/native_dimension.hpp>
#include <pops/numerics/elliptic/linear/generic_krylov.hpp>  // prepared Richardson reference
#include <pops/mesh/execution/for_each.hpp>
#include <pops/mesh/geometry/geometry.hpp>
#include <pops/mesh/index/extent.hpp>
#include <pops/mesh/layout/box_array.hpp>
#include <pops/mesh/layout/distribution.hpp>
#include <pops/mesh/layout/rank_space.hpp>
#include <pops/mesh/storage/mf_arith.hpp>
#include <pops/mesh/storage/multifab.hpp>

#include "test_harness.hpp"  // pops::test::kPi

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <memory>
#include <vector>

using namespace pops;
using pops::test::kPi;

namespace {

constexpr int kDim = kNativeDimension;
constexpr int kN = 32;        // 32 cells per periodic axis
constexpr int kMode = 3;      // nontrivial periodic mode on every native axis
constexpr Real kAlpha = 0.1;  // Helmholtz coefficient: A = I - alpha*Lap (SPD, well-conditioned)
// omega / tol MUST match scripts/gen_solver_kernel.py (GEN_OMEGA / GEN_ABS_TOL) so the generated and
// native Richardson loops trace the same iterates and stop at the same residual (parity below).
constexpr Real kOmega = 1.0e-3;   // stable for the full exact-rank operator in Dim1/2/3
constexpr Real kAbsTol = 1.0e-8;  // ABSOLUTE residual L2 norm the generated loop breaks on

using TestBox = Box<kDim>;
using TestLayout = mesh::BoxArray<kDim>;
using TestRankSpace = mesh::RankSpace<kDim>;
using TestDistribution = mesh::Distribution<kDim>;
using TestField = MultiFab<kDim>;
using TestGeometry = Geometry<kDim>;
using TestOperatorProvider = PreparedAffineOperatorProvider<kDim>;

template <class Ranked, class Value>
Ranked filled(Value value) {
  Ranked result{};
  for (int axis = 0; axis < kDim; ++axis)
    result[axis] = value;
  return result;
}

Extent<kDim> ghosts(int value) {
  return filled<Extent<kDim>>(value);
}

Index<kDim> local_rank() {
  return {};
}

TestDistribution serial_distribution(const TestLayout& layout) {
  const TestRankSpace ranks{Index<kDim>{}, filled<Extent<kDim>>(1)};
  return TestDistribution::partitioned(layout, ranks, std::vector<Index<kDim>>{local_rank()});
}

struct HelmholtzCombineKernel {
  FieldView<Real, kDim> out;
  FieldView<const Real, kDim> input;
  TestBox domain;
  Real inverse_spacing_squared[kDim]{};
  Real alpha;

  POPS_HD void operator()(const Index<kDim>& index) const {
    const Real center = input(index, 0);
    Real laplacian = Real(0);
    for (int axis = 0; axis < kDim; ++axis) {
      Index<kDim> lower = index;
      Index<kDim> upper = index;
      lower[axis] = index[axis] == domain.lo[axis] ? domain.hi[axis] : index[axis] - 1;
      upper[axis] = index[axis] == domain.hi[axis] ? domain.lo[axis] : index[axis] + 1;
      laplacian +=
          (input(lower, 0) - Real(2) * center + input(upper, 0)) * inverse_spacing_squared[axis];
    }
    out(index, 0) = center - alpha * laplacian;
  }
};

// The matrix-free SPD Helmholtz operator as a VALUE-TYPED functor: A(out, in) = in - alpha*Lap(in).
// The generated kernel takes it as a template parameter (inlined; no std::function in the loop).
// Prepared native workspaces use the same stateless recipe through fresh operator sessions which
// capture the exact geometry and report zero persistent fields.
struct HelmholtzOp {
  TestGeometry geometry;

  void operator()(TestField& out, const TestField& in) const {
    Real inverse_spacing_squared[kDim]{};
    for (int axis = 0; axis < kDim; ++axis) {
      const Real inverse = Real(1) / geometry.spacing(axis);
      inverse_spacing_squared[axis] = inverse * inverse;
    }
    for (std::size_t local = 0; local < out.local_size(); ++local) {
      HelmholtzCombineKernel kernel{
          out.fab(local).view(), in.fab(local).view(), geometry.domain(), {}, kAlpha};
      for (int axis = 0; axis < kDim; ++axis)
        kernel.inverse_spacing_squared[axis] = inverse_spacing_squared[axis];
      for_each_cell(out.box(local), kernel);
    }
  }
};

POPS_HD Real phi_exact(const RealVector<kDim>& center) {
  Real value = Real(1);
  for (int axis = 0; axis < kDim; ++axis)
    value *= std::sin(Real(2 * kMode) * kPi * center[axis]);
  return value;
}

struct SampleExactKernel {
  FieldView<Real, kDim> values;
  TestGeometry geometry;

  POPS_HD void operator()(const Index<kDim>& index) const {
    const RealVector<kDim> center = geometry.cell_center(index);
    values(index, 0) = phi_exact(center);
  }
};

struct AbsoluteDifferenceKernel {
  FieldView<const Real, kDim> left;
  FieldView<const Real, kDim> right;

  POPS_HD Real operator()(const Index<kDim>& index) const {
    const Real difference = left(index, 0) - right(index, 0);
    return difference < Real(0) ? -difference : difference;
  }
};

Real max_abs_diff(const TestField& a, const TestField& b) {
  Real d = 0;
  for (std::size_t local = 0; local < a.local_size(); ++local)
    d = std::max(
        d, for_each_cell_reduce_max(
               a.box(local), AbsoluteDifferenceKernel{a.fab(local).view(), b.fab(local).view()}));
  return static_cast<Real>(all_reduce_max(static_cast<double>(d)));
}

TestOperatorProvider prepared_helmholtz_provider(const TestGeometry& geometry) {
  return TestOperatorProvider::trusted_extension(
      {"pops.test.generated-solver.helmholtz", 1}, {}, [geometry](const ExecutionLane&) {
        return PreparedAffineOperatorSessionCallbacks<kDim>{
            {},
            [geometry](TestField& out, const TestField& in) { HelmholtzOp{geometry}(out, in); },
            [] { return std::size_t{0}; }};
      });
}

}  // namespace

TEST(test_solver_codegen_generated, generated_kernel_matches_native_richardson) {
  const TestBox domain{Index<kDim>{}, filled<Index<kDim>>(kN - 1)};
  const TestGeometry geometry =
      TestGeometry::from_bounds(domain, RealVector<kDim>{}, filled<RealVector<kDim>>(Real(1)));
  const TestLayout layout(std::vector<TestBox>{domain});
  const TestDistribution distribution = serial_distribution(layout);

  const HelmholtzOp op{geometry};

  // Manufactured solution + the discretization-exact rhs = A(phi_exact).
  TestField phi_exact_mf(layout, distribution, local_rank(), 1, ghosts(1));
  for (std::size_t local = 0; local < phi_exact_mf.local_size(); ++local) {
    for_each_cell(phi_exact_mf.box(local),
                  SampleExactKernel{phi_exact_mf.fab(local).view(), geometry});
  }
  TestField rhs(layout, distribution, local_rank(), 1, ghosts(0));
  op(rhs, phi_exact_mf);

  // --- Run the GENERATED custom solver (the lowered @pops.lib.solver IR) ---
  TestField x_gen(layout, distribution, local_rank(), 1, ghosts(1));
  x_gen.set_val(0.0);
  const SolveReport r_gen = richardson_gen_solve(op, x_gen, rhs);
  const Real err_gen = max_abs_diff(x_gen, phi_exact_mf);
  std::printf("generated : %s in %d iters (rel=%.2e) | max|x - exact| = %.3e\n",
              r_gen.solved() ? "CONVERGED" : "FAILED", r_gen.iters, r_gen.rel_residual, err_gen);
  EXPECT_TRUE(r_gen.solved()) << "generated_converged";
  EXPECT_TRUE(r_gen.iters > 1) << "generated_iters_gt_1 iters=" << r_gen.iters;
  EXPECT_TRUE(err_gen < 1e-5) << "generated_recovers_exact err_gen=" << err_gen;

  // --- Run the NATIVE prepared Richardson solve with the SAME operator / omega (the reference) ---
  // The prepared native loop receives the same absolute floor as the generated kernel.
  TestField x_ref(layout, distribution, local_rank(), 1, ghosts(1));
  x_ref.set_val(0.0);
  const KrylovFootprint<kDim> footprint{1, ghosts(1), false};
  OperatorEvaluationSnapshot snapshot{{UINT64_C(1), UINT64_C(2), UINT64_C(3), UINT64_C(4)},
                                      1,
                                      0,
                                      0,
                                      1,
                                      0,
                                      0,
                                      1,
                                      detail::layout_fingerprint(x_ref),
                                      {UINT64_C(5), UINT64_C(6), UINT64_C(7), UINT64_C(8)}};
  PreparedAffineLinearProblem<kDim> problem(
      x_ref, prepared_helmholtz_provider(geometry), PreparedLinearPreconditioner<kDim>::identity(),
      LinearOperatorProperties::general(), footprint, PreparedNullspacePolicy<kDim>::nonsingular(),
      [&snapshot]() { return snapshot; });
  KrylovWorkspace<kDim> workspace(x_ref, richardson_krylov_method<kDim>(kOmega), footprint);
  problem.prepare(snapshot);
  workspace.bind(problem);
  const SolveReport r_ref = detail::solve_prepared_affine_in_place(
      problem, workspace, x_ref, rhs,
      KrylovControls<kDim>{richardson_krylov_method<kDim>(kOmega), Real(0), kAbsTol, 1000000});
  const Real err_ref = max_abs_diff(x_ref, phi_exact_mf);
  std::printf("native    : %s in %d iters (rel=%.2e) | max|x - exact| = %.3e\n",
              r_ref.solved() ? "CONVERGED" : "FAILED", r_ref.iters, r_ref.rel_residual, err_ref);
  EXPECT_TRUE(r_ref.solved()) << "native_converged";

  // --- PARITY: the generated kernel IS the native Richardson iteration (same omega / tol / op). ---
  // Both start from x = 0 with identical omega and the same discrete operator, so they trace the same
  // sequence of iterates to the same fixed point; the recovered solutions must agree tightly.
  const Real parity = max_abs_diff(x_gen, x_ref);
  std::printf("parity    : max|x_gen - x_native| = %.3e\n", parity);
  EXPECT_TRUE(parity < 1e-6) << "generated_matches_native_richardson parity=" << parity;
}
