"""Derive numerical input evidence from the existing Module and carrier authority."""
from __future__ import annotations

from collections.abc import Mapping
from fractions import Fraction
from typing import Any

from pops.model.ownership import _definition_fingerprint_scope

from pops.identity.digest import make_identity

from ._resolved_operation_records import (
    EvaluationRequest, ExchangeRecord, NumericalConstruction, ResolvedAccess, TermOccurrence, data,
    identifiers,
)


_LEGACY_ROUTES = {
    "grid_operator": "legacy:flux", "local_source": "legacy:source_term",
    "local_linear_operator": "legacy:linear_source", "local_rate": "legacy:rate_operator",
    "field_operator": "legacy:elliptic_field", "projection": "legacy:projection",
    "local_transform": "legacy:local_transform", "coupled_rate": "program:multi_block_operator",
}


def native_route(module: Any, operator: Any) -> tuple[str | None, str | None]:
    """Current checked adapter vocabulary; no capability follows from a type name alone."""
    from pops._ir.balance import source_balance_supported
    if source_balance_supported(operator.lowering.get("physical_balance")):
        return "program:source_balance", None
    from pops.numerics.diffusion import diffusion_balance_supported
    from pops.numerics.scharfetter_gummel import fitted_balance_supported
    if diffusion_balance_supported(operator.lowering.get("physical_balance")) or fitted_balance_supported(operator.lowering.get("physical_balance")):
        return "program:diffusive_rhs", None
    if operator.lowering.get("diffusive_law") is not None or operator.lowering.get("drift_law") is not None:
        return "program:constitutive_flux", None
    if operator.lowering.get("native_unsupported"):
        return None, "unsupported_physical_balance"
    if operator.lowering.get("joint_balance"):
        from pops.physics.interactions import joint_balance_supported
        if joint_balance_supported(operator.lowering.get("physical_balance")):
            return "program:multi_block_operator", None
        return None, "invalid_joint_balance"
    if operator.kind not in _LEGACY_ROUTES:
        return None, "operator_kind_not_lowerable"
    if operator.kind not in {"local_rate", "coupled_rate"} \
            and (operator.body is None or callable(operator.body)):
        return None, "expression_body_required"
    states = tuple(item for item in operator.signature.inputs if getattr(item, "kind", None) == "state")
    if operator.kind == "field_operator" and len(states) > 1:
        return None, "multi_state_field_provider_unsupported"
    if operator.kind == "field_operator" \
            and not 1 <= len(getattr(operator.signature.output, "components", ())) <= 4:
        return None, "field_output_arity_unsupported"
    return _LEGACY_ROUTES[operator.kind], None


def provider_evidence(packs: Any) -> dict[str, Any]:
    from .component_provider_packs import ComponentProviderPacks
    if type(packs) is not ComponentProviderPacks:
        raise TypeError("resolved inputs require the existing exact ComponentProviderPacks")
    return {"complete": packs.complete.to_data(),
            "by_operator": {name: pack.to_data() for name, pack in sorted(packs.by_operator.items())},
            "physical_flux": packs.physical_flux.to_data(),
            "consumer_plans": data(packs.consumer_plans),
            "physical_flux_plan": data(packs.physical_flux_plan),
            "auxiliary": packs.auxiliary.to_data(),
            "auxiliary_routes": data(packs.auxiliary_route_metadata)}


def resolve_plan_provider_packs(module: Any, operations: Any) -> Any:
    """Project the existing carrier using the plan's exact component reads.

    Unknown projected carrier roles stay conservative. Storage/provider slots are
    preserved; consumer-local slots are regenerated by the existing implementation.
    """
    from .component_provider_packs import (
        ComponentProviderPacks, consumer_provider_plan, resolve_component_provider_packs,
    )
    base = resolve_component_provider_packs(module)
    operations = tuple(operations)
    by_operator = {}
    for operator in module.operator_registry():
        identity = "operation:%s" % _reference(module.operator_handle(operator.name))
        selected_operations = tuple(item for item in operations if item.identity == identity
                                    or item.guarantees.get("declaration_operation") == identity)
        original = base.by_operator[operator.name]
        if not selected_operations:
            by_operator[operator.name] = original
            continue
        selected = []
        # Explicit provider requirements may have narrowed the legacy per-op
        # carrier already. Union transparent reads with those requirements from
        # the same complete authority, rather than intersecting with that subset.
        for key in base.complete:
            spaces = [space for space in module.field_spaces().values()
                      if space.name == key.space_name and space.kind == key.space_kind]
            if len(spaces) != 1:
                if key in original:
                    selected.append(key)  # Preserve unresolved projected carrier roles.
                continue
            reference = _reference(module.field_handle(spaces[0]))
            if any(read.reference == reference
                   and (read.complete or key.component in read.components)
                   for operation in selected_operations for read in operation.inputs):
                selected.append(key)
        by_operator[operator.name] = base.complete.select(selected)
    flux = base.complete.select(key for operator in module.operator_registry()
                                if operator.kind == "grid_operator"
                                for key in by_operator[operator.name])
    return ComponentProviderPacks(
        complete=base.complete, by_operator=by_operator, physical_flux=flux,
        auxiliary=base.auxiliary, auxiliary_routes=base.auxiliary_routes,
        auxiliary_route_metadata=base.auxiliary_route_metadata,
        consumer_plans={name: consumer_provider_plan(pack) for name, pack in by_operator.items()},
        physical_flux_plan=consumer_provider_plan(flux))


def _space_handle(module: Any, space: Any) -> Any:
    from pops.model.spaces import AuxSpace

    if isinstance(space, AuxSpace):
        canonical = module.aux().get(space.name)
        if canonical is None or canonical.to_data() != space.to_data():
            raise ValueError("auxiliary input representation differs from its Module registry")
        return module.aux_handle(canonical)
    kind = getattr(space, "kind", None)
    if kind in {"state", "field"}:
        registry = module.state_spaces() if kind == "state" else module.field_spaces()
        canonical = registry.get(space.name)
        # Frozen model snapshots detach signature descriptors. Authenticate the
        # full descriptor before recovering its one current registry handle.
        if canonical is None or canonical.to_data() != space.to_data():
            raise ValueError("input representation differs from its Module registry")
        return module.state_handle(canonical) if kind == "state" else module.field_handle(canonical)
    return None


def _reference(value: Any) -> str:
    from pops.model.handles import Handle

    if isinstance(value, Handle):
        return value._resolved().qualified_id
    if isinstance(value, str):
        return value
    from pops._ir.expr import Expr
    from pops._ir.visitors import _dag_key_data
    if isinstance(value, Expr):
        from pops._ir.expr_references import resolve_expr_references

        resolved = resolve_expr_references(value, lambda handle: handle._resolved(), {},
                                           allow_formula_vars=True)
        return make_identity("physical_expression", _dag_key_data((resolved,))).token
    qualified = getattr(value, "qualified_id", None)
    if isinstance(qualified, str):
        return qualified
    if isinstance(value, tuple) and len(value) == 2 and type(value[1]) is int:
        return "%s/occurrence:%d" % (_reference(value[0]), value[1])
    to_data = getattr(value, "to_data", None)
    if callable(to_data):
        from ._plans import _evidence

        return make_identity("physical_reference", _evidence(
            to_data(), where="physical reference")).token
    raise TypeError("scientific reference has no qualified identity")


def derive_inputs(module: Any, operator: Any, packs: Any, *, boundary_data: Any = ()) \
        -> tuple[ResolvedAccess, ...]:
    """Collect expression leaves; opaque native input reads remain conservatively complete."""
    from pops._ir.expr import Const, Expr, Var
    from pops._ir.values import StateRef
    from pops._ir.visitors import _children
    from pops.model.handles import Handle
    from pops.model.state_symbols import state_component_symbol

    # Every declared input must name its exact registered carrier, even when a
    # transparent constant body happens not to read it. Output projections do
    # not grant unregistered input spaces a storage identity.
    for space in operator.signature.inputs:
        _space_handle(module, space)
    spaces = (*module.state_spaces().values(), *module.field_spaces().values())
    by_handle = {_reference(_space_handle(module, space)): space for space in spaces}
    auxiliaries = module.aux()
    by_handle.update({_reference(_space_handle(module, space)): space
                      for space in auxiliaries.values()})
    selected_states = tuple(space for space in operator.signature.inputs
                            if getattr(space, "kind", None) == "state")
    result: dict[tuple[str, str, str], ResolvedAccess] = {}
    seen: set[tuple[int, str, str]] = set()
    sampling = "face_trace" if operator.kind == "grid_operator" else "cell"

    def add(handle: Any, space: Any, component: Any, sample: str, origin: str,
            *, complete: bool = False) -> None:
        reference = _reference(handle)
        descriptor = space.to_data() if space is not None else {
            "kind": getattr(handle, "kind", "quantity"), "representation": "unspecified"}
        available_components = getattr(space, "components", (getattr(space, "name", ""),))
        components = tuple(available_components) if complete else (
            () if component is None else (component,))
        if component is not None and space is not None and component not in available_components:
            raise ValueError("typed dependency component is outside its declared space")
        key = (reference, sample, str(component) if not complete else "*")
        previous = result.get(key)
        origins = (origin,) if previous is None else tuple(sorted(set((*previous.origins, origin))))
        result[key] = ResolvedAccess(reference, descriptor["kind"], descriptor, sample,
                                     components, complete, origins)

    def all_inputs(origin: str, sample: str) -> None:
        for space in operator.signature.inputs:
            handle = _space_handle(module, space)
            if handle is not None:
                add(handle, space, None, sample, origin, complete=True)

    def walk(value: Any, sample: str, origin: str) -> None:
        context = (id(value), sample, origin)
        if context in seen:
            return
        seen.add(context)
        if isinstance(value, StateRef):
            walk(value.expr, "left_face_trace" if value.side == "L" else "right_face_trace", origin)
            return
        if isinstance(value, Handle):
            from pops.model.handles import OperatorHandle

            if isinstance(value, OperatorHandle) or value.kind in {"flux", "source"}:
                return  # Scientific declaration dependency, not a numerical quantity read.
            add(value, by_handle.get(_reference(value)), None, sample, origin,
                complete=_reference(value) in by_handle)
            return
        if isinstance(value, Mapping):
            for item in value.values():
                walk(item, sample, origin)
            return
        if isinstance(value, (tuple, list)):
            for item in value:
                walk(item, sample, origin)
            return
        footprint = getattr(value, "__pops_native_read_footprint__", None)
        if callable(footprint):
            reads = footprint()
            if reads is None:
                all_inputs("opaque_native_complete_input", sample)
            else:
                if not isinstance(reads, tuple):
                    raise TypeError("native read footprint must be a tuple or explicit None")
                for item in reads:
                    if not isinstance(item, (Expr, Handle)):
                        raise TypeError("native footprint must contain typed expression/Handle reads")
                    walk(item, sample, "native_footprint")
            return
        if callable(value):
            all_inputs("opaque_native_complete_input", sample)
            return
        if not isinstance(value, Expr):
            if origin == "physical_boundary" and value is not None and not isinstance(
                    value, (str, int, float, bool)):
                all_inputs("opaque_boundary_complete_input", sample)
            return
        handle = getattr(value, "handle", None)
        if isinstance(handle, Handle):
            component = getattr(value, "component", None)
            add(handle, by_handle.get(_reference(handle)), component, sample, origin,
                complete=component is None and _reference(handle) in by_handle)
            return
        if isinstance(value, Var):
            if value.kind == "prim":
                from pops.model.primitive_recipes import resolve_primitive_recipe

                recipe = resolve_primitive_recipe(module, value.name)
                if recipe is not None:
                    walk(recipe, sample, "primitive_recipe:%s" % value.name)
                    return
            matches = [(space, component) for space in spaces for component in space.components
                       if value.name == state_component_symbol(space, component)
                       or (space in operator.signature.inputs and value.name == component)]
            if len(matches) == 1:
                space, component = matches[0]
                add(_space_handle(module, space), space, component, sample, origin)
            elif not matches and value.kind == "aux" and value.name in auxiliaries:
                space = auxiliaries[value.name]
                add(_space_handle(module, space), space, value.name, sample, origin)
            elif value.kind == "prim" and selected_states:
                # Primitive recovery can depend on the full state. Do not guess a fine footprint.
                for space in selected_states:
                    add(_space_handle(module, space), space, None, sample,
                        "constitutive_recovery_complete_input", complete=True)
            elif matches or value.kind in {"cons", "aux", "prim"}:
                raise ValueError("unresolved or ambiguous symbolic dependency %r" % value.name)
            else:
                result[(value.name, sample, value.kind)] = ResolvedAccess(
                    "formula:%s:%s" % (value.kind, value.name), value.kind,
                    {"kind": value.kind, "representation": "formula_coordinate"}, sample,
                    origins=(origin,))
            return
        children = _children(value)
        for child in children:
            walk(child, sample, origin)
        # Parent declaration_references() is transitive. References owned by
        # children were already visited in their numerical sampling context
        # (notably left/right face traces), so only collect additional metadata.
        references = value.declaration_references()
        child_references = {_reference(reference) for child in children
                            for reference in child.declaration_references()}
        for reference in references:
            if _reference(reference) not in child_references:
                walk(reference, sample, origin)
        if not children and not references and not isinstance(value, Const):
            all_inputs("opaque_expression_complete_input", sample)

    walk(operator.body, sampling, "body")
    walk(operator.lowering, sampling, "coefficient_or_lowering")
    balance = operator.lowering.get("physical_balance")
    if balance is not None:
        walk(getattr(balance.accumulation, "law", None), sampling, "accumulation_law")
        for occurrence in balance.occurrences:
            walk(occurrence.payload, sampling, "physical_balance")
    if operator.kind == "local_rate":
        bindings = {_reference(subject): _reference(target)
                    for subject, target in module.operator_bindings().items()}
        for occurrence in _occurrences(module, operator,
                "operation:%s" % _reference(module.operator_handle(operator.name))):
            for dependency in module.operator_registry():
                if _reference(module.operator_handle(dependency.name)) == bindings.get(
                        occurrence.operator, occurrence.operator):
                    walk(dependency.body, "face_trace" if dependency.kind == "grid_operator" else "cell",
                         "balance_contribution")
    walk(boundary_data, "boundary", "physical_boundary")
    if operator.kind == "grid_operator":
        walk(getattr(module, "_eigenvalues", None), sampling, "wave_speed")
    # Explicit provider requirements are additional native dependencies, not a
    # reason to retain every unused FieldSpace component of a transparent body.
    required = operator.requirements.get("aux", ())
    for key in packs.by_operator[operator.name]:
        if key.component not in required:
            continue
        matches = [space for space in spaces if space.name == key.space_name
                   and space.kind == key.space_kind]
        if len(matches) == 1 and not any(
                item.reference == _reference(_space_handle(module, matches[0]))
                and item.sampling == sampling
                and (item.complete or key.component in item.components)
                for item in result.values()):
            add(_space_handle(module, matches[0]), matches[0], key.component,
                sampling, "declared_provider_requirement")
    return tuple(result[key] for key in sorted(result))


def _occurrences(module: Any, operator: Any, identity: str) -> tuple[TermOccurrence, ...]:
    balance = operator.lowering.get("physical_balance")
    if balance is not None:
        return tuple(TermOccurrence(
            _reference(term.identity), _reference(term.payload), _reference(term.target),
            term.kind, Fraction(term.coefficient)) for term in balance.occurrences)
    target_space = getattr(operator.signature.output, "base", operator.signature.output)
    from pops.model.spaces import FieldSpace

    if ((operator.kind == "field_operator" or operator.lowering.get("diffusive_law") is not None
         or operator.lowering.get("drift_law") is not None)
            and isinstance(target_space, FieldSpace)
            and target_space.name not in module.field_spaces()):
        # A field provider may project one result from a shared registered
        # carrier. This is the operator's typed result, not a new stored field:
        # keep its exact descriptor in NumericalConstruction.outputs and its
        # identity under the authenticated operator/source Module authority.
        target = "output:%s" % identity
    else:
        handle = _space_handle(module, target_space)
        target = _reference(handle) if handle is not None else "output:%s" % identity
    if operator.kind == "local_rate":
        terms = []
        low = operator.lowering
        fluxes = tuple(low.get("fluxes") or ())
        if not fluxes and low.get("flux", True):
            default = low.get("default_flux")
            grids = tuple(op.name for op in module.operator_registry() if op.kind == "grid_operator")
            fluxes = (default,) if default else tuple(name for name in grids if name in {"flux", "flux_default"})
            if not fluxes and len(grids) == 1:
                fluxes = grids
        sources = low.get("sources")
        if sources is None:
            sources = tuple(op.name for op in module.operator_registry()
                            if op.kind == "local_source" and op.name == "default")
        for kind, names, coefficient in (("transport", fluxes, -1), ("source", sources, 1)):
            for name in names:
                terms.append(TermOccurrence("%s/term:%d" % (identity, len(terms)),
                    _reference(module.operator_handle(name)), target, kind, Fraction(coefficient)))
        return tuple(terms)
    return (TermOccurrence("%s/term:0" % identity,
                           _reference(module.operator_handle(operator.name)), target,
                           operator.kind),)


def _derive_effects(module: Any, operator: Any, boundary_data: Any) -> tuple[str, ...]:
    """Retain obligations from the expressions this operation evaluates.

    This is a conservative barrier union, not an eager evaluation or permission
    to move expressions across their existing guards/materialization boundaries.
    Declaration references are followed only through the selected rate terms.
    """
    from pops._ir.application import OperatorApplication
    from pops._ir.native_call import NativeCall
    from pops._ir.expr import Const, Div, Expr, Pow, Sqrt, Var
    from pops._ir.visitors import _children
    from pops.model.handles import Handle

    effects: dict[str, None] = {}
    seen: set[tuple[int, bool]] = set()
    visited_operators: set[str] = set()
    bindings = {_reference(subject): _reference(target)
                for subject, target in module.operator_bindings().items()}
    declarations = {_reference(module.operator_handle(item.name)): item
                    for item in module.operator_registry()}

    def retain(*obligations: str) -> None:
        effects.update(dict.fromkeys(obligations))

    def walk(value: Any, *, opaque: bool = False) -> None:
        key = (id(value), opaque)
        if key in seen:
            return
        seen.add(key)
        if isinstance(value, Mapping):
            for item in value.values():
                walk(item, opaque=opaque)
        elif isinstance(value, (tuple, list)):
            for item in value:
                walk(item, opaque=opaque)
        elif callable(value) or callable(getattr(value, "__pops_native_read_footprint__", None)):
            # A precise read footprint does not establish purity or successful evaluation.
            retain("opaque", "fallible")
        elif isinstance(value, Expr):
            if isinstance(value, (Div, Sqrt, Pow)):
                retain("fallible")
            if isinstance(value, OperatorApplication):
                retain(*value.effects)
            if isinstance(value, NativeCall):
                retain("opaque", "fallible", *value.effects)
            if isinstance(value, Var) and value.kind == "prim":
                from pops.model.primitive_recipes import resolve_primitive_recipe

                recipe = resolve_primitive_recipe(module, value.name)
                if recipe is None:
                    retain("opaque", "fallible")
                else:
                    walk(recipe, opaque=True)
            children = _children(value)
            for child in children:
                walk(child, opaque=opaque)
            if not children and not value.declaration_references() \
                    and not isinstance(value, (Const, Var)):
                retain("opaque", "fallible")
        elif opaque and value is not None and not isinstance(
                value, (str, int, float, bool, Handle)):
            retain("opaque", "fallible")

    def visit(declaration: Any) -> None:
        if declaration.name in visited_operators:
            return
        visited_operators.add(declaration.name)
        if declaration.kind == "field_operator":
            retain("solve", "collective", "fallible")
        retain(*identifiers(declaration.capabilities.get("effects", ()), "operator effects"))
        walk(declaration.body, opaque=True)
        walk(declaration.lowering)
        balance = declaration.lowering.get("physical_balance")
        if balance is not None:
            walk(getattr(balance.accumulation, "law", None), opaque=True)
            for occurrence in balance.occurrences:
                walk(occurrence.payload, opaque=True)
                from pops.physics.board_handles import SourceHandle

                # Retained board sources carry their explicit legacy registry
                # route; unlike fluxes they do not use operator_bindings().
                if isinstance(occurrence.payload, SourceHandle):
                    if occurrence.payload.owner_path != module.owner_path:
                        raise ValueError("balance source effect belongs to a different Module")
                    source = module.operator_registry().get(occurrence.payload.reg_name)
                    if source.kind != "local_source":
                        raise ValueError("balance source effect requires its local-source declaration")
                    visit(source)
        if declaration.kind == "local_rate":
            identity = "operation:%s" % _reference(module.operator_handle(declaration.name))
            for occurrence in _occurrences(module, declaration, identity):
                dependency = declarations.get(bindings.get(occurrence.operator, occurrence.operator))
                if dependency is not None:
                    visit(dependency)
        if declaration.kind == "grid_operator":
            walk(getattr(module, "_eigenvalues", None), opaque=True)

    visit(operator)
    walk(boundary_data, opaque=True)
    return tuple(effects)


@_definition_fingerprint_scope()
def derive_module_operations(module: Any, packs: Any, *, boundary_data: Any = ()) \
        -> tuple[tuple[EvaluationRequest, ...], tuple[NumericalConstruction, ...]]:
    requests, operations = [], []
    for operator in module.operator_registry():
        identity = "operation:%s" % _reference(module.operator_handle(operator.name))
        evaluation = "evaluation:%s" % identity
        occurrences = _occurrences(module, operator, identity)
        requests.append(EvaluationRequest(evaluation, occurrences))
        route, refusal = native_route(module, operator)
        effects = _derive_effects(module, operator, boundary_data)
        exchanges = tuple(ExchangeRecord(term.identity, term.target)
                          for term in occurrences if term.kind in {"flux", "transport", "diffusion", "drift", "grid_operator"})
        operations.append(NumericalConstruction(
            identity, evaluation, tuple(term.identity for term in occurrences),
            inputs=derive_inputs(module, operator, packs, boundary_data=boundary_data),
            outputs=(operator.signature.output.to_data(),),
            sampling="face_trace" if operator.kind == "grid_operator" else "cell",
            effects=effects, exchanges=exchanges, native_route=route, refusal=refusal,
            guarantees={"analytical": "unverified", "numerical": "unverified",
                        "native_execution": "not_executed_by_resolution"}))
    return tuple(requests), tuple(operations)
