"""pops.codegen.cache : out-of-source .so cache helpers.

Extracted verbatim from pops.dsl (bodies byte-for-byte); only import lines adjusted.
Public API re-exported from pops.codegen.__init__.
"""
from __future__ import annotations

import os
from threading import Lock
from typing import Any

from .toolchain import _pops_module  # noqa: F401 -- used by _native_mpi_flags


# Optimization flags shared by generated libraries on the sole production path.
# Default -O3 -DNDEBUG: hot-loop asserts disarmed + full vectorization -> parity with a native block (at
# -O2 without -DNDEBUG the generated kernel is ~1.48x). $POPS_DSL_OPTFLAGS overrides; affects NEITHER the
# ABI NOR portability.
_DSL_OPTFLAGS_DEFAULT = "-O3 -DNDEBUG"


def _dsl_optflags() -> list:
    """Optimization flags list for the production DSL .so (cf. _DSL_OPTFLAGS_DEFAULT)."""
    return os.environ.get("POPS_DSL_OPTFLAGS", _DSL_OPTFLAGS_DEFAULT).split()


def _platform_cache_key() -> str:
    """MACHINE traits that change the binary code of the .so without changing the C++ ABI key (__VERSION__
    is identical cross-arch): CPU architecture + optimization flags. Without them in the cache
    key, a .so x86_64 (Rosetta) or -march=native would be reused on another machine/arch via
    a shared cache (NFS, synchronized home) -> SIGILL (illegal instruction) or cryptic dlopen."""
    import platform
    return "arch=%s;optflags=%s" % (platform.machine(),
                                    os.environ.get("POPS_DSL_OPTFLAGS", _DSL_OPTFLAGS_DEFAULT))


# --- Out-of-source build cache -----------------------------------------------
# When the caller does not provide so_path, m.compile(...) writes the .so into a SHARED out-of-source
# cache (never next to the temporary .cpp), indexed by a stable model key: model_hash (formulas
# + roles + n_aux + params) AND abi_key (header signature + compiler + std). Two compilations
# of the SAME model (same key) reuse the cached .so (cache HIT, no recompilation); changing the
# model OR a parameter OR the toolchain changes the key -> new .so (cache MISS, recompilation). The
# file name carries the key, so several variants coexist without collision. cf. the same idea
# in adc_cases/common/native.py (ABI key = compiler + flags + header signature).
def _configured_cache_root() -> tuple[str, bool]:
    """Return the single configured PoPS cache authority and whether it is explicit."""
    override = os.environ.get("POPS_CACHE_DIR")
    if override:
        return override, True
    xdg = os.environ.get("XDG_CACHE_HOME") or os.path.join(os.path.expanduser("~"), ".cache")
    return os.path.join(xdg, "pops"), False


def pops_cache_dir() -> str:
    """Cache directory for the .so files generated by m.compile() without an explicit so_path.

    $POPS_CACHE_DIR (override), else $XDG_CACHE_HOME/pops/dsl, else ~/.cache/pops/dsl. Created as needed.
    Out-of-source by construction (never inside the repo tree), so nothing to ignore on the git side."""
    root, explicit = _configured_cache_root()
    base = root if explicit else os.path.join(root, "dsl")
    os.makedirs(base, exist_ok=True)
    return base


def component_store_dir() -> str:
    """Immutable installed-component store under the configured PoPS cache authority.

    ``POPS_CACHE_DIR`` is the explicit authority when set. Otherwise this resolves to
    ``$XDG_CACHE_HOME/pops/component-store-v1`` (or ``~/.cache/pops/...``).
    Artifact installation owns content addressing, atomic publication and digest revalidation.
    """
    root, _ = _configured_cache_root()
    directory = os.path.join(root, "component-store-v1")
    os.makedirs(directory, exist_ok=True)
    return directory


def _identity_cache_so_path(spec_identity: Any) -> str:
    """Return the collision-safe path addressed by one artifact specification.

    The complete digest is retained in the filename.  Human-readable names and paths are not
    identity inputs; any emitted symbol name that changes bytes belongs in the artifact-spec
    component payload before this function is called.
    """
    from pops.identity import Identity

    if not isinstance(spec_identity, Identity) or spec_identity.domain != "artifact-spec":
        raise TypeError("cache path requires a pops.artifact-spec Identity")
    return os.path.join(pops_cache_dir(), spec_identity.hexdigest + ".so")


def _precision_cache_key() -> str:
    """The floating-point precision component of a compiled artifact's cache key (ADC-536).

    The native runtime is fixed to double precision today (``NATIVE_REAL_BYTES`` = 8), but the token
    enters the key so a FUTURE precision switch (single / mixed) is a cache MISS, never a silent
    reuse of a double-precision ``.so`` under a single-precision request. Readable
    ("precision=double;real_bytes=8") so the mismatching field is nameable in a diagnostic. When a
    typed ``Production(precision=...)`` backend descriptor lands (538/537) it becomes the token's
    source; until then it mirrors the single native fact."""
    from pops.runtime_environment import NATIVE_PRECISION, NATIVE_REAL_BYTES
    return "precision=%s;real_bytes=%d" % (NATIVE_PRECISION, NATIVE_REAL_BYTES)


def _registry_cache_key() -> str:
    """Route registry + report vocabulary components of EVERY cache key (ADC-599).

    The typed native route registry (pops.runtime.routes / route_ids.hpp) and the
    capabilities/reports vocabulary participate in the artifact identity: an artifact built
    against a different route set (a route added/removed/re-tokenized, a native entry renamed)
    or an older report vocabulary must be a cache MISS, never a silent reuse. The component is
    readable ("routes=v2:<hash16>;capvocab=1") so the mismatching field is nameable in
    diagnostics and in compiled.inspect()."""
    from pops.runtime.routes import (CAPABILITY_VOCAB_VERSION, ROUTE_REGISTRY_VERSION,
                                     route_registry_hash)
    return "routes=v%d:%s;capvocab=%d" % (ROUTE_REGISTRY_VERSION, route_registry_hash()[:16],
                                          CAPABILITY_VOCAB_VERSION)


_process_so_identity: dict[str, str] = {}
_process_so_identity_lock = Lock()


def _artifact_distinct_so_path(so_path: Any, spec_identity: Any) -> Any:
    """Keep explicit native paths safe from the dynamic loader's path-based handle cache.

    Recompiling a different production artifact over an already used path can make ``dlopen``
    return the old handle. The first identity retains the requested path; later identities use a
    deterministic sibling derived from their authenticated artifact identity. Rebuilding the same
    identity keeps the same path because its native contract is unchanged.
    """
    import hashlib
    import os

    requested = os.path.abspath(os.fspath(so_path))
    identity = str(spec_identity)
    with _process_so_identity_lock:
        previous = _process_so_identity.get(requested)
        if previous is None:
            _process_so_identity[requested] = identity
            return so_path
        if previous == identity:
            return so_path

        digest = hashlib.sha256(identity.encode("utf-8")).hexdigest()[:16]
        root, ext = os.path.splitext(os.fspath(so_path))
        alternate = "%s.%s%s" % (root, digest, ext or ".so")
        _process_so_identity.setdefault(os.path.abspath(alternate), identity)
        return alternate


def _record_artifact_identity(so_path: Any, spec_identity: Any) -> None:
    """Record the authenticated artifact occupying a native loader path in this process."""
    import os

    with _process_so_identity_lock:
        _process_so_identity[os.path.abspath(os.fspath(so_path))] = str(spec_identity)


def _native_mpi_flags() -> list:
    """Compile flags so the production DSL loader uses comm.hpp's REAL MPI seam (ADC-319).

    The loader inlines the runtime templates (System / AmrSystem coupler), which call pops::n_ranks() /
    my_rank() from comm.hpp to lay out the distributed grid (DistributionMapping over n_ranks()).
    Compiled WITHOUT POPS_HAS_MPI while _pops is built WITH MPI, comm.hpp falls back to its SERIAL stubs
    (n_ranks()=1, my_rank()=0): any distributed layout built INSIDE the loader then collapses to a
    single owner on EVERY rank -- e.g. AmrSystem(distribute_coarse=True) replicates the coarse
    transport on all ranks (no MPI strong-scaling, ADC-319). We compile WITH -DPOPS_HAS_MPI + the SAME
    MPI include dir as _pops (baked as __mpi_include__) and leave the MPI symbols UNDEFINED, resolved at
    load time against the libmpi already loaded by _pops / mpi4py (RTLD_GLOBAL) -- no 2nd libmpi linked,
    exactly like the Kokkos runtime. Empty (no flag) when _pops is a serial build (__has_mpi__ False),
    so the serial loader path stays bit-identical."""
    mod = _pops_module()
    if mod is None or not getattr(mod, "__has_mpi__", False):
        return []
    flags = ["-DPOPS_HAS_MPI"]
    inc = getattr(mod, "__mpi_include__", "") or ""
    for d in inc.split("|"):  # CMake bakes the include dirs joined by '|' (paths may contain ';')
        if d:
            flags += ["-I", d]
    return flags
