"""Type-only contract for the Program authoring mixins (ADC-628, static analysis only).

The concrete :class:`pops.time.program.Program` assembles its behaviour from topical mixins
(``_ProgramCore`` / ``_ProgramCall`` / ``_ProgramLocal`` / ``_ProgramSolve`` /
``_ProgramAuthoring`` / ``_ProgramPasses`` / ``_ProgramInspect``). Each mixin reads instance
attributes and sibling methods that live on the composed class, not on the mixin itself, so a
static checker cannot resolve them from the mixin in isolation.

This module declares that shared surface ONCE. Each mixin lists :class:`_ProgramBase` as a
``TYPE_CHECKING``-only base; at runtime the guard is false and the base collapses to ``object``,
so the class layout, the MRO and every runtime behaviour are unchanged (the contract is never
imported, instantiated or introspected outside a type checker). The bodies are ``...`` stubs:
they describe shapes, never behaviour.
"""
from __future__ import annotations

from typing import Any


class _ProgramBase:
    """The :class:`pops.time.program.Program` instance surface the authoring mixins share.

    The attributes are created by ``Program.__init__``; the methods are defined across the sibling
    authoring mixins. Declared here so each mixin type-checks against the composed instance without
    a runtime base change. Also carries the class-level constant tables of ``_ProgramConstants``.
    """

    # --- instance attributes (Program.__init__) ---
    name: str
    dt: Any
    _values: list
    _next_id: int
    _commits: dict
    _recording: list
    _histories: dict
    _dt_bound: Any
    _registry: Any
    _capture_source: bool
    _coupled_scratch: dict
    _frozen: bool

    # --- class-level constant tables (_ProgramConstants) ---
    _RESIDUAL_LOCAL_OPS: Any
    _KRYLOV_METHODS: Any
    _GMRES_RESTART_DEFAULT: Any
    _OPERATOR_KINDS: Any
    _CELL_CMPS: dict
    _REMOVABLE_OPS: Any
    _SUBBLOCK_OPS: Any
    _PURE_OPS: Any
    _STATE_BARRIER_OPS: Any
    _OPTIMIZE_PASSES: Any
    _SCRATCH_OPS: Any
    _PERCELL_KERNEL_OPS: Any
    _HEAVY_KERNEL_OPS: Any
    _GPU_MAX_SMALL_KERNELS: int
    _GPU_MAX_SCRATCHES: int
    _GPU_MAX_TRAFFIC_FIELDS: int

    # The composed Program is constructed as ``type(self)(self.name)`` inside ``_rebuild``; the stub
    # lets the checker resolve that call. Never runs (contract is TYPE_CHECKING-only).
    def __init__(self, name: Any) -> None: ...

    # --- node construction / core builder (_ProgramCore) ---
    def _new(self, vtype: Any, op: Any, inputs: Any, attrs: Any, name: Any, block: Any) -> Any: ...
    def state(self, arg: Any = None, space: Any = None, *, block: Any = None) -> Any: ...
    def solve_fields(self, name: Any = None, state: Any = None, field: Any = None) -> Any: ...
    def solve_fields_from_blocks(self, states: Any, name: Any = None) -> Any: ...
    def rhs(self, name: Any = None, state: Any = None, fields: Any = None, *,
            terms: Any = None, **legacy: Any) -> Any: ...
    def _rhs_legacy(self, name: Any = None, state: Any = None, fields: Any = None,
                    flux: Any = True, sources: Any = None, fluxes: Any = None) -> Any: ...
    def linear_combine(self, name: Any = None, expr: Any = None) -> Any: ...
    def source(self, name: Any, state: Any = None, fields: Any = None) -> Any: ...
    def _check_operator_state(self, l_value: Any, state_value: Any, where: Any) -> Any: ...
    def apply(self, operator: Any = None, state: Any = None, fields: Any = None,
              name: Any = None) -> Any: ...
    def _apply(self, operator: Any = None, state: Any = None, fields: Any = None,
               name: Any = None) -> Any: ...

    # --- typed operator-call lowering (_ProgramCall) ---
    def call(self, operator: Any, *args: Any, name: Any = None, schedule: Any = None) -> Any: ...
    def _call(self, operator: Any, *args: Any, name: Any = None, schedule: Any = None) -> Any: ...
    def _operator_call_name(self, operator: Any) -> Any: ...
    def _validate_schedule(self, op: Any, schedule: Any) -> Any: ...
    def _lower_call(self, op: Any, operator_name: Any, args: Any, name: Any) -> Any: ...
    def _lower_coupled_rate(self, op: Any, operator_name: Any, args: Any, name: Any) -> Any: ...
    def _check_call_args(self, op: Any, args: Any) -> Any: ...

    # --- local / matrix-free ops (_ProgramLocal) ---
    def solve_local_linear(self, name: Any = None, operator: Any = None, rhs: Any = None,
                           fields: Any = None) -> Any: ...
    def _linear_source_name(self, operator: Any, where: Any) -> Any: ...
    def _linear_source(self, name: Any) -> Any: ...

    # --- dumps / control flow / reductions (_ProgramAuthoring) ---
    def project(self, name: Any = None, state: Any = None, projection: Any = "block") -> Any: ...
    def cell_compare(self, field: Any, value: Any, cmp: Any, name: Any = None) -> Any: ...
    def _ncomp(self, value: Any) -> Any: ...
    def _record(self, fn: Any, x: Any) -> Any: ...
    def _compare(self, lhs: Any, rhs: Any, cmp: Any) -> Any: ...
    def _scalar_binop(self, a: Any, b: Any, fn: Any) -> Any: ...
    def record_scalar(self, name: Any, value: Any) -> Any: ...

    # --- solve / commit / board sugar (_ProgramSolve) ---
    def solve_linear(self, name: Any = None, operator: Any = None, rhs: Any = None,
                     initial_guess: Any = None, method: Any = None, preconditioner: Any = None,
                     tol: Any = 1e-8, max_iter: Any = None, restart: Any = None) -> Any: ...
    def history(self, name: Any, lag: Any = 1) -> Any: ...
    def store_history(self, name: Any, value: Any) -> Any: ...
    def commit(self, block: Any, state: Any = None) -> Any: ...
    def define(self, name: Any, value: Any = None) -> Any: ...
    def record(self, name: Any, value: Any) -> Any: ...

    # --- passes / serialization / inspection (_ProgramPasses / _ProgramInspect) ---
    def _subblock_value_refs(self, v: Any) -> Any: ...
    def _serialize_node(self, v: Any) -> Any: ...
    def _cse_key(self, v: Any, canon: Any) -> Any: ...
    def _live_value_ids(self) -> Any: ...
    def _rebuild(self, keep: Any, alias: Any = None) -> Any: ...
    def _serialize(self) -> Any: ...
    def _ir_hash(self) -> Any: ...
    def _block_indices(self) -> Any: ...
    def _validate_block(self, block: Any, outer_seen: Any) -> Any: ...
    def eliminate_dead_nodes(self) -> Any: ...
    def eliminate_common_subexpressions(self) -> Any: ...
    def eliminate_redundant_field_solves(self) -> Any: ...
    def scratch_liveness(self) -> Any: ...
    def buffer_reuse_report(self) -> Any: ...
    def estimate(self) -> Any: ...
    def gpu_detectors(self) -> Any: ...
