"""Generated by scripts/generate_component_catalog.py; DO NOT EDIT."""
from __future__ import annotations

COMPONENT_CATALOG_SCHEMA_VERSION = 1
COMPONENT_MANIFEST_SCHEMA_VERSION = 2
COMPONENT_CATALOG_SHA256 = 'dfb04cd60f0523d305063096d60b90e00f2a298f8cd4da7a55bc6d7997c5e57e'
COMPONENT_CATALOG_SEMANTIC_SHA256 = '2655ee5697755f565c40d442de74d8be9e41948dae612b7e35a6c7741204a8f1'
COMPONENT_INTERFACE_SPECS = ({'name': 'requirement', 'method': 'requirements', 'required_args': 0},
 {'name': 'lowering', 'method': 'lower', 'required_args': 1},
 {'name': 'stencil', 'method': 'stencil', 'required_args': 0},
 {'name': 'stability', 'method': 'stability', 'required_args': 0},
 {'name': 'provider', 'method': 'providers', 'required_args': 0},
 {'name': 'effects', 'method': 'effects', 'required_args': 0},
 {'name': 'restart', 'method': 'restart', 'required_args': 0},
 {'name': 'report', 'method': 'report', 'required_args': 0},
 {'name': 'fallible_evaluation', 'method': 'evaluate', 'required_args': 1},
 {'name': 'format', 'method': 'format', 'required_args': 1})
COMPONENT_MANIFEST_SEMANTIC_FIELDS = ('schema_version', 'uri', 'component_type', 'version', 'facets', 'signature', 'reads', 'writes', 'parameters', 'interfaces', 'requirements', 'capabilities', 'effects', 'layouts', 'clocks', 'target', 'determinism', 'restart', 'precision', 'conservation', 'entry_points')
COMPONENT_MANIFEST_TOP_LEVEL_FIELDS = ('schema_version', 'uri', 'component_type', 'version', 'facets', 'signature', 'reads', 'writes', 'parameters', 'interfaces', 'requirements', 'capabilities', 'effects', 'layouts', 'clocks', 'target', 'determinism', 'restart', 'precision', 'conservation', 'entry_points', 'extensions', 'digests')
COMPONENT_TARGET_FIELDS = ('variants',)
COMPONENT_DIGEST_FIELDS = ('semantic', 'manifest')
COMPONENT_EXTENSION_KINDS = ('documentary', 'semantic')

__all__ = [name for name in globals() if name.startswith('COMPONENT_')]
