"""Generated by scripts/generate_component_catalog.py; DO NOT EDIT."""
from __future__ import annotations

COMPONENT_CATALOG_SCHEMA_VERSION = 2
COMPONENT_MANIFEST_SCHEMA_VERSION = 2
COMPONENT_CATALOG_SHA256 = '06e90f38d927e8543e9020d9b2ce1a4f6722630d5c65f347cc9a175cc31f7746'
COMPONENT_CATALOG_SEMANTIC_SHA256 = '27ac54a69188657111717e78b90d2b75c06fdb971ed6b70e96fe68be5de78ad2'
COMPONENT_INTERFACE_SPECS = ({'name': 'requirement', 'method': 'requirements', 'required_args': 0},
 {'name': 'lowering', 'method': 'lower', 'required_args': 1},
 {'name': 'stencil', 'method': 'stencil', 'required_args': 0},
 {'name': 'stability', 'method': 'stability', 'required_args': 0},
 {'name': 'provider', 'method': 'providers', 'required_args': 0},
 {'name': 'effects', 'method': 'effects', 'required_args': 0},
 {'name': 'restart', 'method': 'restart', 'required_args': 0},
 {'name': 'report', 'method': 'report', 'required_args': 0},
 {'name': 'fallible_evaluation', 'method': 'evaluate', 'required_args': 1},
 {'name': 'format', 'method': 'format', 'required_args': 1})
COMPONENT_MANIFEST_SEMANTIC_FIELDS = ('schema_version', 'uri', 'component_type', 'version', 'facets', 'signature', 'reads', 'writes', 'parameters', 'interfaces', 'requirements', 'capabilities', 'effects', 'layouts', 'clocks', 'target', 'determinism', 'restart', 'precision', 'conservation', 'entry_points')
COMPONENT_MANIFEST_TOP_LEVEL_FIELDS = ('schema_version', 'uri', 'component_type', 'version', 'facets', 'signature', 'reads', 'writes', 'parameters', 'interfaces', 'requirements', 'capabilities', 'effects', 'layouts', 'clocks', 'target', 'determinism', 'restart', 'precision', 'conservation', 'entry_points', 'extensions', 'digests')
COMPONENT_TARGET_FIELDS = ('variants',)
COMPONENT_DIGEST_FIELDS = ('semantic', 'manifest')
COMPONENT_EXTENSION_KINDS = ('documentary', 'semantic')

__all__ = [name for name in globals() if name.startswith('COMPONENT_')]
