#!/usr/bin/env python3
"""Generate the Python/C++ release contract from versioned sources.

``project(VERSION)`` remains the single package-version source. The JSON file owns the
independently evolving API/IR/normalization/registry/ABI/checkpoint revisions and the exact
tested platform matrix. Checked-in products keep source imports and header consumers generator-free;
``--check`` is the release drift gate.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import pprint
import re
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "schemas" / "release_contract.v1.json"
CMAKE = ROOT / "CMakeLists.txt"
PYTHON = ROOT / "python" / "pops" / "_generated_release_contract.py"
CPP = ROOT / "include" / "pops" / "runtime" / "config" / "generated_release_contract.hpp"

_VERSION_RE = re.compile(r"(?m)^\s*VERSION\s+(\d+\.\d+\.\d+)\b")
_VERSION_FIELDS = (
    "release_contract_schema_version",
    "public_api_version",
    "semantic_ir_version",
    "normalization_version",
    "component_catalog_schema_version",
    "component_manifest_schema_version",
    "component_registry_version",
    "capability_vocabulary_version",
    "component_interface_abi_version",
    "native_abi_version",
    "checkpoint_envelope_schema_version",
    "uniform_checkpoint_payload_version",
    "amr_checkpoint_payload_version",
)


class ContractError(ValueError):
    pass


def _package_version() -> str:
    matches = _VERSION_RE.findall(CMAKE.read_text(encoding="utf-8"))
    if len(matches) != 1:
        raise ContractError("CMakeLists.txt must contain exactly one project VERSION x.y.z")
    return matches[0]


def _canonical(data: Any) -> bytes:
    return json.dumps(data, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=True).encode("utf-8")


def _load() -> tuple[dict[str, Any], str, str]:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    expected = set(_VERSION_FIELDS) | {"supported_matrix"}
    if not isinstance(data, dict) or set(data) != expected:
        raise ContractError("release contract fields must be exactly %s" % sorted(expected))
    for name in _VERSION_FIELDS:
        value = data[name]
        if type(value) is not int or value < 1:
            raise ContractError("%s must be an integer >= 1" % name)
    matrix = data["supported_matrix"]
    if not isinstance(matrix, dict) or set(matrix) != {
        "language", "kokkos", "distributed", "source_builds", "wheels", "not_promised",
    }:
        raise ContractError("supported_matrix is incomplete or contains unknown fields")
    if not matrix["source_builds"] or not matrix["wheels"]:
        raise ContractError("release contract must declare source and wheel lanes")
    package_version = _package_version()
    semantic = {"package_version": package_version, **data}
    digest = hashlib.sha256(_canonical(semantic)).hexdigest()
    return data, package_version, digest


def _python_text(data: dict[str, Any], package_version: str, digest: str) -> str:
    constants = [
        '"""Generated by scripts/generate_release_contract.py; DO NOT EDIT."""',
        "from __future__ import annotations",
        "",
        "from types import MappingProxyType",
        "from typing import Any",
        "",
        "PACKAGE_VERSION = %r" % package_version,
    ]
    for name in _VERSION_FIELDS:
        constants.append("%s = %d" % (name.upper(), data[name]))
    constants.extend([
        "RELEASE_CONTRACT_SHA256 = %r" % digest,
        "_SUPPORTED_MATRIX_DATA = %s" % pprint.pformat(
            data["supported_matrix"], width=96, sort_dicts=True),
        "",
        "def _freeze(value: Any) -> Any:",
        "    if isinstance(value, dict):",
        "        return MappingProxyType({key: _freeze(item) for key, item in value.items()})",
        "    if isinstance(value, list):",
        "        return tuple(_freeze(item) for item in value)",
        "    return value",
        "",
        "SUPPORTED_MATRIX = _freeze(_SUPPORTED_MATRIX_DATA)",
        "del _SUPPORTED_MATRIX_DATA",
        "",
    ])
    return "\n".join(constants)


def _cpp_text(data: dict[str, Any], package_version: str, digest: str) -> str:
    names = {
        "release_contract_schema_version": "kReleaseContractSchemaVersion",
        "public_api_version": "kPublicApiVersion",
        "semantic_ir_version": "kSemanticIrVersion",
        "normalization_version": "kNormalizationVersion",
        "component_catalog_schema_version": "kComponentCatalogSchemaVersion",
        "component_manifest_schema_version": "kReleaseComponentManifestSchemaVersion",
        "component_registry_version": "kComponentRegistryVersion",
        "capability_vocabulary_version": "kReleaseCapabilityVocabularyVersion",
        "component_interface_abi_version": "kComponentInterfaceAbiVersion",
        "native_abi_version": "kReleaseNativeAbiVersion",
        "checkpoint_envelope_schema_version": "kCheckpointEnvelopeSchemaVersion",
        "uniform_checkpoint_payload_version": "kUniformCheckpointPayloadVersion",
        "amr_checkpoint_payload_version": "kAmrCheckpointPayloadVersion",
    }
    lines = [
        "#pragma once",
        "// Generated by scripts/generate_release_contract.py; DO NOT EDIT.",
        "// clang-format off",
        "namespace pops::release_contract {",
        'inline constexpr const char* kPackageVersion = "%s";' % package_version,
    ]
    lines.extend("inline constexpr int %s = %d;" % (names[name], data[name])
                 for name in _VERSION_FIELDS)
    lines.extend([
        'inline constexpr const char* kContractSha256 = "%s";' % digest,
        "}  // namespace pops::release_contract",
        "// clang-format on",
        "",
    ])
    return "\n".join(lines)


def _outputs() -> dict[Path, str]:
    data, package_version, digest = _load()
    return {
        PYTHON: _python_text(data, package_version, digest),
        CPP: _cpp_text(data, package_version, digest),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        outputs = _outputs()
    except (ContractError, json.JSONDecodeError) as exc:
        print("release contract error: %s" % exc, file=sys.stderr)
        return 2
    stale = []
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if stale:
        print("stale generated release contract: %s" % ", ".join(map(str, stale)), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
