"""Generated by scripts/generate_release_contract.py; DO NOT EDIT."""
from __future__ import annotations

from types import MappingProxyType
from typing import Any

PACKAGE_VERSION = '0.3.0'
RELEASE_CONTRACT_SCHEMA_VERSION = 1
PUBLIC_API_VERSION = 1
SEMANTIC_IR_VERSION = 1
NORMALIZATION_VERSION = 1
COMPONENT_CATALOG_SCHEMA_VERSION = 1
COMPONENT_MANIFEST_SCHEMA_VERSION = 2
COMPONENT_REGISTRY_VERSION = 2
CAPABILITY_VOCABULARY_VERSION = 1
NATIVE_ABI_VERSION = 3
CHECKPOINT_ENVELOPE_SCHEMA_VERSION = 1
UNIFORM_CHECKPOINT_PAYLOAD_VERSION = 3
AMR_CHECKPOINT_PAYLOAD_VERSION = 3
RELEASE_CONTRACT_SHA256 = '25ab9573c2060b282fe25c7b8af73f48768bddf7c64616f07bb3a0d5f6d80fa9'
_SUPPORTED_MATRIX_DATA = {'distributed': {'execution_spaces': ['Serial'], 'mpi_implementation': 'OpenMPI'},
 'kokkos': {'execution_spaces': ['Serial', 'OpenMP'], 'version': '4.4.01'},
 'language': {'compiler_families': ['GNU', 'AppleClang'],
              'cpp_standard': 20,
              'python': ['3.12']},
 'not_promised': ['CUDA wheel', 'HIP wheel', 'MPI wheel', 'Windows wheel'],
 'source_builds': [{'arch': 'x86_64', 'backend': 'Kokkos Serial', 'os': 'linux'},
                   {'arch': 'x86_64', 'backend': 'Kokkos OpenMP', 'os': 'linux'},
                   {'arch': 'x86_64', 'backend': 'Kokkos Serial + OpenMPI', 'os': 'linux'},
                   {'arch': 'arm64', 'backend': 'Kokkos Serial', 'os': 'macos'}],
 'wheels': [{'arch': 'arm64', 'backend': 'Kokkos Serial', 'os': 'macos', 'python': 'cp312'}]}

def _freeze(value: Any) -> Any:
    if isinstance(value, dict):
        return MappingProxyType({key: _freeze(item) for key, item in value.items()})
    if isinstance(value, list):
        return tuple(_freeze(item) for item in value)
    return value

SUPPORTED_MATRIX = _freeze(_SUPPORTED_MATRIX_DATA)
del _SUPPORTED_MATRIX_DATA
