"""Generated by scripts/generate_release_contract.py; DO NOT EDIT."""
from __future__ import annotations

from types import MappingProxyType
from typing import Any

PACKAGE_VERSION = '1.0.0'
RELEASE_CONTRACT_SCHEMA_VERSION = 2
PUBLIC_API_VERSION = 1
SEMANTIC_IR_VERSION = 1
NORMALIZATION_VERSION = 1
COMPONENT_CATALOG_SCHEMA_VERSION = 2
COMPONENT_MANIFEST_SCHEMA_VERSION = 2
COMPONENT_REGISTRY_VERSION = 4
CAPABILITY_VOCABULARY_VERSION = 4
COMPONENT_INTERFACE_ABI_VERSION = 1
NATIVE_ABI_VERSION = 3
CHECKPOINT_ENVELOPE_SCHEMA_VERSION = 1
CHECKPOINT_SPATIAL_SCHEMA_VERSION = 1
UNIFORM_CHECKPOINT_PAYLOAD_VERSION = 7
AMR_CHECKPOINT_PAYLOAD_VERSION = 8
COMPONENT_CATALOG_SHA256 = '06e90f38d927e8543e9020d9b2ce1a4f6722630d5c65f347cc9a175cc31f7746'
COMPONENT_CATALOG_SEMANTIC_SHA256 = '27ac54a69188657111717e78b90d2b75c06fdb971ed6b70e96fe68be5de78ad2'
RELEASE_CONTRACT_SHA256 = 'b955b1fb7258111b584e652412fe96801ce7add6af1b531ecce873f853b8ef1b'
_SUPPORTED_MATRIX_DATA = {'distributed': {'execution_spaces': ['Serial'], 'mpi_implementation': 'OpenMPI'},
 'kokkos': {'execution_spaces': ['Serial', 'OpenMP'], 'version': '4.4.01'},
 'language': {'compiler_families': ['GNU', 'AppleClang'],
              'cpp_standard': 20,
              'python': ['3.12']},
 'not_promised': ['CUDA wheel', 'HIP wheel', 'MPI wheel', 'Windows wheel'],
 'source_builds': [{'arch': 'x86_64', 'backend': 'Kokkos Serial', 'os': 'linux'},
                   {'arch': 'x86_64', 'backend': 'Kokkos OpenMP', 'os': 'linux'},
                   {'arch': 'x86_64', 'backend': 'Kokkos Serial + OpenMPI', 'os': 'linux'},
                   {'arch': 'arm64', 'backend': 'Kokkos Serial', 'os': 'macos'}],
 'wheels': [{'arch': 'arm64', 'backend': 'Kokkos Serial', 'os': 'macos', 'python': 'cp312'}]}

def _freeze(value: Any) -> Any:
    if isinstance(value, dict):
        return MappingProxyType({key: _freeze(item) for key, item in value.items()})
    if isinstance(value, list):
        return tuple(_freeze(item) for item in value)
    return value

SUPPORTED_MATRIX = _freeze(_SUPPORTED_MATRIX_DATA)
del _SUPPORTED_MATRIX_DATA
