"""Final field-operator contracts: physics, numerics and materialization stay separate."""

from __future__ import annotations

from .context import (
    Accepted,
    FieldContext,
    FieldInput,
    FieldMaterialization,
    FieldValidity,
    LayoutBinding,
    Provisional,
    RecomputeField,
    UseHeldField,
    UseMaterializedField,
)
from .discretization import (
    CompositeHierarchySolve,
    FieldDiscretization,
    FieldHierarchyPolicy,
    InferHierarchyFromLayout,
    LevelByLevelSolve,
)
from .gauges import FieldGauge, MeanValueGauge, PinnedValueGauge
from .nullspace import (
    ConnectedComponentsManifest,
    ConstantNullspace,
    NullspaceBasis,
    NullspaceBasisVector,
    NullspaceCompatibility,
    RHSCompatibilityEvidence,
)
from .operator import FieldOperator
from .outputs import DerivedField, FieldOutput, GradientOutput
from .poisson import (
    AnisotropicPoissonOperator,
    PoissonOperator,
    ScreenedPoissonOperator,
)
from .policies import (
    FailFieldRead,
    FieldAttemptRejected,
    FieldConsumer,
    FieldFailureAction,
    FieldReadError,
    FieldReadPolicy,
    HoldLastValue,
    RecomputeAtDiagnostic,
    RecomputeAtOutput,
    RecomputeAtTagging,
    RejectFieldAttempt,
)
from .residual import (
    DirichletContribution,
    FieldBoundaryContribution,
    FieldDependencyCoverage,
    FieldResidualContract,
    FieldResidualDependencies,
    FieldRestartContract,
    MixedContribution,
    NeumannContribution,
    PeriodicContribution,
)
from .solve import (
    FieldArtifactUnavailable,
    FieldOperatorDomain,
    FieldSolveCapabilities,
    FieldSolvePlan,
    FieldSolveResolver,
    PreconditionerBinding,
    ResolvedHierarchyPolicy,
    SolveOutcome,
    SolveStatus,
)
from . import aux, bcs, coefficients, gauges, nullspace, outputs, policies, rhs
from .catalog import fields as catalog


__all__ = [
    "Accepted",
    "AnisotropicPoissonOperator",
    "CompositeHierarchySolve",
    "ConnectedComponentsManifest",
    "ConstantNullspace",
    "DerivedField",
    "DirichletContribution",
    "FailFieldRead",
    "FieldAttemptRejected",
    "FieldArtifactUnavailable",
    "FieldBoundaryContribution",
    "FieldConsumer",
    "FieldContext",
    "FieldDiscretization",
    "FieldDependencyCoverage",
    "FieldFailureAction",
    "FieldGauge",
    "FieldHierarchyPolicy",
    "FieldInput",
    "FieldMaterialization",
    "FieldOperator",
    "FieldOperatorDomain",
    "FieldOutput",
    "FieldReadError",
    "FieldReadPolicy",
    "FieldResidualContract",
    "FieldResidualDependencies",
    "FieldRestartContract",
    "FieldSolveCapabilities",
    "FieldSolvePlan",
    "FieldSolveResolver",
    "FieldValidity",
    "GradientOutput",
    "HoldLastValue",
    "InferHierarchyFromLayout",
    "LayoutBinding",
    "LevelByLevelSolve",
    "MeanValueGauge",
    "MixedContribution",
    "NeumannContribution",
    "NullspaceBasis",
    "NullspaceBasisVector",
    "NullspaceCompatibility",
    "PeriodicContribution",
    "PinnedValueGauge",
    "PoissonOperator",
    "Provisional",
    "PreconditionerBinding",
    "RHSCompatibilityEvidence",
    "RecomputeAtDiagnostic",
    "RecomputeAtOutput",
    "RecomputeAtTagging",
    "RecomputeField",
    "RejectFieldAttempt",
    "ResolvedHierarchyPolicy",
    "ScreenedPoissonOperator",
    "SolveOutcome",
    "SolveStatus",
    "UseHeldField",
    "UseMaterializedField",
    "aux",
    "bcs",
    "catalog",
    "coefficients",
    "gauges",
    "nullspace",
    "outputs",
    "policies",
    "rhs",
]
