#pragma once
// Generated by scripts/generate_release_contract.py; DO NOT EDIT.
namespace pops::release_contract {
inline constexpr const char* kPackageVersion = "0.3.0";
inline constexpr int kReleaseContractSchemaVersion = 1;
inline constexpr int kPublicApiVersion = 1;
inline constexpr int kSemanticIrVersion = 1;
inline constexpr int kNormalizationVersion = 1;
inline constexpr int kComponentCatalogSchemaVersion = 1;
inline constexpr int kReleaseComponentManifestSchemaVersion = 2;
inline constexpr int kComponentRegistryVersion = 2;
inline constexpr int kReleaseCapabilityVocabularyVersion = 1;
inline constexpr int kComponentInterfaceAbiVersion = 1;
inline constexpr int kReleaseNativeAbiVersion = 3;
inline constexpr int kCheckpointEnvelopeSchemaVersion = 1;
inline constexpr int kUniformCheckpointPayloadVersion = 3;
inline constexpr int kAmrCheckpointPayloadVersion = 3;
inline constexpr const char* kContractSha256 = "c8acf57707d46195eef9e52a877d9af384493f626151ee5ce9f03a5fce4723fd";
}  // namespace pops::release_contract
