#pragma once

// Generated by scripts/generate_component_catalog.py; DO NOT EDIT.
// The ABI crosses no C++ standard-library or backend-owned type. Hot interfaces are batch calls;
// discovery and symbol resolution happen once during installation, never inside a scientific loop.

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define POPS_COMPONENT_API_SYMBOL_V1 "pops_component_interface_v1"
#define POPS_COMPONENT_CATALOG_SHA256_V1 "6a9e3d473ce9fef2ec84c781a51628247017ca0aba8acd28076318058d211e97"
#define POPS_COMPONENT_PROTOCOL_ABI_V1 1u
#define POPS_COMPONENT_COMMON_ABI_V1 1u

typedef enum PopsNativeInterfaceIdV1 {
  POPS_NATIVE_INTERFACE_NUMERICAL_FLUX_V1 = 0,
  POPS_NATIVE_INTERFACE_GHOST_BOUNDARY_V1 = 1,
  POPS_NATIVE_INTERFACE_FIELD_BOUNDARY_CLOSURE_V1 = 2,
  POPS_NATIVE_INTERFACE_TAGGER_V1 = 3,
  POPS_NATIVE_INTERFACE_CLUSTERING_V1 = 4,
  POPS_NATIVE_INTERFACE_TRANSFER_V1 = 5,
  POPS_NATIVE_INTERFACE_REFLUX_V1 = 6,
  POPS_NATIVE_INTERFACE_FIELD_SOLVER_V1 = 7,
  POPS_NATIVE_INTERFACE_WRITER_V1 = 8,
  POPS_NATIVE_INTERFACE_FIELD_TOPOLOGY_V1 = 9,
} PopsNativeInterfaceIdV1;

typedef enum PopsComponentActionV1 {
  POPS_COMPONENT_CONTINUE_V1 = 0,
  POPS_COMPONENT_RETRY_STEP_V1 = 1,
  POPS_COMPONENT_REJECT_STEP_V1 = 2,
  POPS_COMPONENT_ABORT_RUN_V1 = 3
} PopsComponentActionV1;

typedef struct PopsComponentStatusV1 {
  uint32_t struct_size;
  int32_t code;
  PopsComponentActionV1 action;
  const char* reason;
} PopsComponentStatusV1;

typedef enum PopsMemorySpaceV1 {
  POPS_MEMORY_SPACE_HOST_V1 = 1,
  POPS_MEMORY_SPACE_DEVICE_V1 = 2,
  POPS_MEMORY_SPACE_MANAGED_V1 = 3
} PopsMemorySpaceV1;
typedef enum PopsScalarTypeV1 {
  POPS_SCALAR_FLOAT32_V1 = 1,
  POPS_SCALAR_FLOAT64_V1 = 2
} PopsScalarTypeV1;
typedef enum PopsFieldCenteringV1 {
  POPS_FIELD_CENTERING_CELL_V1 = 1,
  POPS_FIELD_CENTERING_FACE_V1 = 2,
  POPS_FIELD_CENTERING_NODE_V1 = 3,
  POPS_FIELD_CENTERING_EDGE_V1 = 4
} PopsFieldCenteringV1;
typedef enum PopsFieldOwnershipV1 {
  POPS_FIELD_OWNERSHIP_RUNTIME_BORROWED_V1 = 1,
  POPS_FIELD_OWNERSHIP_COMPONENT_BORROWED_V1 = 2,
  POPS_FIELD_OWNERSHIP_COMPONENT_OWNED_V1 = 3
} PopsFieldOwnershipV1;

typedef struct PopsConstFieldViewV1 {
  uint32_t struct_size;
  const void* data;
  int32_t dimension;
  size_t extents[3];
  ptrdiff_t axis_strides[3];
  size_t component_count;
  ptrdiff_t component_stride;
  PopsFieldCenteringV1 centering;
  uint32_t centering_axes;
  size_t ghost_lower[3];
  size_t ghost_upper[3];
  PopsScalarTypeV1 scalar_type;
  PopsMemorySpaceV1 memory_space;
  const char* layout_identity;
  const char* patch_identity;
  PopsFieldOwnershipV1 ownership;
} PopsConstFieldViewV1;

typedef struct PopsFieldViewV1 {
  uint32_t struct_size;
  void* data;
  int32_t dimension;
  size_t extents[3];
  ptrdiff_t axis_strides[3];
  size_t component_count;
  ptrdiff_t component_stride;
  PopsFieldCenteringV1 centering;
  uint32_t centering_axes;
  size_t ghost_lower[3];
  size_t ghost_upper[3];
  PopsScalarTypeV1 scalar_type;
  PopsMemorySpaceV1 memory_space;
  const char* layout_identity;
  const char* patch_identity;
  PopsFieldOwnershipV1 ownership;
} PopsFieldViewV1;

typedef struct PopsConstByteViewV1 {
  uint32_t struct_size;
  const uint8_t* data;
  size_t size;
} PopsConstByteViewV1;

typedef struct PopsByteViewV1 {
  uint32_t struct_size;
  uint8_t* data;
  size_t size;
} PopsByteViewV1;

typedef struct PopsInt32ViewV1 {
  uint32_t struct_size;
  int32_t* data;
  size_t size;
} PopsInt32ViewV1;

typedef struct PopsConstInt32ViewV1 {
  uint32_t struct_size;
  const int32_t* data;
  size_t size;
} PopsConstInt32ViewV1;

typedef struct PopsLogicalTimeV1 {
  uint32_t struct_size;
  const char* clock_identity;
  int64_t tick;
  int32_t level;
  int32_t substep;
  int32_t stage;
  int64_t fraction_numerator;
  int64_t fraction_denominator;
  double dt;
  double physical_time;
} PopsLogicalTimeV1;

typedef enum PopsPrecisionV1 {
  POPS_PRECISION_FLOAT16_V1 = 1,
  POPS_PRECISION_BFLOAT16_V1 = 2,
  POPS_PRECISION_FLOAT32_V1 = 3,
  POPS_PRECISION_FLOAT64_V1 = 4
} PopsPrecisionV1;
typedef struct PopsExecutionContextV1 {
  uint32_t struct_size;
  uint32_t context_version;
  const char* execution_identity;
  PopsMemorySpaceV1 memory_space;
  const char* backend_identity;
  const char* device_identity;
  PopsScalarTypeV1 scalar_type;
  PopsPrecisionV1 storage_precision;
  PopsPrecisionV1 compute_precision;
  PopsPrecisionV1 accumulation_precision;
  PopsPrecisionV1 reduction_precision;
  uint64_t stream_handle;
  const char* stream_identity;
  int64_t communicator_f_handle;
  int64_t communicator_datatype_f_handle;
  const char* communicator_identity;
  const char* communicator_datatype_identity;
} PopsExecutionContextV1;

typedef struct PopsComponentPrepareRequestV1 {
  uint32_t struct_size;
  const char* parameters_json;
  const char* target_json;
  PopsExecutionContextV1 execution;
} PopsComponentPrepareRequestV1;

typedef int32_t (*PopsComponentPrepareFnV1)(
    const PopsComponentPrepareRequestV1*, void**, PopsComponentStatusV1*);
typedef void (*PopsComponentDestroyFnV1)(void*);

typedef struct PopsComponentTableHeaderV1 {
  uint32_t struct_size;
  uint32_t abi_version;
  PopsNativeInterfaceIdV1 interface_id;
  uint32_t interface_version;
  PopsComponentPrepareFnV1 prepare;
  PopsComponentDestroyFnV1 destroy;
} PopsComponentTableHeaderV1;

typedef struct PopsNumericalFluxRequestV1 {
  uint32_t struct_size;
  PopsConstFieldViewV1 left;
  PopsConstFieldViewV1 right;
  PopsConstFieldViewV1 normals;
  const double* face_measures;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsNumericalFluxRequestV1;
typedef struct PopsNumericalFluxResultV1 {
  uint32_t struct_size;
  PopsFieldViewV1 normal_flux;
  double* stability_bounds;
  PopsComponentActionV1* actions;
  PopsComponentStatusV1 status;
} PopsNumericalFluxResultV1;
typedef int32_t (*PopsEvaluateFacesFnV1)(
    void*, const PopsNumericalFluxRequestV1*, PopsNumericalFluxResultV1*);
typedef struct PopsNumericalFluxApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsEvaluateFacesFnV1 evaluate_faces;
} PopsNumericalFluxApiV1;

typedef enum PopsBoundaryRegionKindV1 {
  POPS_BOUNDARY_FACE_V1 = 1,
  POPS_BOUNDARY_EDGE_V1 = 2,
  POPS_BOUNDARY_CORNER_V1 = 3
} PopsBoundaryRegionKindV1;
typedef struct PopsBoundaryRegionV1 {
  uint32_t struct_size;
  PopsBoundaryRegionKindV1 kind;
  int32_t dimension;
  int32_t codimension;
  size_t axis_count;
  const int32_t* axes;
  const int32_t* sides;
  const char* region_identity;
} PopsBoundaryRegionV1;
typedef struct PopsQualifiedConstFieldV1 {
  uint32_t struct_size;
  uint32_t present;
  const char* qualified_id;
  PopsConstFieldViewV1 values;
} PopsQualifiedConstFieldV1;
typedef struct PopsQualifiedFieldV1 {
  uint32_t struct_size;
  const char* qualified_id;
  PopsFieldViewV1 values;
} PopsQualifiedFieldV1;
typedef struct PopsQualifiedScalarV1 {
  uint32_t struct_size;
  const char* qualified_id;
  double value;
} PopsQualifiedScalarV1;
typedef struct PopsGhostBoundaryRequestV1 {
  uint32_t struct_size;
  const char* producer_identity;
  const char* state_identity;
  const char* ghost_identity;
  PopsConstFieldViewV1 interior;
  PopsFieldViewV1 ghosts;
  PopsConstFieldViewV1 coordinates;
  PopsBoundaryRegionV1 region;
  size_t dependency_count;
  const PopsQualifiedConstFieldV1* dependencies;
  size_t parameter_count;
  const PopsQualifiedScalarV1* parameters;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsGhostBoundaryRequestV1;
typedef int32_t (*PopsApplyRegionBatchFnV1)(
    void*, const PopsGhostBoundaryRequestV1*, PopsComponentStatusV1*);
typedef struct PopsGhostBoundaryApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsApplyRegionBatchFnV1 apply_region_batch;
} PopsGhostBoundaryApiV1;

typedef struct PopsFieldBoundaryRequestV1 {
  uint32_t struct_size;
  const char* closure_identity;
  PopsBoundaryRegionV1 region;
  PopsConstFieldViewV1 coordinates;
  size_t state_count;
  const PopsQualifiedConstFieldV1* states;
  size_t direction_count;
  const PopsQualifiedConstFieldV1* directions;
  size_t field_count;
  const PopsQualifiedConstFieldV1* fields;
  size_t parameter_count;
  const PopsQualifiedScalarV1* parameters;
  size_t output_count;
  PopsQualifiedFieldV1* outputs;
  PopsQualifiedConstFieldV1 rate;
  PopsQualifiedConstFieldV1 nonlinear_iterate;
  int32_t level;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsFieldBoundaryRequestV1;
typedef int32_t (*PopsFieldBoundaryEvalFnV1)(
    void*, const PopsFieldBoundaryRequestV1*, PopsComponentStatusV1*);
typedef struct PopsFieldBoundaryClosureApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsFieldBoundaryEvalFnV1 residual;
  PopsFieldBoundaryEvalFnV1 jvp;
} PopsFieldBoundaryClosureApiV1;

typedef struct PopsTaggerRequestV1 {
  uint32_t struct_size;
  PopsConstFieldViewV1 state;
  PopsByteViewV1 tags;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsTaggerRequestV1;
typedef int32_t (*PopsTagBatchFnV1)(void*, const PopsTaggerRequestV1*, PopsComponentStatusV1*);
typedef struct PopsTaggerApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsTagBatchFnV1 tag_batch;
} PopsTaggerApiV1;

typedef struct PopsClusteringRequestV1 {
  uint32_t struct_size;
  PopsConstByteViewV1 tags;
  const int64_t* extents;
  int32_t dimension;
  int64_t* boxes;
  size_t box_capacity;
  size_t* box_count;
  PopsExecutionContextV1 execution;
} PopsClusteringRequestV1;
typedef int32_t (*PopsClusterFnV1)(void*, const PopsClusteringRequestV1*, PopsComponentStatusV1*);
typedef struct PopsClusteringApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsClusterFnV1 cluster;
} PopsClusteringApiV1;

typedef enum PopsTransferOperationV1 {
  POPS_TRANSFER_OPERATION_CONSERVATIVE_CELL_AVERAGE_V1 = 1
} PopsTransferOperationV1;
typedef struct PopsTransferRequestV1 {
  uint32_t struct_size;
  PopsConstFieldViewV1 source;
  PopsFieldViewV1 destination;
  const int32_t* refinement_ratio;
  int32_t dimension;
  PopsTransferOperationV1 operation;
  PopsExecutionContextV1 execution;
} PopsTransferRequestV1;
typedef int32_t (*PopsTransferApplyFnV1)(void*, const PopsTransferRequestV1*, PopsComponentStatusV1*);
typedef struct PopsTransferApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsTransferApplyFnV1 apply;
} PopsTransferApiV1;

typedef struct PopsRefluxRequestV1 {
  uint32_t struct_size;
  PopsConstFieldViewV1 coarse_integrated;
  PopsConstFieldViewV1 fine_integrated;
  PopsFieldViewV1 flux_register;
  PopsExecutionContextV1 execution;
} PopsRefluxRequestV1;
typedef int32_t (*PopsDepositIntegratedFnV1)(
    void*, const PopsRefluxRequestV1*, PopsComponentStatusV1*);
typedef struct PopsRefluxApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsDepositIntegratedFnV1 deposit_integrated;
} PopsRefluxApiV1;

typedef struct PopsFieldSolverRequestV1 {
  uint32_t struct_size;
  PopsConstFieldViewV1 rhs;
  PopsFieldViewV1 solution;
  PopsConstFieldViewV1 coefficients;
  PopsConstByteViewV1 material_mask;
  PopsConstInt32ViewV1 component_labels;
  const char* topology_digest;
  const char* boundary_contract_json;
  double relative_tolerance;
  double absolute_tolerance;
  int32_t max_iterations;
  PopsExecutionContextV1 execution;
} PopsFieldSolverRequestV1;
typedef struct PopsSolveReportV1 {
  uint32_t struct_size;
  int32_t converged;
  int32_t iterations;
  double initial_residual;
  double final_residual;
  PopsComponentStatusV1 status;
} PopsSolveReportV1;
typedef int32_t (*PopsFieldSolveFnV1)(
    void*, const PopsFieldSolverRequestV1*, PopsSolveReportV1*);
typedef struct PopsFieldSolverApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsFieldSolveFnV1 solve;
} PopsFieldSolverApiV1;

typedef struct PopsWriterBoxV1 {
  uint32_t struct_size;
  int32_t dimension;
  const int64_t* lower;
  const int64_t* upper;
} PopsWriterBoxV1;
typedef struct PopsWriterGeometryV1 {
  uint32_t struct_size;
  const char* layout_identity;
  const char* layout_kind;
  int32_t level;
  int32_t dimension;
  const double* origin;
  const double* spacing;
  const size_t* cell_shape;
  size_t box_count;
  const PopsWriterBoxV1* boxes;
  PopsConstByteViewV1 valid_cells;
  PopsConstByteViewV1 coverage;
  PopsConstFieldViewV1 cell_volumes;
} PopsWriterGeometryV1;
typedef struct PopsWriterPieceV1 {
  uint32_t struct_size;
  int32_t dimension;
  const int64_t* lower;
  const int64_t* upper;
  PopsConstFieldViewV1 values;
} PopsWriterPieceV1;
typedef struct PopsWriterFieldV1 {
  uint32_t struct_size;
  const char* field_identity;
  const char* reference_id;
  const char* component_manifest_identity;
  const char* layout_identity;
  int32_t level;
  const char* state_id;
  const char* centering;
  const char* units;
  size_t component_name_count;
  const char* const* component_names;
  int32_t dimension;
  const size_t* global_shape;
  size_t piece_count;
  const PopsWriterPieceV1* pieces;
} PopsWriterFieldV1;
typedef struct PopsWriterDiagnosticV1 {
  uint32_t struct_size;
  const char* diagnostic_identity;
  const char* reference_id;
  const char* component_manifest_identity;
  const char* layout_identity;
  int32_t level;
  const char* state_id;
  const char* reduction;
  double value;
  const char* units;
  const char* terms_json;
} PopsWriterDiagnosticV1;
typedef struct PopsWriterRequestV1 {
  uint32_t struct_size;
  size_t geometry_count;
  const PopsWriterGeometryV1* geometries;
  size_t field_count;
  const PopsWriterFieldV1* fields;
  size_t diagnostic_count;
  const PopsWriterDiagnosticV1* diagnostics;
  const char* metadata_json;
  const char* selection_identity;
  const char* temporary_path;
  const char* published_path;
  const char* snapshot_identity;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsWriterRequestV1;
typedef struct PopsWriterReceiptV1 {
  uint32_t struct_size;
  uint64_t bytes_written;
  const char* content_digest;
  PopsComponentStatusV1 status;
} PopsWriterReceiptV1;
typedef int32_t (*PopsWriterVerifyFnV1)(void*, const PopsWriterRequestV1*, PopsWriterReceiptV1*);
typedef int32_t (*PopsWriterPublishFnV1)(void*, const PopsWriterRequestV1*, PopsWriterReceiptV1*);
typedef void (*PopsWriterCleanupFnV1)(void*, const PopsWriterRequestV1*);
typedef struct PopsWriterApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsWriterVerifyFnV1 verify;
  PopsWriterPublishFnV1 publish;
  PopsWriterCleanupFnV1 discard;
  PopsWriterCleanupFnV1 rollback;
} PopsWriterApiV1;

typedef struct PopsFieldTopologyRequestV1 {
  uint32_t struct_size;
  PopsConstFieldViewV1 geometry;
  PopsByteViewV1 material_mask;
  PopsInt32ViewV1 component_labels;
  PopsExecutionContextV1 execution;
} PopsFieldTopologyRequestV1;
typedef struct PopsTopologyLabelV1 {
  int32_t id;
  const char* label;
  const char* provenance;
} PopsTopologyLabelV1;
typedef struct PopsFieldTopologyResultV1 {
  uint32_t struct_size;
  size_t label_count;
  const PopsTopologyLabelV1* labels;
  const char* provenance;
  const char* topology_digest;
  PopsComponentStatusV1 status;
} PopsFieldTopologyResultV1;
typedef int32_t (*PopsPrepareTopologyFnV1)(
    void*, const PopsFieldTopologyRequestV1*, PopsFieldTopologyResultV1*);
typedef struct PopsFieldTopologyApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsPrepareTopologyFnV1 prepare_topology;
} PopsFieldTopologyApiV1;

typedef struct PopsComponentInterfaceEntryV1 {
  PopsNativeInterfaceIdV1 interface_id;
  uint32_t interface_version;
  uint32_t table_size;
  const void* table;
} PopsComponentInterfaceEntryV1;

typedef struct PopsComponentApiV1 {
  uint32_t struct_size;
  uint32_t protocol_abi;
  const char* catalog_sha256;
  const char* component_id;
  const char* semantic_identity;
  const char* manifest_identity;
  size_t interface_count;
  const PopsComponentInterfaceEntryV1* interfaces;
} PopsComponentApiV1;

typedef const PopsComponentApiV1* (*PopsComponentApiGetterV1)(void);

#ifdef __cplusplus
}  // extern "C"

namespace pops::component {
inline constexpr size_t generated_native_interface_table_size(
    PopsNativeInterfaceIdV1 id) noexcept {
  switch (id) {
    case POPS_NATIVE_INTERFACE_NUMERICAL_FLUX_V1: return sizeof(PopsNumericalFluxApiV1);
    case POPS_NATIVE_INTERFACE_GHOST_BOUNDARY_V1: return sizeof(PopsGhostBoundaryApiV1);
    case POPS_NATIVE_INTERFACE_FIELD_BOUNDARY_CLOSURE_V1: return sizeof(PopsFieldBoundaryClosureApiV1);
    case POPS_NATIVE_INTERFACE_TAGGER_V1: return sizeof(PopsTaggerApiV1);
    case POPS_NATIVE_INTERFACE_CLUSTERING_V1: return sizeof(PopsClusteringApiV1);
    case POPS_NATIVE_INTERFACE_TRANSFER_V1: return sizeof(PopsTransferApiV1);
    case POPS_NATIVE_INTERFACE_REFLUX_V1: return sizeof(PopsRefluxApiV1);
    case POPS_NATIVE_INTERFACE_FIELD_SOLVER_V1: return sizeof(PopsFieldSolverApiV1);
    case POPS_NATIVE_INTERFACE_WRITER_V1: return sizeof(PopsWriterApiV1);
    case POPS_NATIVE_INTERFACE_FIELD_TOPOLOGY_V1: return sizeof(PopsFieldTopologyApiV1);
  }
  return 0;
}
inline constexpr const char* generated_native_interface_table_name(
    PopsNativeInterfaceIdV1 id) noexcept {
  switch (id) {
    case POPS_NATIVE_INTERFACE_NUMERICAL_FLUX_V1: return "PopsNumericalFluxApiV1";
    case POPS_NATIVE_INTERFACE_GHOST_BOUNDARY_V1: return "PopsGhostBoundaryApiV1";
    case POPS_NATIVE_INTERFACE_FIELD_BOUNDARY_CLOSURE_V1: return "PopsFieldBoundaryClosureApiV1";
    case POPS_NATIVE_INTERFACE_TAGGER_V1: return "PopsTaggerApiV1";
    case POPS_NATIVE_INTERFACE_CLUSTERING_V1: return "PopsClusteringApiV1";
    case POPS_NATIVE_INTERFACE_TRANSFER_V1: return "PopsTransferApiV1";
    case POPS_NATIVE_INTERFACE_REFLUX_V1: return "PopsRefluxApiV1";
    case POPS_NATIVE_INTERFACE_FIELD_SOLVER_V1: return "PopsFieldSolverApiV1";
    case POPS_NATIVE_INTERFACE_WRITER_V1: return "PopsWriterApiV1";
    case POPS_NATIVE_INTERFACE_FIELD_TOPOLOGY_V1: return "PopsFieldTopologyApiV1";
  }
  return nullptr;
}
}  // namespace pops::component
#endif
