#pragma once

// Generated by scripts/generate_component_catalog.py; DO NOT EDIT.
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace pops {

struct RouteInfo {
  int index;
  const char* token;
  const char* native_entry;
  const char* requirements;
  const char* limitations;
};

enum class ComponentInterfaceId : std::uint8_t {
  kRequirement = 0,
  kLowering = 1,
  kStencil = 2,
  kStability = 3,
  kProvider = 4,
  kEffects = 5,
  kRestart = 6,
  kReport = 7,
  kFallibleEvaluation = 8,
  kFormat = 9,
};
struct ComponentInterfaceInfo {
  ComponentInterfaceId id; const char* name; const char* method; int required_args;
};
inline constexpr ComponentInterfaceInfo kComponentInterfaces[] = {
  {ComponentInterfaceId::kRequirement, "requirement", "requirements", 0},
  {ComponentInterfaceId::kLowering, "lowering", "lower", 1},
  {ComponentInterfaceId::kStencil, "stencil", "stencil", 0},
  {ComponentInterfaceId::kStability, "stability", "stability", 0},
  {ComponentInterfaceId::kProvider, "provider", "providers", 0},
  {ComponentInterfaceId::kEffects, "effects", "effects", 0},
  {ComponentInterfaceId::kRestart, "restart", "restart", 0},
  {ComponentInterfaceId::kReport, "report", "report", 0},
  {ComponentInterfaceId::kFallibleEvaluation, "fallible_evaluation", "evaluate", 1},
  {ComponentInterfaceId::kFormat, "format", "format", 1},
};
constexpr const ComponentInterfaceInfo* find_component_interface(std::string_view name) {
  for (const auto& interface : kComponentInterfaces)
    if (name == interface.name)
      return &interface;
  return nullptr;
}

enum class RouteFamily : std::uint8_t {
  kRiemann = 0,
  kLimiter = 1,
  kRecon = 2,
  kTime = 3,
  kFieldSolver = 4,
  kPoissonBc = 5,
  kLayout = 6,
  kTransport = 7,
  kSource = 8,
  kElliptic = 9,
  kPoissonRhs = 10,
  kWall = 11,
};

constexpr const char* route_family_name(RouteFamily family) {
  switch (family) {
    case RouteFamily::kRiemann: return "riemann";
    case RouteFamily::kLimiter: return "limiter";
    case RouteFamily::kRecon: return "recon";
    case RouteFamily::kTime: return "time";
    case RouteFamily::kFieldSolver: return "field_solver";
    case RouteFamily::kPoissonBc: return "poisson_bc";
    case RouteFamily::kLayout: return "layout";
    case RouteFamily::kTransport: return "transport";
    case RouteFamily::kSource: return "source";
    case RouteFamily::kElliptic: return "elliptic";
    case RouteFamily::kPoissonRhs: return "poisson_rhs";
    case RouteFamily::kWall: return "wall";
  }
  return "unknown";
}

enum class RiemannRouteId : int {
  kRusanov = 0,
  kHll = 1,
  kHllc = 2,
  kRoe = 3,
  kEulerHllc = 4,
  kEulerRoe = 5,
};
inline constexpr RouteInfo kRiemannRoutes[] = {
  {0, "rusanov", "pops::RusanovFlux", "physical_flux,provider_pack,stability_bound", ""},
  {1, "hll", "pops::HLLFlux", "physical_flux,provider_pack,stability_bound,wave_speeds", ""},
  {2, "hllc", "pops::HLLCFlux", "physical_flux,provider_pack,stability_bound,pressure,wave_speeds,contact_speed,hllc_star_state", "polar geometry not wired; generic-only (ADC-590), requires HasHLLCStructure"},
  {3, "roe", "pops::RoeFlux", "physical_flux,provider_pack,stability_bound,roe_dissipation", "polar geometry not wired; generic-only (ADC-590), requires HasRoeDissipation"},
  {4, "euler_hllc", "pops::EulerHLLCFlux2D", "physical_flux,provider_pack,stability_bound,pressure,euler_2d_layout", "4-variable canonical Euler (rho,mx,my,E) only; explicit route, never a fallback; polar not wired"},
  {5, "euler_roe", "pops::EulerRoeFlux2D", "physical_flux,provider_pack,stability_bound,pressure,euler_2d_layout", "4-variable canonical Euler (rho,mx,my,E) only; explicit route, never a fallback; polar not wired"},
};
inline constexpr const char* kRiemannRouteTokensCsv = "rusanov|hll|hllc|roe|euler_hllc|euler_roe";

enum class LimiterRouteId : int {
  kNone = 0,
  kMinmod = 1,
  kVanLeer = 2,
  kWeno5 = 3,
};
inline constexpr RouteInfo kLimiterRoutes[] = {
  {0, "none", "pops::NoSlope", "", ""},
  {1, "minmod", "pops::Minmod", "", ""},
  {2, "vanleer", "pops::VanLeer", "", ""},
  {3, "weno5", "pops::Weno5Z", "3-cell halo", ""},
};
inline constexpr const char* kLimiterRouteTokensCsv = "none|minmod|vanleer|weno5";

enum class ReconRouteId : int {
  kConservative = 0,
  kPrimitive = 1,
};
inline constexpr RouteInfo kReconRoutes[] = {
  {0, "conservative", "pops::make_block(recon_prim=false)", "", ""},
  {1, "primitive", "pops::make_block(recon_prim=true)", "primitive_vars", "requires a model exposing primitive variables"},
};
inline constexpr const char* kReconRouteTokensCsv = "conservative|primitive";

enum class TimeRouteId : int {
  kExplicitSsprk2 = 0,
  kSsprk3 = 1,
  kForwardEuler = 2,
  kImex = 3,
  kImexRkArs222 = 4,
};
inline constexpr RouteInfo kTimeRoutes[] = {
  {0, "explicit", "pops::SSPRK2", "", ""},
  {1, "ssprk3", "pops::SSPRK3", "", ""},
  {2, "euler", "pops::ForwardEuler", "", "validation use, never default"},
  {3, "imex", "pops::AdvanceImex", "implicit source term", ""},
  {4, "imexrk_ars222", "pops::ImexRkArs222", "implicit source term", "composed native add_block only (.so ABIs do not carry the RK tableau)"},
};
inline constexpr const char* kTimeRouteTokensCsv = "explicit|ssprk3|euler|imex|imexrk_ars222";

enum class FieldSolverRouteId : int {
  kGeometricMg = 0,
  kFft = 1,
  kFftSpectral = 2,
  kPolar = 3,
};
inline constexpr RouteInfo kFieldSolverRoutes[] = {
  {0, "geometric_mg", "pops::GeometricMG", "", ""},
  {1, "fft", "pops::PoissonFFTSolver", "periodic bc,constant coefficient", "walls / variable epsilon not wired; non power-of-two grid falls back to O(n^2) DFT"},
  {2, "fft_spectral", "pops::PoissonFFTSolver(spectral)", "periodic bc,constant coefficient", "walls / variable epsilon not wired; continuous symbol -(kx^2+ky^2)"},
  {3, "polar", "pops::PolarPoissonSolver", "polar geometry", "annular polar only (r_min > 0)"},
};
inline constexpr const char* kFieldSolverRouteTokensCsv = "geometric_mg|fft|fft_spectral|polar";

enum class PoissonBcRouteId : int {
  kAuto = 0,
  kPeriodic = 1,
  kDirichlet = 2,
  kNeumann = 3,
};
inline constexpr RouteInfo kPoissonBcRoutes[] = {
  {0, "auto", "resolved from the wall/periodic system config", "", ""},
  {1, "periodic", "pops::fill_boundary(periodic)", "", ""},
  {2, "dirichlet", "pops::PhysicalBc(dirichlet)", "", ""},
  {3, "neumann", "pops::PhysicalBc(neumann)", "", ""},
};
inline constexpr const char* kPoissonBcRouteTokensCsv = "auto|periodic|dirichlet|neumann";

enum class LayoutRouteId : int {
  kUniform = 0,
  kAmr = 1,
};
inline constexpr RouteInfo kLayoutRoutes[] = {
  {0, "uniform", "pops::System", "", ""},
  {1, "amr", "pops::AmrSystem", "", "refinement ratio 2 (kAmrRefRatio); fft field solver not wired"},
};
inline constexpr const char* kLayoutRouteTokensCsv = "uniform|amr";

enum class TransportRouteId : int {
  kExb = 0,
  kCompressible = 1,
  kIsothermal = 2,
};
inline constexpr RouteInfo kTransportRoutes[] = {
  {0, "exb", "pops::ExBVelocity", "", "scalar (1 var); no fluid source"},
  {1, "compressible", "pops::CompressibleFlux", "", "polar geometry not wired"},
  {2, "isothermal", "pops::IsothermalFlux", "", ""},
};
inline constexpr const char* kTransportRouteTokensCsv = "exb|compressible|isothermal";

enum class SourceRouteId : int {
  kNone = 0,
  kPotential = 1,
  kGravity = 2,
  kMagneticLorentz = 3,
  kPotentialMagneticLorentz = 4,
};
inline constexpr RouteInfo kSourceRoutes[] = {
  {0, "none", "pops::NoSource", "", ""},
  {1, "potential", "pops::PotentialForce", "fluid transport (>= 3 vars)", ""},
  {2, "gravity", "pops::GravityForce", "fluid transport (>= 3 vars)", ""},
  {3, "magnetic", "pops::MagneticLorentzForce", "fluid transport (>= 3 vars),aux B_z channel", "explicit regime (stiff regime -> condensed Schur stage)"},
  {4, "potential_magnetic", "pops::CompositeSource<PotentialForce, MagneticLorentzForce>", "fluid transport (>= 3 vars),aux B_z channel", ""},
};
inline constexpr const char* kSourceRouteTokensCsv = "none|potential|gravity|magnetic|potential_magnetic";

enum class EllipticRouteId : int {
  kCharge = 0,
  kBackground = 1,
  kGravity = 2,
};
inline constexpr RouteInfo kEllipticRoutes[] = {
  {0, "charge", "pops::ChargeDensity", "", ""},
  {1, "background", "pops::BackgroundDensity", "", ""},
  {2, "gravity", "pops::GravityCoupling", "", ""},
};
inline constexpr const char* kEllipticRouteTokensCsv = "charge|background|gravity";

enum class PoissonRhsRouteId : int {
  kChargeDensity = 0,
  kComposite = 1,
};
inline constexpr RouteInfo kPoissonRhsRoutes[] = {
  {0, "charge_density", "per-block ChargeDensity bricks summed", "", "alias of composite when every block carries a charge density (bit-identical)"},
  {1, "composite", "per-block elliptic bricks summed", "", ""},
};
inline constexpr const char* kPoissonRhsRouteTokensCsv = "charge_density|composite";

enum class WallRouteId : int {
  kNone = 0,
  kCircle = 1,
};
inline constexpr RouteInfo kWallRoutes[] = {
  {0, "none", "no wall (fully periodic/physical domain)", "", ""},
  {1, "circle", "pops::make_wall_predicate(circle)", "wall_radius > 0", ""},
};
inline constexpr const char* kWallRouteTokensCsv = "none|circle";

struct LimiterTag { const char* name; int n_ghost; };
inline constexpr LimiterTag kLimiters[] = {
  {"none", 1},
  {"minmod", 2},
  {"vanleer", 2},
  {"weno5", 3},
};

struct RiemannTag {
  const char* name; bool needs_wave_speeds; bool needs_hllc_struct;
  bool needs_roe_diss; bool polar_ok;
};
inline constexpr RiemannTag kRiemanns[] = {
  {"rusanov", false, false, false, true},
  {"hll", true, false, false, true},
  {"hllc", false, true, false, false},
  {"roe", false, false, true, false},
  {"euler_hllc", false, false, false, false},
  {"euler_roe", false, false, false, false},
};

struct TransportTag { const char* name; int n_vars; bool polar_ok; const char* summary; };
inline constexpr TransportTag kTransports[] = {
  {"exb", 1, true, "scalar ExB drift advection, v = (-d_y phi, d_x phi) / B0"},
  {"compressible", 4, false, "compressible Euler, 4 var (rho, rho u, rho v, E)"},
  {"isothermal", 3, true, "isothermal Euler, 3 var (rho, rho u, rho v)"},
};

struct SourceTag { const char* name; int min_vars; const char* summary; };
inline constexpr SourceTag kSources[] = {
  {"none", 1, "neutral: no source term"},
  {"potential", 3, "(q/m) rho E electrostatic force"},
  {"gravity", 3, "rho g gravity force"},
  {"magnetic", 3, "q v x B_z magnetized Lorentz force (explicit regime)"},
  {"potential_magnetic", 3, "electrostatic + Lorentz, summed"},
};

struct EllipticTag { const char* name; const char* summary; };
inline constexpr EllipticTag kElliptics[] = {
  {"charge", "rho - q : charge density (Poisson source)"},
  {"background", "alpha (rho - n0) : neutralizing background"},
  {"gravity", "sign * 4 pi G (rho - rho0) : gravitational coupling"},
};

struct BrickCatalogEntry {
  const char* id; const char* category; int route_index; const char* native_entry;
  const char* parameters; const char* parameters_json; int n_vars; bool polar_ok;
  const char* requirements; const char* requirements_json;
  const char* limitations; const char* limitations_json; const char* summary;
};
inline constexpr BrickCatalogEntry kBrickCatalog[] = {
  {"exb", "transport", 0, "pops::ExBVelocity", "B0", "[\"B0\"]", 1, true, "", "[]", "scalar (1 var); no fluid source", "[\"scalar (1 var); no fluid source\"]", "scalar ExB drift advection, v = (-d_y phi, d_x phi) / B0"},
  {"compressible", "transport", 1, "pops::CompressibleFlux", "gamma", "[\"gamma\"]", 4, false, "", "[]", "polar geometry not wired", "[\"polar geometry not wired\"]", "compressible Euler, 4 var (rho, rho u, rho v, E)"},
  {"isothermal", "transport", 2, "pops::IsothermalFlux", "cs2,vacuum_floor", "[\"cs2\",\"vacuum_floor\"]", 3, true, "", "[]", "", "[]", "isothermal Euler, 3 var (rho, rho u, rho v)"},
  {"none", "source", 0, "pops::NoSource", "", "[]", 1, false, "", "[]", "", "[]", "neutral: no source term"},
  {"potential", "source", 1, "pops::PotentialForce", "qom", "[\"qom\"]", 3, false, "fluid transport (>= 3 vars)", "[\"fluid transport (>= 3 vars)\"]", "", "[]", "(q/m) rho E electrostatic force"},
  {"gravity", "source", 2, "pops::GravityForce", "", "[]", 3, false, "fluid transport (>= 3 vars)", "[\"fluid transport (>= 3 vars)\"]", "", "[]", "rho g gravity force"},
  {"magnetic", "source", 3, "pops::MagneticLorentzForce", "qom", "[\"qom\"]", 3, false, "fluid transport (>= 3 vars),aux B_z channel", "[\"fluid transport (>= 3 vars)\",\"aux B_z channel\"]", "explicit regime (stiff regime -> condensed Schur stage)", "[\"explicit regime (stiff regime -> condensed Schur stage)\"]", "q v x B_z magnetized Lorentz force (explicit regime)"},
  {"potential_magnetic", "source", 4, "pops::CompositeSource<PotentialForce, MagneticLorentzForce>", "qom", "[\"qom\"]", 3, false, "fluid transport (>= 3 vars),aux B_z channel", "[\"fluid transport (>= 3 vars)\",\"aux B_z channel\"]", "", "[]", "electrostatic + Lorentz, summed"},
  {"charge", "elliptic", 0, "pops::ChargeDensity", "q", "[\"q\"]", -1, false, "", "[]", "", "[]", "rho - q : charge density (Poisson source)"},
  {"background", "elliptic", 1, "pops::BackgroundDensity", "alpha,n0", "[\"alpha\",\"n0\"]", -1, false, "", "[]", "", "[]", "alpha (rho - n0) : neutralizing background"},
  {"gravity", "elliptic", 2, "pops::GravityCoupling", "sign,four_pi_G,rho0", "[\"sign\",\"four_pi_G\",\"rho0\"]", -1, false, "", "[]", "", "[]", "sign * 4 pi G (rho - rho0) : gravitational coupling"},
};

inline constexpr int kComponentCatalogSchemaVersion = 1;
inline constexpr int kComponentManifestSchemaVersion = 2;
inline constexpr int kRouteRegistryVersion = 2;
inline constexpr int kCapabilityVocabularyVersion = 1;
inline constexpr const char* kComponentCatalogSha256 = "b709b8b15e073d7c20ca0114da924f37aaf605fbfdf02e015af8235042f32eb5";
inline constexpr const char* kComponentCatalogSemanticSha256 = "2655ee5697755f565c40d442de74d8be9e41948dae612b7e35a6c7741204a8f1";
inline constexpr const char* kRouteRegistrySignature = "v2:2655ee5697755f565c40d442de74d8be9e41948dae612b7e35a6c7741204a8f1";
inline constexpr const char* kComponentManifestSemanticFields[] = {
  "schema_version",
  "uri",
  "component_type",
  "version",
  "facets",
  "signature",
  "reads",
  "writes",
  "parameters",
  "interfaces",
  "requirements",
  "capabilities",
  "effects",
  "layouts",
  "clocks",
  "target",
  "determinism",
  "restart",
  "precision",
  "conservation",
  "entry_points",
};
inline constexpr const char* kComponentManifestTopLevelFields[] = {
  "schema_version",
  "uri",
  "component_type",
  "version",
  "facets",
  "signature",
  "reads",
  "writes",
  "parameters",
  "interfaces",
  "requirements",
  "capabilities",
  "effects",
  "layouts",
  "clocks",
  "target",
  "determinism",
  "restart",
  "precision",
  "conservation",
  "entry_points",
  "extensions",
  "digests",
};
inline constexpr const char* kComponentTargetFields[] = {
  "variants",
};
inline constexpr const char* kComponentDigestFields[] = {
  "semantic",
  "manifest",
};

}  // namespace pops
