#pragma once
// Generated by scripts/generate_release_contract.py; DO NOT EDIT.
// clang-format off
namespace pops::release_contract {
inline constexpr const char* kPackageVersion = "1.0.0";
inline constexpr int kReleaseContractSchemaVersion = 2;
inline constexpr int kPublicApiVersion = 1;
inline constexpr int kSemanticIrVersion = 1;
inline constexpr int kNormalizationVersion = 1;
inline constexpr int kComponentCatalogSchemaVersion = 1;
inline constexpr int kReleaseComponentManifestSchemaVersion = 2;
inline constexpr int kComponentRegistryVersion = 4;
inline constexpr int kReleaseCapabilityVocabularyVersion = 4;
inline constexpr int kComponentInterfaceAbiVersion = 1;
inline constexpr int kReleaseNativeAbiVersion = 3;
inline constexpr int kCheckpointEnvelopeSchemaVersion = 1;
inline constexpr int kCheckpointSpatialSchemaVersion = 1;
inline constexpr int kUniformCheckpointPayloadVersion = 6;
inline constexpr int kAmrCheckpointPayloadVersion = 8;
inline constexpr const char* kComponentCatalogSha256 = "70e3810ef372d4014b5f9ad36442bb24824acf5c0b5b7e06c5b0179456795edb";
inline constexpr const char* kComponentCatalogSemanticSha256 = "b126d0db6c54ed304aaffe3b67efaa4a0391393fc6febedf9ae4faa05328e4ec";
inline constexpr const char* kContractSha256 = "c5a660106eedf2277929ef463d66883d792d7edf87b312cfcba9adc7e1ba013f";
}  // namespace pops::release_contract
// clang-format on
