#pragma once

// Generated by scripts/generate_component_catalog.py; DO NOT EDIT.
// clang-format off
// The ABI crosses no C++ standard-library or backend-owned type. Hot interfaces are batch calls;
// discovery and symbol resolution happen once during installation, never inside a scientific loop.

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
#include <pops/runtime/dynamic/abi_key.hpp>

extern "C" {
#endif

#define POPS_COMPONENT_API_SYMBOL_V1 "pops_component_interface_v1"
#define POPS_COMPONENT_CATALOG_SHA256_V1 "b709b8b15e073d7c20ca0114da924f37aaf605fbfdf02e015af8235042f32eb5"
#define POPS_COMPONENT_PROTOCOL_ABI_V1 1u
#define POPS_COMPONENT_COMMON_ABI_V1 1u

typedef enum PopsNativeInterfaceIdV1 {
  POPS_NATIVE_INTERFACE_NUMERICAL_FLUX_V1 = 0,
  POPS_NATIVE_INTERFACE_GHOST_BOUNDARY_V1 = 1,
  POPS_NATIVE_INTERFACE_FIELD_BOUNDARY_CLOSURE_V1 = 2,
  POPS_NATIVE_INTERFACE_TAGGER_V1 = 3,
  POPS_NATIVE_INTERFACE_CLUSTERING_V1 = 4,
  POPS_NATIVE_INTERFACE_TRANSFER_V1 = 5,
  POPS_NATIVE_INTERFACE_FIELD_SOLVER_V2 = 7,
  POPS_NATIVE_INTERFACE_WRITER_V1 = 8,
  POPS_NATIVE_INTERFACE_FIELD_TOPOLOGY_V2 = 9,
} PopsNativeInterfaceIdV1;

typedef enum PopsTaggingOpcodeV1 {
  POPS_TAGGING_ABOVE_V1 = 1,
  POPS_TAGGING_BELOW_V1 = 2,
  POPS_TAGGING_MAGNITUDE_ABOVE_V1 = 3,
  POPS_TAGGING_GRADIENT_ABOVE_V1 = 4,
  POPS_TAGGING_GRADIENT_BELOW_V1 = 5,
  POPS_TAGGING_ANY_OF_V1 = 16,
  POPS_TAGGING_ALL_OF_V1 = 17,
  POPS_TAGGING_NOT_V1 = 18,
} PopsTaggingOpcodeV1;
#define POPS_TAGGING_MAXIMUM_INSTRUCTION_COUNT_V1 128u
#define POPS_TAGGING_MAXIMUM_STENCIL_TERMS_V1 16u
#define POPS_TAGGING_NO_STENCIL_V1 ((size_t)-1)
#define POPS_TAGGING_NON_FINITE_REJECT_V1 1
#define POPS_TAGGING_STENCIL_ROUTE_LINEAR_AXIS_STENCIL_L2_V1 "linear_axis_stencil_l2_v1"

static inline int pops_tagging_opcode_is_leaf_v1(int32_t opcode) {
  switch (opcode) { case POPS_TAGGING_ABOVE_V1: case POPS_TAGGING_BELOW_V1: case POPS_TAGGING_MAGNITUDE_ABOVE_V1: case POPS_TAGGING_GRADIENT_ABOVE_V1: case POPS_TAGGING_GRADIENT_BELOW_V1: return 1; default: return 0; }
}
static inline int pops_tagging_opcode_is_logical_v1(int32_t opcode) {
  switch (opcode) { case POPS_TAGGING_ANY_OF_V1: case POPS_TAGGING_ALL_OF_V1: case POPS_TAGGING_NOT_V1: return 1; default: return 0; }
}

typedef enum PopsComponentActionV1 {
  POPS_COMPONENT_CONTINUE_V1 = 0,
  POPS_COMPONENT_RETRY_STEP_V1 = 1,
  POPS_COMPONENT_REJECT_STEP_V1 = 2,
  POPS_COMPONENT_ABORT_RUN_V1 = 3
} PopsComponentActionV1;

typedef struct PopsComponentStatusV1 {
  uint32_t struct_size;
  int32_t code;
  PopsComponentActionV1 action;
  const char* reason;
} PopsComponentStatusV1;

typedef enum PopsMemorySpaceV1 {
  POPS_MEMORY_SPACE_HOST_V1 = 1,
  POPS_MEMORY_SPACE_DEVICE_V1 = 2,
  POPS_MEMORY_SPACE_MANAGED_V1 = 3
} PopsMemorySpaceV1;
typedef enum PopsScalarTypeV1 {
  POPS_SCALAR_FLOAT32_V1 = 1,
  POPS_SCALAR_FLOAT64_V1 = 2
} PopsScalarTypeV1;
typedef enum PopsFieldCenteringV1 {
  POPS_FIELD_CENTERING_CELL_V1 = 1,
  POPS_FIELD_CENTERING_FACE_V1 = 2,
  POPS_FIELD_CENTERING_NODE_V1 = 3,
  POPS_FIELD_CENTERING_EDGE_V1 = 4
} PopsFieldCenteringV1;
typedef enum PopsFieldOwnershipV1 {
  POPS_FIELD_OWNERSHIP_RUNTIME_BORROWED_V1 = 1,
  POPS_FIELD_OWNERSHIP_COMPONENT_BORROWED_V1 = 2,
  POPS_FIELD_OWNERSHIP_COMPONENT_OWNED_V1 = 3
} PopsFieldOwnershipV1;

typedef struct PopsConstFieldViewV1 {
  uint32_t struct_size;
  const void* data;
  int32_t dimension;
  size_t extents[3];
  ptrdiff_t axis_strides[3];
  size_t component_count;
  ptrdiff_t component_stride;
  PopsFieldCenteringV1 centering;
  uint32_t centering_axes;
  size_t ghost_lower[3];
  size_t ghost_upper[3];
  PopsScalarTypeV1 scalar_type;
  PopsMemorySpaceV1 memory_space;
  const char* layout_identity;
  const char* patch_identity;
  PopsFieldOwnershipV1 ownership;
} PopsConstFieldViewV1;

typedef struct PopsFieldViewV1 {
  uint32_t struct_size;
  void* data;
  int32_t dimension;
  size_t extents[3];
  ptrdiff_t axis_strides[3];
  size_t component_count;
  ptrdiff_t component_stride;
  PopsFieldCenteringV1 centering;
  uint32_t centering_axes;
  size_t ghost_lower[3];
  size_t ghost_upper[3];
  PopsScalarTypeV1 scalar_type;
  PopsMemorySpaceV1 memory_space;
  const char* layout_identity;
  const char* patch_identity;
  PopsFieldOwnershipV1 ownership;
} PopsFieldViewV1;

typedef struct PopsConstByteViewV1 {
  uint32_t struct_size;
  const uint8_t* data;
  size_t size;
} PopsConstByteViewV1;

typedef struct PopsByteViewV1 {
  uint32_t struct_size;
  uint8_t* data;
  size_t size;
} PopsByteViewV1;

typedef struct PopsInt32ViewV1 {
  uint32_t struct_size;
  int32_t* data;
  size_t size;
} PopsInt32ViewV1;

typedef struct PopsConstInt32ViewV1 {
  uint32_t struct_size;
  const int32_t* data;
  size_t size;
} PopsConstInt32ViewV1;

typedef struct PopsLogicalTimeV1 {
  uint32_t struct_size;
  const char* clock_identity;
  int64_t tick;
  int32_t level;
  int32_t substep;
  int32_t stage;
  int64_t fraction_numerator;
  int64_t fraction_denominator;
  double dt;
  double physical_time;
} PopsLogicalTimeV1;

typedef enum PopsPrecisionV1 {
  POPS_PRECISION_FLOAT16_V1 = 1,
  POPS_PRECISION_BFLOAT16_V1 = 2,
  POPS_PRECISION_FLOAT32_V1 = 3,
  POPS_PRECISION_FLOAT64_V1 = 4
} PopsPrecisionV1;
typedef struct PopsExecutionContextV1 {
  uint32_t struct_size;
  uint32_t context_version;
  const char* execution_identity;
  PopsMemorySpaceV1 memory_space;
  const char* backend_identity;
  const char* device_identity;
  PopsScalarTypeV1 scalar_type;
  PopsPrecisionV1 storage_precision;
  PopsPrecisionV1 compute_precision;
  PopsPrecisionV1 accumulation_precision;
  PopsPrecisionV1 reduction_precision;
  uint64_t stream_handle;
  const char* stream_identity;
  int64_t communicator_f_handle;
  int64_t communicator_datatype_f_handle;
  const char* communicator_identity;
  const char* communicator_datatype_identity;
} PopsExecutionContextV1;

typedef struct PopsComponentPrepareRequestV1 {
  uint32_t struct_size;
  const char* parameters_json;
  const char* target_json;
  PopsExecutionContextV1 execution;
} PopsComponentPrepareRequestV1;

typedef int32_t (*PopsComponentPrepareFnV1)(
    const PopsComponentPrepareRequestV1*, void**, PopsComponentStatusV1*);
typedef void (*PopsComponentDestroyFnV1)(void*);

typedef struct PopsComponentTableHeaderV1 {
  uint32_t struct_size;
  uint32_t abi_version;
  PopsNativeInterfaceIdV1 interface_id;
  uint32_t interface_version;
  PopsComponentPrepareFnV1 prepare;
  PopsComponentDestroyFnV1 destroy;
} PopsComponentTableHeaderV1;

typedef struct PopsNumericalFluxRequestV1 {
  uint32_t struct_size;
  PopsConstFieldViewV1 left;
  PopsConstFieldViewV1 right;
  PopsConstFieldViewV1 normals;
  const double* face_measures;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsNumericalFluxRequestV1;
typedef struct PopsNumericalFluxResultV1 {
  uint32_t struct_size;
  PopsFieldViewV1 normal_flux;
  double* stability_bounds;
  PopsComponentActionV1* actions;
  PopsComponentStatusV1 status;
} PopsNumericalFluxResultV1;
typedef int32_t (*PopsEvaluateFacesFnV1)(
    void*, const PopsNumericalFluxRequestV1*, PopsNumericalFluxResultV1*);
typedef struct PopsNumericalFluxApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsEvaluateFacesFnV1 evaluate_faces;
} PopsNumericalFluxApiV1;

typedef enum PopsBoundaryRegionKindV1 {
  POPS_BOUNDARY_FACE_V1 = 1,
  POPS_BOUNDARY_EDGE_V1 = 2,
  POPS_BOUNDARY_CORNER_V1 = 3
} PopsBoundaryRegionKindV1;
typedef struct PopsBoundaryRegionV1 {
  uint32_t struct_size;
  PopsBoundaryRegionKindV1 kind;
  int32_t dimension;
  int32_t codimension;
  size_t axis_count;
  const int32_t* axes;
  const int32_t* sides;
  const char* region_identity;
} PopsBoundaryRegionV1;
typedef struct PopsQualifiedConstFieldV1 {
  uint32_t struct_size;
  uint32_t present;
  const char* qualified_id;
  PopsConstFieldViewV1 values;
} PopsQualifiedConstFieldV1;
typedef struct PopsQualifiedFieldV1 {
  uint32_t struct_size;
  const char* qualified_id;
  PopsFieldViewV1 values;
} PopsQualifiedFieldV1;
typedef struct PopsQualifiedScalarV1 {
  uint32_t struct_size;
  const char* qualified_id;
  double value;
} PopsQualifiedScalarV1;
typedef struct PopsGhostBoundaryRequestV1 {
  uint32_t struct_size;
  const char* producer_identity;
  const char* state_identity;
  const char* ghost_identity;
  PopsConstFieldViewV1 interior;
  PopsFieldViewV1 ghosts;
  PopsConstFieldViewV1 coordinates;
  PopsBoundaryRegionV1 region;
  size_t dependency_count;
  const PopsQualifiedConstFieldV1* dependencies;
  size_t parameter_count;
  const PopsQualifiedScalarV1* parameters;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsGhostBoundaryRequestV1;
typedef int32_t (*PopsApplyRegionBatchFnV1)(
    void*, const PopsGhostBoundaryRequestV1*, PopsComponentStatusV1*);
typedef struct PopsGhostBoundaryApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsApplyRegionBatchFnV1 apply_region_batch;
} PopsGhostBoundaryApiV1;

typedef struct PopsFieldBoundaryRequestV1 {
  uint32_t struct_size;
  const char* closure_identity;
  PopsBoundaryRegionV1 region;
  PopsConstFieldViewV1 coordinates;
  size_t state_count;
  const PopsQualifiedConstFieldV1* states;
  size_t direction_count;
  const PopsQualifiedConstFieldV1* directions;
  size_t field_count;
  const PopsQualifiedConstFieldV1* fields;
  size_t parameter_count;
  const PopsQualifiedScalarV1* parameters;
  size_t output_count;
  PopsQualifiedFieldV1* outputs;
  PopsQualifiedConstFieldV1 rate;
  PopsQualifiedConstFieldV1 nonlinear_iterate;
  int32_t level;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsFieldBoundaryRequestV1;
typedef int32_t (*PopsFieldBoundaryEvalFnV1)(
    void*, const PopsFieldBoundaryRequestV1*, PopsComponentStatusV1*);
typedef struct PopsFieldBoundaryClosureApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsFieldBoundaryEvalFnV1 residual;
  PopsFieldBoundaryEvalFnV1 jvp;
} PopsFieldBoundaryClosureApiV1;

typedef struct PopsTaggingAxisStencilV1 {
  uint32_t struct_size;
  int32_t axis;
  int32_t derivative_order;
  int32_t formal_order;
  size_t ghost_lower;
  size_t ghost_upper;
  size_t term_count;
  const int32_t* offsets;
  const double* coefficients;
} PopsTaggingAxisStencilV1;
typedef struct PopsTaggingStencilV1 {
  uint32_t struct_size;
  const char* stencil_identity;
  const char* route;
  const char* norm;
  const char* scale;
  const char* boundary_mode;
  int32_t dimension;
  size_t axis_count;
  const PopsTaggingAxisStencilV1* axes;
} PopsTaggingStencilV1;
typedef struct PopsTaggingLeafV1 {
  uint32_t struct_size;
  size_t state_index;
  size_t component;
  int32_t opcode;
  double threshold;
  size_t stencil_index;
} PopsTaggingLeafV1;
typedef struct PopsTaggingProgramV1 {
  uint32_t struct_size;
  const char* program_identity;
  size_t stencil_count;
  const PopsTaggingStencilV1* stencils;
  size_t leaf_count;
  const PopsTaggingLeafV1* leaves;
  size_t refine_instruction_count;
  const int32_t* refine_opcodes;
  const int32_t* refine_arguments;
  size_t coarsen_instruction_count;
  const int32_t* coarsen_opcodes;
  const int32_t* coarsen_arguments;
  int32_t minimum_cycles;
  int32_t equality_policy;
  int32_t conflict_policy;
  int32_t non_finite_policy;
} PopsTaggingProgramV1;
typedef struct PopsTaggerRequestV1 {
  uint32_t struct_size;
  size_t state_count;
  const PopsQualifiedConstFieldV1* states;
  PopsTaggingProgramV1 program;
  int64_t patch_lower[3];
  int64_t domain_lower[3];
  int64_t domain_upper[3];
  double cell_size[3];
  uint32_t periodic_axes;
  PopsByteViewV1 refine_candidates;
  PopsByteViewV1 coarsen_candidates;
  PopsByteViewV1 refine_equalities;
  PopsByteViewV1 coarsen_equalities;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsTaggerRequestV1;
typedef int32_t (*PopsTagBatchFnV1)(void*, const PopsTaggerRequestV1*, PopsComponentStatusV1*);
typedef struct PopsTaggerApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsTagBatchFnV1 tag_batch;
} PopsTaggerApiV1;

typedef struct PopsClusteringRequestV1 {
  uint32_t struct_size;
  PopsConstByteViewV1 tags;
  const int64_t* extents;
  int32_t dimension;
  // `boxes` is box-major [lo_0..lo_(d-1), hi_0..hi_(d-1)]. Bounds are
  // inclusive and relative to the supplied tag region.
  int64_t* boxes;
  size_t box_capacity;
  size_t* box_count;
  PopsExecutionContextV1 execution;
} PopsClusteringRequestV1;
typedef int32_t (*PopsClusterFnV1)(void*, const PopsClusteringRequestV1*, PopsComponentStatusV1*);
typedef struct PopsClusteringApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsClusterFnV1 cluster;
} PopsClusteringApiV1;

typedef enum PopsTransferOperationV1 {
  POPS_TRANSFER_OPERATION_CONSERVATIVE_CELL_AVERAGE_V1 = 1
} PopsTransferOperationV1;
typedef struct PopsTransferRequestV1 {
  uint32_t struct_size;
  PopsConstFieldViewV1 source;
  PopsFieldViewV1 destination;
  const int32_t* refinement_ratio;
  int32_t dimension;
  PopsTransferOperationV1 operation;
  PopsExecutionContextV1 execution;
} PopsTransferRequestV1;
typedef int32_t (*PopsTransferApplyFnV1)(void*, const PopsTransferRequestV1*, PopsComponentStatusV1*);
typedef struct PopsTransferApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsTransferApplyFnV1 apply;
} PopsTransferApiV1;

typedef struct PopsFieldPatchMetadataV1 {
  uint32_t struct_size;
  size_t global_patch_index;
  int32_t owner_rank;
  int32_t level;
  int32_t dimension;
  int64_t lower[3];
  int64_t upper[3];
  // Physical coordinate of the lower face at `lower`, not the global-domain origin.
  double physical_lower[3];
  double cell_spacing[3];
  PopsFieldCenteringV1 centering;
  uint32_t centering_axes;
  // Qualified source LayoutPlan identity; materialization is carried by global topology.
  const char* layout_identity;
  const char* patch_identity;
} PopsFieldPatchMetadataV1;

typedef enum PopsFieldMaterialRepresentationV1 {
  POPS_FIELD_MATERIAL_FULL_V1 = 1,
  POPS_FIELD_MATERIAL_BINARY_COVERAGE_V1 = 2,
  POPS_FIELD_MATERIAL_CUT_CELL_FRACTION_V1 = 3,
  POPS_FIELD_MATERIAL_IDS_V1 = 4,
  POPS_FIELD_MATERIAL_IDS_WITH_CUT_CELL_FRACTION_V1 = 5
} PopsFieldMaterialRepresentationV1;

typedef struct PopsFieldGlobalTopologyV1 {
  uint32_t struct_size;
  const char* topology_recipe_identity;
  // Qualified authoring LayoutPlan identity, preserved on every FieldView.
  const char* source_layout_identity;
  // Exact runtime materialization identity: source layout + geometry + boxes + owners + topology.
  const char* materialized_layout_identity;
  int32_t dimension;
  int64_t domain_lower[3];
  int64_t domain_upper[3];
  uint32_t periodic_axes;
  size_t patch_count;
  const PopsFieldPatchMetadataV1* patches;
} PopsFieldGlobalTopologyV1;

typedef struct PopsFieldSolverTopologyLabelV2 {
  uint32_t struct_size;
  int32_t id;
  const char* label;
  const char* provenance;
} PopsFieldSolverTopologyLabelV2;

typedef struct PopsFieldSolverPatchV2 {
  uint32_t struct_size;
  size_t metadata_index;
  PopsConstFieldViewV1 rhs;
  PopsFieldViewV1 solution;
  PopsConstFieldViewV1 coefficients;
  PopsConstByteViewV1 material_mask;
  PopsConstInt32ViewV1 component_labels;
} PopsFieldSolverPatchV2;

typedef struct PopsFieldSolverRequestV2 {
  uint32_t struct_size;
  PopsFieldGlobalTopologyV1 topology;
  size_t local_patch_count;
  const PopsFieldSolverPatchV2* local_patches;
  size_t topology_label_count;
  const PopsFieldSolverTopologyLabelV2* topology_labels;
  const char* topology_provenance;
  const char* topology_digest;
  const char* boundary_contract_json;
  double relative_tolerance;
  double absolute_tolerance;
  int32_t max_iterations;
  PopsExecutionContextV1 execution;
} PopsFieldSolverRequestV2;

typedef enum PopsSolveStatusV2 {
  POPS_SOLVE_SOLVED_V2 = 0,
  POPS_SOLVE_SINGULAR_V2 = 1,
  POPS_SOLVE_BREAKDOWN_V2 = 2,
  POPS_SOLVE_ITERATION_LIMIT_V2 = 3,
  POPS_SOLVE_INVALID_EVALUATION_V2 = 4,
  POPS_SOLVE_CAPABILITY_FAILURE_V2 = 5,
  POPS_SOLVE_INVALID_INPUT_V2 = 6,
  POPS_SOLVE_INCOMPATIBLE_RHS_V2 = 7
} PopsSolveStatusV2;

typedef enum PopsSolveActionV2 {
  POPS_SOLVE_ACTION_NONE_V2 = 0,
  POPS_SOLVE_ACTION_FAIL_RUN_V2 = 1,
  POPS_SOLVE_ACTION_REJECT_ATTEMPT_V2 = 2
} PopsSolveActionV2;

typedef struct PopsSolveReportV2 {
  uint32_t struct_size;
  PopsSolveStatusV2 status;
  PopsSolveActionV2 action;
  int32_t iterations;
  // residual_norm / reference_residual_norm, using denominator 1 only when the reference is zero.
  double relative_residual;
  // Exact ||R(x0)|| used by max(relative_tolerance * ||R(x0)||, absolute_tolerance).
  double reference_residual_norm;
  // Exact ||R(x_final)|| tested against the mixed convergence threshold.
  double residual_norm;
  const char* reason;
} PopsSolveReportV2;
typedef int32_t (*PopsFieldSolveFnV2)(
    void*, const PopsFieldSolverRequestV2*, PopsSolveReportV2*);
typedef struct PopsFieldSolverApiV2 {
  PopsComponentTableHeaderV1 header;
  PopsFieldSolveFnV2 solve;
} PopsFieldSolverApiV2;

typedef struct PopsWriterBoxV1 {
  uint32_t struct_size;
  int32_t dimension;
  const int64_t* lower;
  const int64_t* upper;
} PopsWriterBoxV1;
typedef struct PopsWriterGeometryV1 {
  uint32_t struct_size;
  const char* layout_identity;
  const char* layout_kind;
  int32_t level;
  int32_t dimension;
  const double* origin;
  const double* spacing;
  const size_t* cell_shape;
  size_t box_count;
  const PopsWriterBoxV1* boxes;
  PopsConstByteViewV1 valid_cells;
  PopsConstByteViewV1 coverage;
  PopsConstFieldViewV1 cell_volumes;
} PopsWriterGeometryV1;
typedef struct PopsWriterPieceV1 {
  uint32_t struct_size;
  int32_t dimension;
  const int64_t* lower;
  const int64_t* upper;
  PopsConstFieldViewV1 values;
} PopsWriterPieceV1;
typedef struct PopsWriterFieldV1 {
  uint32_t struct_size;
  const char* field_identity;
  const char* reference_id;
  const char* component_manifest_identity;
  const char* layout_identity;
  int32_t level;
  const char* state_id;
  const char* centering;
  const char* units;
  size_t component_name_count;
  const char* const* component_names;
  int32_t dimension;
  const size_t* global_shape;
  size_t piece_count;
  const PopsWriterPieceV1* pieces;
} PopsWriterFieldV1;
typedef struct PopsWriterDiagnosticV1 {
  uint32_t struct_size;
  const char* diagnostic_identity;
  const char* reference_id;
  const char* component_manifest_identity;
  const char* layout_identity;
  int32_t level;
  const char* state_id;
  const char* reduction;
  double value;
  const char* units;
  const char* terms_json;
} PopsWriterDiagnosticV1;
typedef struct PopsWriterRequestV1 {
  uint32_t struct_size;
  size_t geometry_count;
  const PopsWriterGeometryV1* geometries;
  size_t field_count;
  const PopsWriterFieldV1* fields;
  size_t diagnostic_count;
  const PopsWriterDiagnosticV1* diagnostics;
  const char* metadata_json;
  const char* selection_identity;
  const char* temporary_path;
  const char* published_path;
  const char* snapshot_identity;
  PopsLogicalTimeV1 logical_time;
  PopsExecutionContextV1 execution;
} PopsWriterRequestV1;
typedef struct PopsWriterReceiptV1 {
  uint32_t struct_size;
  uint64_t bytes_written;
  const char* content_digest;
  PopsComponentStatusV1 status;
} PopsWriterReceiptV1;
typedef int32_t (*PopsWriterVerifyFnV1)(void*, const PopsWriterRequestV1*, PopsWriterReceiptV1*);
typedef int32_t (*PopsWriterPublishFnV1)(void*, const PopsWriterRequestV1*, PopsWriterReceiptV1*);
typedef void (*PopsWriterCleanupFnV1)(void*, const PopsWriterRequestV1*);
typedef struct PopsWriterApiV1 {
  PopsComponentTableHeaderV1 header;
  PopsWriterVerifyFnV1 verify;
  PopsWriterPublishFnV1 publish;
  PopsWriterCleanupFnV1 discard;
  PopsWriterCleanupFnV1 rollback;
} PopsWriterApiV1;

typedef struct PopsFieldTopologyPatchV2 {
  uint32_t struct_size;
  size_t metadata_index;
  PopsFieldMaterialRepresentationV1 material_representation;
  PopsConstByteViewV1 material_coverage;
  PopsConstFieldViewV1 cut_cell_volume_fraction;
  PopsConstInt32ViewV1 material_ids;
  PopsByteViewV1 material_mask;
  PopsInt32ViewV1 component_labels;
} PopsFieldTopologyPatchV2;
typedef struct PopsFieldTopologyRequestV2 {
  uint32_t struct_size;
  PopsFieldGlobalTopologyV1 topology;
  size_t local_patch_count;
  const PopsFieldTopologyPatchV2* local_patches;
  PopsExecutionContextV1 execution;
} PopsFieldTopologyRequestV2;
typedef struct PopsTopologyLabelV2 {
  uint32_t struct_size;
  int32_t id;
  const char* label;
  const char* provenance;
} PopsTopologyLabelV2;
typedef struct PopsFieldTopologyResultV2 {
  uint32_t struct_size;
  size_t label_count;
  const PopsTopologyLabelV2* labels;
  const char* provenance;
  const char* topology_digest;
  PopsComponentStatusV1 status;
} PopsFieldTopologyResultV2;
typedef int32_t (*PopsPrepareTopologyFnV2)(
    void*, const PopsFieldTopologyRequestV2*, PopsFieldTopologyResultV2*);
typedef struct PopsFieldTopologyApiV2 {
  PopsComponentTableHeaderV1 header;
  PopsPrepareTopologyFnV2 prepare_topology;
} PopsFieldTopologyApiV2;

typedef struct PopsComponentInterfaceEntryV1 {
  PopsNativeInterfaceIdV1 interface_id;
  uint32_t interface_version;
  uint32_t table_size;
  const void* table;
} PopsComponentInterfaceEntryV1;

typedef struct PopsComponentApiV1 {
  uint32_t struct_size;
  uint32_t protocol_abi;
  // Translation-unit-local native ABI identity. C++ providers use POPS_ABI_KEY_LITERAL; C
  // providers must emit the exact equivalent literal selected by their PoPS build.
  const char* abi_key;
  const char* catalog_sha256;
  const char* component_id;
  const char* semantic_identity;
  const char* manifest_identity;
  size_t interface_count;
  const PopsComponentInterfaceEntryV1* interfaces;
} PopsComponentApiV1;

typedef const PopsComponentApiV1* (*PopsComponentApiGetterV1)(void);

#ifdef __cplusplus
}  // extern "C"

namespace pops::component {
inline constexpr size_t generated_native_interface_table_size(
    PopsNativeInterfaceIdV1 id) noexcept {
  switch (id) {
    case POPS_NATIVE_INTERFACE_NUMERICAL_FLUX_V1: return sizeof(PopsNumericalFluxApiV1);
    case POPS_NATIVE_INTERFACE_GHOST_BOUNDARY_V1: return sizeof(PopsGhostBoundaryApiV1);
    case POPS_NATIVE_INTERFACE_FIELD_BOUNDARY_CLOSURE_V1: return sizeof(PopsFieldBoundaryClosureApiV1);
    case POPS_NATIVE_INTERFACE_TAGGER_V1: return sizeof(PopsTaggerApiV1);
    case POPS_NATIVE_INTERFACE_CLUSTERING_V1: return sizeof(PopsClusteringApiV1);
    case POPS_NATIVE_INTERFACE_TRANSFER_V1: return sizeof(PopsTransferApiV1);
    case POPS_NATIVE_INTERFACE_FIELD_SOLVER_V2: return sizeof(PopsFieldSolverApiV2);
    case POPS_NATIVE_INTERFACE_WRITER_V1: return sizeof(PopsWriterApiV1);
    case POPS_NATIVE_INTERFACE_FIELD_TOPOLOGY_V2: return sizeof(PopsFieldTopologyApiV2);
  }
  return 0;
}
inline constexpr const char* generated_native_interface_table_name(
    PopsNativeInterfaceIdV1 id) noexcept {
  switch (id) {
    case POPS_NATIVE_INTERFACE_NUMERICAL_FLUX_V1: return "PopsNumericalFluxApiV1";
    case POPS_NATIVE_INTERFACE_GHOST_BOUNDARY_V1: return "PopsGhostBoundaryApiV1";
    case POPS_NATIVE_INTERFACE_FIELD_BOUNDARY_CLOSURE_V1: return "PopsFieldBoundaryClosureApiV1";
    case POPS_NATIVE_INTERFACE_TAGGER_V1: return "PopsTaggerApiV1";
    case POPS_NATIVE_INTERFACE_CLUSTERING_V1: return "PopsClusteringApiV1";
    case POPS_NATIVE_INTERFACE_TRANSFER_V1: return "PopsTransferApiV1";
    case POPS_NATIVE_INTERFACE_FIELD_SOLVER_V2: return "PopsFieldSolverApiV2";
    case POPS_NATIVE_INTERFACE_WRITER_V1: return "PopsWriterApiV1";
    case POPS_NATIVE_INTERFACE_FIELD_TOPOLOGY_V2: return "PopsFieldTopologyApiV2";
  }
  return nullptr;
}
}  // namespace pops::component
#endif
// clang-format on
